//client/src/components/PCBuilder/Modal/MockData/Power Supply/PowerSupply.js
export const powerSupplyData = [
  {
    id: 'psu-1',
    name: 'Corsair RM1000x 1000W 80+ Gold Modular',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 10830.00, // Converted from 189.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Gold",
      "Modularity": "Full Modular",
      "Manufacturer": "Corsair",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "1000 W",
      "Length": "160 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 1,
      "PCIe 6+2-pin": 8,
      "SATA": 12,
      "Molex 4-pin": 4,
      "Fan Size": "135 mm",
      "Fan Bearing": "Rifle Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "10 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-2',
    name: 'Seasonic FOCUS GX-850 850W 80+ Gold',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 8550.00, // Converted from 149.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Gold",
      "Modularity": "Full Modular",
      "Manufacturer": "Seasonic",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "850 W",
      "Length": "140 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 0,
      "PCIe 6+2-pin": 6,
      "SATA": 9,
      "Molex 4-pin": 3,
      "Fan Size": "120 mm",
      "Fan Bearing": "Fluid Dynamic Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "10 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-3',
    name: 'EVGA SuperNOVA 1600 T2 1600W 80+ Titanium',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 28500.00, // Converted from 499.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Titanium",
      "Modularity": "Full Modular",
      "Manufacturer": "EVGA",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "1600 W",
      "Length": "200 mm",
      "EPS 8-pin (CPU)": 4,
      "PCIe 12VHPWR": 2,
      "PCIe 6+2-pin": 14,
      "SATA": 18,
      "Molex 4-pin": 8,
      "Fan Size": "140 mm",
      "Fan Bearing": "Double Ball Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "10 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-4',
    name: 'Corsair SF750 750W 80+ Platinum SFX',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 10260.00, // Converted from 179.99 USD to PHP
    specs: {
      "Form Factor": "SFX",
      "Efficiency Rating": "80+ Platinum",
      "Modularity": "Full Modular",
      "Manufacturer": "Corsair",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "750 W",
      "Length": "100 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 0,
      "PCIe 6+2-pin": 4,
      "SATA": 8,
      "Molex 4-pin": 8,
      "Fan Size": "92 mm",
      "Fan Bearing": "Rifle Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "7 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-5',
    name: 'be quiet! Straight Power 11 650W 80+ Platinum',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 7410.00, // Converted from 129.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Platinum",
      "Modularity": "Full Modular",
      "Manufacturer": "be quiet!",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "650 W",
      "Length": "160 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 0,
      "PCIe 6+2-pin": 4,
      "SATA": 8,
      "Molex 4-pin": 3,
      "Fan Size": "135 mm",
      "Fan Bearing": "Rifle Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 0
    },
  {
    id: 'psu-6',
    name: 'Thermaltake Toughpower GF3 1350W 80+ Gold',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 13110.00, // Converted from 229.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Gold",
      "Modularity": "Full Modular",
      "Manufacturer": "Thermaltake",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "1350 W",
      "Length": "150 mm",
      "EPS 8-pin (CPU)": 3,
      "PCIe 12VHPWR": 2,
      "PCIe 6+2-pin": 8,
      "SATA": 12,
      "Molex 4-pin": 4,
      "Fan Size": "140 mm",
      "Fan Bearing": "Fluid Dynamic Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "10 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-7',
    name: 'Cooler Master V850 Gold V2 850W 80+ Gold',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 7980.00, // Converted from 139.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Gold",
      "Modularity": "Full Modular",
      "Manufacturer": "Cooler Master",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "850 W",
      "Length": "140 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 0,
      "PCIe 6+2-pin": 6,
      "SATA": 9,
      "Molex 4-pin": 3,
      "Fan Size": "120 mm",
      "Fan Bearing": "Rifle Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "10 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-8',
    name: 'ASUS ROG Thor 1200P2 1200W 80+ Platinum',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 19950.00, // Converted from 349.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Platinum",
      "Modularity": "Full Modular",
      "Manufacturer": "ASUS",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "1200 W",
      "Length": "190 mm",
      "EPS 8-pin (CPU)": 3,
      "PCIe 12VHPWR": 1,
      "PCIe 6+2-pin": 10,
      "SATA": 14,
      "Molex 4-pin": 6,
      "Fan Size": "135 mm",
      "Fan Bearing": "Axial-tech Fan",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "10 years"
    },
    has3D: true,
    stockCount: 10
    },
  {
    id: 'psu-9',
    name: 'SeaSonic PRIME TX-1000 1000W 80+ Titanium',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 17100.00, // Converted from 299.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Titanium",
      "Modularity": "Full Modular",
      "Manufacturer": "SeaSonic",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "1000 W",
      "Length": "170 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 1,
      "PCIe 6+2-pin": 8,
      "SATA": 12,
      "Molex 4-pin": 4,
      "Fan Size": "135 mm",
      "Fan Bearing": "Fluid Dynamic Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "12 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-10',
    name: 'EVGA 600 BR 600W 80+ Bronze',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 3420.00, // Converted from 59.99 USD PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Bronze",
      "Modularity": "Non-Modular",
      "Manufacturer": "EVGA",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "600 W",
      "Length": "140 mm",
      "EPS 8-pin (CPU)": 1,
      "PCIe 12VHPWR": 0,
      "PCIe 6+2-pin": 2,
      "SATA": 6,
      "Molex 4-pin": 3,
      "Fan Size": "120 mm",
      "Fan Bearing": "Sleeve Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "3 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-11',
    name: 'FSP Group Dagger Pro 850W 80+ Gold SFX',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 9120.00, // Converted from 159.99 USD to PHP
    specs: {
      "Form Factor": "SFX",
      "Efficiency Rating": "80+ Gold",
      "Modularity": "Full Modular",
      "Manufacturer": "FSP Group",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "850 W",
      "Length": "100 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 1,
      "PCIe 6+2-pin": 4,
      "SATA": 8,
      "Molex 4-pin": 2,
      "Fan Size": "92 mm",
      "Fan Bearing": "Fluid Dynamic Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "5 years"
  },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-12',
    name: 'NZXT C1200 1200W 80+ Gold',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 14250.00, // Converted from 249.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Gold",
      "Modularity": "Full Modular",
      "Manufacturer": "NZXT",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "1200 W",
      "Length": "150 mm",
      "EPS 8-pin (CPU)": 3,
      "PCIe 12VHPWR": 2,
      "PCIe 6+2-pin": 8,
      "SATA": 12,
      "Molex 4-pin": 4,
      "Fan Size": "140 mm",
      "Fan Bearing": "Fluid Dynamic Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "10 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-13',
    name: 'Super Flower Leadex III Gold 850W 80+ Gold',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 7410.00, // Converted from 129.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Gold",
      "Modularity": "Full Modular",
      "Manufacturer": "Super Flower",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "850 W",
      "Length": "160 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 0,
      "PCIe 6+2-pin": 6,
      "SATA": 9,
      "Molex 4-pin": 3,
      "Fan Size": "135 mm",
      "Fan Bearing": "Fluid Dynamic Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "10 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-14',
    name: 'Phanteks AMP 1000W 80+ Gold',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 9690.00, // Converted from 169.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Gold",
      "Modularity": "Full Modular",
      "Manufacturer": "Phanteks",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "1000 W",
      "Length": "160 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 1,
      "PCIe 6+2-pin": 8,
      "SATA": 12,
      "Molex 4-pin": 4,
      "Fan Size": "135 mm",
      "Fan Bearing": "Fluid Dynamic Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "10 years"
    },
    has3D: false,
    stockCount: 0
    },
  {
    id: 'psu-15',
    name: 'be quiet! Dark Power 13 850W 80+ Titanium',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 14250.00, // Converted from 249.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Titanium",
      "Modularity": "Full Modular",
      "Manufacturer": "be quiet!",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "850 W",
      "Length": "150 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 1,
      "PCIe 6+2-pin": 6,
      "SATA": 9,
      "Molex 4-pin": 3,
      "Fan Size": "135 mm",
      "Fan Bearing": "Rifle Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-16',
    name: 'SilverStone Extreme 850R Platinum 850W 80+ Platinum',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 10260.00, // Converted from 179.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Platinum",
      "Modularity": "Full Modular",
      "Manufacturer": "SilverStone",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "850 W",
      "Length": "150 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 1,
      "PCIe 6+2-pin": 6,
      "SATA": 9,
      "Molex 4-pin": 3,
      "Fan Size": "120 mm",
      "Fan Bearing": "Fluid Dynamic Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "7 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-17',
    name: 'Gigabyte UD850GM 850W 80+ Gold',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 6840.00, // Converted from 119.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Gold",
      "Modularity": "Semi-Modular",
      "Manufacturer": "Gigabyte",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "850 W",
      "Length": "150 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 0,
      "PCIe 6+2-pin": 6,
      "SATA": 9,
      "Molex 4-pin": 3,
      "Fan Size": "120 mm",
      "Fan Bearing": "Hydraulic Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-18',
    name: 'Cooler Master V550 Gold V2 550W 80+ Gold',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 5130.00, // Converted from 89.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Gold",
      "Modularity": "Full Modular",
      "Manufacturer": "Cooler Master",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "550 W",
      "Length": "140 mm",
      "EPS 8-pin (CPU)": 1,
      "PCIe 12VHPWR": 0,
      "PCIe 6+2-pin": 4,
      "SATA": 6,
      "Molex 4-pin": 2,
      "Fan Size": "120 mm",
      "Fan Bearing": "Rifle Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "10 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-19',
    name: 'Seasonic FOCUS SPX-750 750W 80+ Platinum SFX-L',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 10830.00, // Converted from 189.99 USD to PHP
    specs: {
      "Form Factor": "SFX-L",
      "Efficiency Rating": "80+ Platinum",
      "Modularity": "Full Modular",
      "Manufacturer": "Seasonic",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "750 W",
      "Length": "125 mm",
      "EPS 8-pin (CPU)": 2,
      "PCIe 12VHPWR": 0,
      "PCIe 6+2-pin": 4,
      "SATA": 8,
      "Molex 4-pin": 2,
      "Fan Size": "120 mm",
      "Fan Bearing": "Fluid Dynamic Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "10 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'psu-20',
    name: 'EVGA SuperNOVA 550 G3 550W 80+ Gold',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 5700.00, // Converted from 99.99 USD to PHP
    specs: {
      "Form Factor": "ATX",
      "Efficiency Rating": "80+ Gold",
      "Modularity": "Full Modular",
      "Manufacturer": "EVGA",
      "Color": "BLACK",
      "Fanless": "No",
      "Wattage": "550 W",
      "Length": "150 mm",
      "EPS 8-pin (CPU)": 1,
      "PCIe 12VHPWR": 0,
      "PCIe 6+2-pin": 4,
      "SATA": 6,
      "Molex 4-pin": 2,
      "Fan Size": "130 mm",
      "Fan Bearing": "Double Ball Bearing",
      "Protections": "OPP, OVP, UVP, OCP, OTP, SCP",
      "Warranty": "7 years"
    },
    has3D: false,
    stockCount: 10
    }
];
