// client/src/components/MockData/desktopProducts.js
import SampleImg from "../../assets/Laptop1.png";

export const desktopProducts = [
  {
    id: 1,
    name: "Gaming Desktop Pro",
    brand: "NVIDIA",
    description: "High-performance gaming desktop with RTX 4080",
    img: SampleImg,
    price: 85999,
    oldPrice: 89999,
    rating: 4.8,
    reviews: 124,
    category: "Gaming Desktops",
    series: "meg-series",
    subcategory: "latest-gpu-technology",
    specs: {
      gpu: "rtx4070",
      processor: "intel-i9",
      screenSize: "17",
      ram: "32gb",
      storage: "1tb",
    },
  },
  {
    id: 2,
    name: "Workstation Elite",
    brand: "Intel",
    description: "Professional workstation for content creators",
    img: SampleImg,
    price: 72999,
    oldPrice: 78999,
    rating: 4.6,
    reviews: 87,
    category: "Workstation Desktops",
    series: "wt-series",
    subcategory: "creator",
    specs: {
      gpu: "rtx4050",
      processor: "intel-i5",
      screenSize: "15",
      ram: "16gb",
      storage: "512gb",
    },
  },
  {
    id: 3,
    name: "Streamer PC",
    brand: "AMD",
    description: "Optimized for streaming and gaming simultaneously",
    img: SampleImg,
    price: 65999,
    oldPrice: 0,
    rating: 4.7,
    reviews: 56,
    category: "Gaming Desktops",
    series: "mpg-series",
    subcategory: "streaming",
    specs: {
      gpu: "rtx4080",
      processor: "intel-i9",
      screenSize: "17",
      ram: "32gb",
      storage: "2tb",
    },
  },
  {
    id: 4,
    name: "Budget Gaming PC",
    brand: "ASUS",
    description: "Entry-level gaming desktop with great performance",
    img: SampleImg,
    price: 42999,
    oldPrice: 45999,
    rating: 4.5,
    reviews: 203,
    category: "Gaming Desktops",
    series: "codex-series",
    subcategory: "budget",
    specs: {
      gpu: "rtx4060",
      processor: "amd-ryzen9",
      screenSize: "16",
      ram: "32gb",
      storage: "1tb",
    },
  },
  {
    id: 5,
    name: "Mini ITX Build",
    brand: "MSI",
    description: "Compact gaming PC with powerful components",
    img: SampleImg,
    price: 57999,
    oldPrice: 61999,
    rating: 4.9,
    reviews: 42,
    category: "Mini PCs",
    series: "gaming-cube-series",
    subcategory: "mini-itx",
    specs: {
      gpu: "rtx5000",
      processor: "intel-xeon",
      screenSize: "17",
      ram: "64gb",
      storage: "2tb",
    },
  },
  {
    id: 6,
    name: "RGB Gaming Beast",
    brand: "Corsair",
    description: "Fully customized RGB gaming desktop",
    img: SampleImg,
    price: 78999,
    oldPrice: 84999,
    rating: 4.8,
    reviews: 91,
    category: "Gaming Desktops",
    series: "meg-series",
    subcategory: "rgb",
    specs: {
      gpu: "apple-silicon",
      processor: "apple-m2",
      screenSize: "16",
      ram: "32gb",
      storage: "1tb",
    },
  },
  {
    id: 7,
    name: "Silent Workstation",
    brand: "Be Quiet!",
    description: "Whisper quiet performance for professionals",
    img: SampleImg,
    price: 68999,
    oldPrice: 0,
    rating: 4.7,
    reviews: 38,
    category: "Workstation Desktops",
    series: "wt-series",
    subcategory: "silent",
    specs: {
      gpu: "integrated",
      processor: "intel-i5",
      screenSize: "15",
      ram: "16gb",
      storage: "512gb",
    },
  },
  {
    id: 8,
    name: "VR Ready Desktop",
    brand: "HP",
    description: "Optimized for virtual reality experiences",
    img: SampleImg,
    price: 75999,
    oldPrice: 79999,
    rating: 4.6,
    reviews: 67,
    category: "All-in-One PCs",
    series: "creative-aio-series",
    subcategory: "vr-ready",
    specs: {
      gpu: "integrated",
      processor: "intel-i7",
      screenSize: "14",
      ram: "16gb",
      storage: "512gb",
    },
  },
];