//client/src/components/PCBuilder/Modal/MockData/Microphone/Microphone.js
export const microphoneData = [
  {
    id: 'microphone-1',
    name: 'Blue Yeti USB Microphone',
    image: "/src/assets/Laptop1.png",
    price: 129.99,
    specs: {
      "Brand": "Logitech for Creators",
      "Type": "Condenser",
      "Patterns": "Cardioid, Bidirectional, Omnidirectional, Stereo",
      "Connectivity": "USB",
      "Sample Rate": "48 kHz",
      "Bit Depth": "16-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "4.5mV/Pa",
      "Max SPL": "120 dB",
      "Polar Patterns": 4,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "1.2 lbs",
      "Dimensions": "4.9 x 4.7 x 11.6 inches"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'microphone-2',
    name: 'Audio-Technica AT2020USB+ Cardioid Condenser USB Microphone',
    image: "/src/assets/Laptop1.png",
    price: 149.00,
    specs: {
      "Brand": "Audio-Technica",
      "Type": "Condenser",
      "Patterns": "Cardioid",
      "Connectivity": "USB",
      "Sample Rate": "44.1/48 kHz",
      "Bit Depth": "16-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "144 dB",
      "Polar Patterns": 1,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "1.2 lbs",
      "Dimensions": "6.38 x 2.05 x 2.05 inches"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'microphone-3',
    name: 'Razer Seiren V2 Pro USB Streaming Microphone',
    image: "/src/assets/Laptop1.png",
    price: 159.99,
    specs: {
      "Brand": "Razer",
      "Type": "Condenser",
      "Patterns": "Cardioid",
      "Connectivity": "USB",
      "Sample Rate": "48 kHz",
      "Bit Depth": "24-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "120 dB",
      "Polar Patterns": 1,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "1.8 lbs",
      "Dimensions": "6.3 x 4.1 x 12.2 inches"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'microphone-4',
    name: 'HyperX QuadCast S USB Condenser Microphone',
    image: "/src/assets/Laptop1.png",
    price: 159.99,
    specs: {
      "Brand": "HyperX",
      "Type": "Condenser",
      "Patterns": "Cardioid, Stereo, Omnidirectional, Bidirectional",
      "Connectivity": "USB",
      "Sample Rate": "48 kHz",
      "Bit Depth": "16-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "120 dB",
      "Polar Patterns": 4,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "1.65 lbs",
      "Dimensions": "5.71 x 5.71 x 10.04 inches",
      "RGB Lighting": "Yes"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'microphone-5',
    name: 'RØDE NT-USB+ Studio Condenser USB Microphone',
    image: "/src/assets/Laptop1.png",
    price: 199.00,
    specs: {
      "Brand": "RØDE",
      "Type": "Condenser",
      "Patterns": "Cardioid",
      "Connectivity": "USB",
      "Sample Rate": "48 kHz",
      "Bit Depth": "24-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "132 dB",
      "Polar Patterns": 1,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "1.54 lbs",
      "Dimensions": "7.87 x 2.56 x 2.56 inches"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'microphone-6',
    name: 'Elgato Wave:3 USB Condenser Microphone',
    image: "/src/assets/Laptop1.png",
    price: 159.99,
    specs: {
      "Brand": "Elgato",
      "Type": "Condenser",
      "Patterns": "Cardioid",
      "Connectivity": "USB",
      "Sample Rate": "96 kHz",
      "Bit Depth": "24-bit",
      "Frequency Response": "70Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "120 dB",
      "Polar Patterns": 1,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "1.1 lbs",
      "Dimensions": "6.1 x 2.0 x 2.0 inches",
      "Clipguard Technology": "Yes"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'microphone-7',
    name: 'Amazon Basics Desktop Mini Condenser Microphone',
    image: "/src/assets/Laptop1.png",
    price: 29.99,
    specs: {
      "Brand": "Amazon Basics",
      "Type": "Condenser",
      "Patterns": "Cardioid",
      "Connectivity": "USB",
      "Sample Rate": "44.1/48 kHz",
      "Bit Depth": "16-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "110 dB",
      "Polar Patterns": 1,
      "Headphone Output": "No",
      "Gain Control": "No",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "0.5 lbs",
      "Dimensions": "3.9 x 2.4 x 2.4 inches"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'microphone-8',
    name: 'Blue Yeti Nano USB Microphone',
    image: "/src/assets/Laptop1.png",
    price: 99.99,
    specs: {
      "Brand": "Logitech for Creators",
      "Type": "Condenser",
      "Patterns": "Cardioid, Omnidirectional",
      "Connectivity": "USB",
      "Sample Rate": "48 kHz",
      "Bit Depth": "16-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "120 dB",
      "Polar Patterns": 2,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "1.0 lbs",
      "Dimensions": "4.3 x 4.3 x 7.9 inches"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'microphone-9',
    name: 'Audio-Technica AT2005USB Dynamic Microphone',
    image: "/src/assets/Laptop1.png",
    price: 79.00,
    specs: {
      "Brand": "Audio-Technica",
      "Type": "Dynamic",
      "Patterns": "Cardioid",
      "Connectivity": "USB, XLR",
      "Sample Rate": "44.1/48 kHz",
      "Bit Depth": "16-bit",
      "Frequency Response": "50Hz - 15kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "140 dB",
      "Polar Patterns": 1,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "No",
      "Mount Included": "No",
      "Weight": "0.9 lbs",
      "Dimensions": "6.38 x 2.05 x 2.05 inches"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'microphone-10',
    name: 'RØDE VideoMic NTG Shotgun USB Microphone',
    image: "/src/assets/Laptop1.png",
    price: 249.00,
    specs: {
      "Brand": "RØDE",
      "Type": "Shotgun Condenser",
      "Patterns": "Supercardioid",
      "Connectivity": "USB, 3.5mm",
      "Sample Rate": "48 kHz",
      "Bit Depth": "24-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "132 dB",
      "Polar Patterns": 1,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "2.2 lbs",
      "Dimensions": "8.3 x 2.0 x 2.0 inches"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'microphone-11',
    name: 'HyperX SoloCast USB Condenser Microphone',
    image: "/src/assets/Laptop1.png",
    price: 59.99,
    specs: {
      "Brand": "HyperX",
      "Type": "Condenser",
      "Patterns": "Cardioid",
      "Connectivity": "USB",
      "Sample Rate": "48 kHz",
      "Bit Depth": "16-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "120 dB",
      "Polar Patterns": 1,
      "Headphone Output": "No",
      "Gain Control": "No",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "0.7 lbs",
      "Dimensions": "4.3 x 4.3 x 10.0 inches"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'microphone-12',
    name: 'Elgato Wave DX Dynamic XLR Microphone',
    image: "/src/assets/Laptop1.png",
    price: 129.99,
    specs: {
      "Brand": "Elgato",
      "Type": "Dynamic",
      "Patterns": "Cardioid",
      "Connectivity": "XLR",
      "Sample Rate": "N/A",
      "Bit Depth": "N/A",
      "Frequency Response": "50Hz - 15kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "140 dB",
      "Polar Patterns": 1,
      "Headphone Output": "No",
      "Gain Control": "No",
      "Mute Button": "No",
      "Mount Included": "No",
      "Weight": "1.3 lbs",
      "Dimensions": "6.5 x 2.0 x 2.0 inches"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'microphone-13',
    name: 'Razer Seiren Emote USB Streaming Microphone',
    image: "/src/assets/Laptop1.png",
    price: 199.99,
    specs: {
      "Brand": "Razer",
      "Type": "Condenser",
      "Patterns": "Cardioid",
      "Connectivity": "USB",
      "Sample Rate": "48 kHz",
      "Bit Depth": "24-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "120 dB",
      "Polar Patterns": 1,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "2.0 lbs",
      "Dimensions": "6.5 x 6.5 x 12.0 inches",
      "Emote Display": "Yes"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'microphone-14',
    name: 'Audio-Technica AT2040 Hypercardioid Dynamic Microphone',
    image: "/src/assets/Laptop1.png",
    price: 199.00,
    specs: {
      "Brand": "Audio-Technica",
      "Type": "Dynamic",
      "Patterns": "Hypercardioid",
      "Connectivity": "XLR",
      "Sample Rate": "N/A",
      "Bit Depth": "N/A",
      "Frequency Response": "80Hz - 16kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "140 dB",
      "Polar Patterns": 1,
      "Headphone Output": "No",
      "Gain Control": "No",
      "Mute Button": "No",
      "Mount Included": "No",
      "Weight": "1.1 lbs",
      "Dimensions": "6.38 x 2.05 x 2.05 inches"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'microphone-15',
    name: 'RØDE PodMic Dynamic Broadcast Microphone',
    image: "/src/assets/Laptop1.png",
    price: 99.00,
    specs: {
      "Brand": "RØDE",
      "Type": "Dynamic",
      "Patterns": "Cardioid",
      "Connectivity": "XLR",
      "Sample Rate": "N/A",
      "Bit Depth": "N/A",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "Not specified",
      "Polar Patterns": 1,
      "Headphone Output": "No",
      "Gain Control": "No",
      "Mute Button": "No",
      "Mount Included": "No",
      "Weight": "2.2 lbs",
      "Dimensions": "6.1 x 3.5 x 3.5 inches"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'microphone-16',
    name: 'Blue Snowball Ice USB Microphone',
    image: "/src/assets/Laptop1.png",
    price: 49.99,
    specs: {
      "Brand": "Logitech for Creators",
      "Type": "Condenser",
      "Patterns": "Cardioid",
      "Connectivity": "USB",
      "Sample Rate": "44.1/48 kHz",
      "Bit Depth": "16-bit",
      "Frequency Response": "40Hz - 18kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "110 dB",
      "Polar Patterns": 1,
      "Headphone Output": "No",
      "Gain Control": "No",
      "Mute Button": "No",
      "Mount Included": "Yes",
      "Weight": "0.8 lbs",
      "Dimensions": "4.72 x 4.72 x 7.87 inches"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'microphone-17',
    name: 'HyperX DuoCast USB Condenser Microphone',
    image: "/src/assets/Laptop1.png",
    price: 129.99,
    specs: {
      "Brand": "HyperX",
      "Type": "Condenser",
      "Patterns": "Cardioid, Stereo",
      "Connectivity": "USB",
      "Sample Rate": "48 kHz",
      "Bit Depth": "24-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "120 dB",
      "Polar Patterns": 2,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "1.5 lbs",
      "Dimensions": "5.7 x 5.7 x 10.0 inches"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'microphone-18',
    name: 'Elgato Wave:1 USB Condenser Microphone',
    image: "/src/assets/Laptop1.png",
    price: 129.99,
    specs: {
      "Brand": "Elgato",
      "Type": "Condenser",
      "Patterns": "Cardioid",
      "Connectivity": "USB",
      "Sample Rate": "96 kHz",
      "Bit Depth": "24-bit",
      "Frequency Response": "70Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "120 dB",
      "Polar Patterns": 1,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "1.0 lbs",
      "Dimensions": "6.1 x 2.0 x 2.0 inches"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'microphone-19',
    name: 'Razer Seiren Mini USB Condenser Microphone',
    image: "/src/assets/Laptop1.png",
    price: 49.99,
    specs: {
      "Brand": "Razer",
      "Type": "Condenser",
      "Patterns": "Cardioid",
      "Connectivity": "USB",
      "Sample Rate": "48 kHz",
      "Bit Depth": "16-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "110 dB",
      "Polar Patterns": 1,
      "Headphone Output": "No",
      "Gain Control": "No",
      "Mute Button": "No",
      "Mount Included": "Yes",
      "Weight": "0.6 lbs",
      "Dimensions": "3.9 x 3.9 x 9.8 inches"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'microphone-20',
    name: 'Audio-Technica AT2020USB-XP USB Microphone',
    image: "/src/assets/Laptop1.png",
    price: 179.00,
    specs: {
      "Brand": "Audio-Technica",
      "Type": "Condenser",
      "Patterns": "Cardioid",
      "Connectivity": "USB",
      "Sample Rate": "96 kHz",
      "Bit Depth": "24-bit",
      "Frequency Response": "20Hz - 20kHz",
      "Sensitivity": "Not specified",
      "Max SPL": "144 dB",
      "Polar Patterns": 1,
      "Headphone Output": "Yes",
      "Gain Control": "Yes",
      "Mute Button": "Yes",
      "Mount Included": "Yes",
      "Weight": "1.2 lbs",
      "Dimensions": "6.38 x 2.05 x 2.05 inches"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  }
];