//src/components/PCBuilder/Modal/MockData/Motherboard/Motherboard.js
export const motherboardData = [
  {
    id: "mb-1",
    name: "ASRock B450 Pro4 R2.0 ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 5700.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B450",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "ASRock",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-2",
    name: "ASRock B550 Phantom Gaming 4 ac ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 7400.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "ASRock",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-3",
    name: "Asus PRIME B550-PLUS AC-HES ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 8500.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-4",
    name: "Asus ROG STRIX B450-F GAMING ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 6800.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B450",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 0
  },
  {
    id: "mb-5",
    name: "Asus ROG STRIX B550-A GAMING ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 10200.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "WHITE",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-6",
    name: "Asus ROG STRIX B550-F GAMING ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 10800.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-7",
    name: "Asus TUF GAMING B550-PLUS WIFI II ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 9500.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-8",
    name: "Gigabyte B550 AORUS ELITE AX V2 ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 8900.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Gigabyte",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-9",
    name: "MSI B450 TOMAHAWK MAX ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 6500.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B450",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "MSI",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-10",
    name: "MSI B550-A PRO ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 7800.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "MSI",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-11",
    name: "ASRock A520M-HDV Micro ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 3800.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD A520",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "ASRock",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "No",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-12",
    name: "ASRock B550M Pro4 Micro ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 6200.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "ASRock",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-13",
    name: "Asus PRIME B550M-A WIFI II Micro ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 7200.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 0
  },
  {
    id: "mb-14",
    name: "Gigabyte B550M AORUS ELITE AX Micro ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 8200.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Gigabyte",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-15",
    name: "MSI B550M PRO-VDH WIFI Micro ATX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 6800.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "MSI",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-16",
    name: "ASRock B550 Phantom Gaming-ITX ax Mini ITX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 11500.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "Mini ITX",
      "RAM Type": "DDR4",
      Manufacturer: "ASRock",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-17",
    name: "Asus ROG STRIX B550-I GAMING Mini ITX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 12500.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "Mini ITX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-18",
    name: "Gigabyte X570SI AORUS PRO AX Mini ITX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 11800.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD X570",
      "Form Factor": "Mini ITX",
      "RAM Type": "DDR4",
      Manufacturer: "Gigabyte",
      Color: "BLACK",
      "ECC Support": "Yes (Un-buffered)",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-19",
    name: "MSI MPG B550I GAMING EDGE WIFI Mini ITX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 11200.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD B550",
      "Form Factor": "Mini ITX",
      "RAM Type": "DDR4",
      Manufacturer: "MSI",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-20",
    name: "ASRock X570 Phantom Gaming-ITX TB3 Mini ITX AM4",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 14500.0,
    specs: {
      Socket: "AM4",
      Chipset: "AMD X570",
      "Form Factor": "Mini ITX",
      "RAM Type": "DDR4",
      Manufacturer: "ASRock",
      Color: "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  // AM5 Motherboards
  {
    id: "mb-21",
    name: "Asus ROG STRIX B850-F GAMING WIFI ATX AM5",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 14500.0,
    specs: {
      Socket: "AM5",
      Chipset: "AMD B850E",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-22",
    name: "Asus PRIME B650-PLUS WIFI ATX AM5",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 11200.0,
    specs: {
      Socket: "AM5",
      Chipset: "AMD B650",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 0
  },
  {
    id: "mb-23",
    name: "Gigabyte B650 EAGLE AX ATX AM5",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 9800.0,
    specs: {
      Socket: "AM5",
      Chipset: "AMD B650",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      Manufacturer: "Gigabyte",
      Color: "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-24",
    name: "MSI PRO B650-S WIFI ATX AM5",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 10500.0,
    specs: {
      Socket: "AM5",
      Chipset: "AMD B650",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      Manufacturer: "MSI",
      Color: "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-25",
    name: "Asus TUF GAMING B650-E WIFI ATX AM5",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 13200.0,
    specs: {
      Socket: "AM5",
      Chipset: "AMD B650E",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },

  // LGA 1151 Motherboards
  {
    id: "mb-26",
    name: "Asus PRIME Z270-A ATX LGA1151",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 6800.0,
    specs: {
      Socket: "LGA1151",
      Chipset: "Intel Z270",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-27",
    name: "Gigabyte Z290 AORUS PRO WIFI ATX LGA1151",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 8900.0,
    specs: {
      Socket: "LGA1151",
      Chipset: "Intel Z290",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Gigabyte",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-28",
    name: "MSI Z270-A PRO ATX LGA1151",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 6200.0,
    specs: {
      Socket: "LGA1151",
      Chipset: "Intel Z270",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "MSI",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-29",
    name: "Asus PRIME Z290-P ATX LGA1151",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 7500.0,
    specs: {
      Socket: "LGA1151",
      Chipset: "Intel Z290",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-30",
    name: "Gigabyte Z290 UD ATX LGA1151",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 7100.0,
    specs: {
      Socket: "LGA1151",
      Chipset: "Intel Z290",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Gigabyte",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },

  // LGA 1200 Motherboards
  {
    id: "mb-31",
    name: "Asus PRIME B560-PLUS ATX LGA1200",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 8200.0,
    specs: {
      Socket: "LGA1200",
      Chipset: "Intel B560",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 0
  },
  {
    id: "mb-32",
    name: "Asus ROG STRIX Z690-E GAMING WIFI ATX LGA1200",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 15800.0,
    specs: {
      Socket: "LGA1200",
      Chipset: "Intel Z690",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-33",
    name: "MSI Z490-A PRO ATX LGA1200",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 7800.0,
    specs: {
      Socket: "LGA1200",
      Chipset: "Intel Z490",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "MSI",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-34",
    name: "Asus TUF Gaming Z590-PLUS WIFI ATX LGA1200",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 11200.0,
    specs: {
      Socket: "LGA1200",
      Chipset: "Intel Z590",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-35",
    name: "Asus PRIME Z590-P ATX LGA1200",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 8500.0,
    specs: {
      Socket: "LGA1200",
      Chipset: "Intel Z590",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },

  // LGA 1700 Motherboards
  {
    id: "mb-36",
    name: "Asus PRIME B660-PLUS D4 ATX LGA1700",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 9200.0,
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel B660",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-37",
    name: "Gigabyte B760 GAMING X DDR4 ATX LGA1700",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 10500.0,
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel B760",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Gigabyte",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-38",
    name: "MSI B760 GAMING PLUS WIFI DDR4 ATX LGA1700",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 11800.0,
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel B760",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "MSI",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-39",
    name: "Asus TUF GAMING Z690-PLUS WIFI D4 ATX LGA1700",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 14200.0,
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel Z690",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-40",
    name: "MSI PRO B760-P WIFI DDR4 ATX LGA1700",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 9800.0,
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel B760",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      Manufacturer: "MSI",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 0
  },
  // AM5 Micro ATX Motherboards
  {
    id: "mb-41",
    name: "ASRock B650M Pro RS Micro ATX AM5",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 9800.0,
    specs: {
      Socket: "AM5",
      Chipset: "AMD B650",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR5",
      Manufacturer: "ASRock",
      Color: "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-42",
    name: "ASRock B650M Pro RS WiFi Micro ATX AM5",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 10500.0,
    specs: {
      Socket: "AM5",
      Chipset: "AMD B650",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR5",
      Manufacturer: "ASRock",
      Color: "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-43",
    name: "Gigabyte B650M GAMING PLUS WiFi Micro ATX AM5",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 11200.0,
    specs: {
      Socket: "AM5",
      Chipset: "AMD B650",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR5",
      Manufacturer: "Gigabyte",
      Color: "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-44",
    name: "MSI PRO B650M-A WiFi Micro ATX AM5",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 10800.0,
    specs: {
      Socket: "AM5",
      Chipset: "AMD B650",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR5",
      Manufacturer: "MSI",
      Color: "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-45",
    name: "Asus TUF GAMING B850M-PLUS WiFi Micro ATX AM5",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 12500.0,
    specs: {
      Socket: "AM5",
      Chipset: "AMD B850",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR5",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },

  // LGA 1151 Micro ATX Motherboards
  {
    id: "mb-46",
    name: "ASRock B250M-HDV Micro ATX LGA1151",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 4500.0,
    specs: {
      Socket: "LGA1151",
      Chipset: "Intel B250",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "ASRock",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "No",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "32 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-47",
    name: "Asus PRIME B360M-A Micro ATX LGA1151",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 5200.0,
    specs: {
      Socket: "LGA1151",
      Chipset: "Intel B360",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "No",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "32 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-48",
    name: "Gigabyte B365M DS3H Micro ATX LGA1151",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 4800.0,
    specs: {
      Socket: "LGA1151",
      Chipset: "Intel B365",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Gigabyte",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-49",
    name: "ASRock B365M Pro4 Micro ATX LGA1151",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 5500.0,
    specs: {
      Socket: "LGA1151",
      Chipset: "Intel B365",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "ASRock",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 0
  },
  {
    id: "mb-50",
    name: "Asus H110M-K Micro ATX LGA1151",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 3800.0,
    specs: {
      Socket: "LGA1151",
      Chipset: "Intel H110",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "No",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "32 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },

  // LGA 1200 Micro ATX Motherboards
  {
    id: "mb-51",
    name: "Asus PRIME B560M-A Micro ATX LGA1200",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 6800.0,
    specs: {
      Socket: "LGA1200",
      Chipset: "Intel B560",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-52",
    name: "Asus TUF GAMING B560M-PLUS WiFi Micro ATX LGA1200",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 8500.0,
    specs: {
      Socket: "LGA1200",
      Chipset: "Intel B560",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-53",
    name: "MSI B460M PRO-VDH WiFi Micro ATX LGA1200",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 6200.0,
    specs: {
      Socket: "LGA1200",
      Chipset: "Intel B460",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "MSI",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "No",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-54",
    name: "Gigabyte B560M D53H AC Micro ATX LGA1200",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 5900.0,
    specs: {
      Socket: "LGA1200",
      Chipset: "Intel B560",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Gigabyte",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-55",
    name: "Asus PRIME H510M-A Micro ATX LGA1200",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 5200.0,
    specs: {
      Socket: "LGA1200",
      Chipset: "Intel H510",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "No",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },

  // LGA 1700 Micro ATX Motherboards
  {
    id: "mb-56",
    name: "ASRock B660M Pro RS Micro ATX LGA1700",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 7800.0,
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel B660",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "ASRock",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-57",
    name: "Asus PRIME B760M-A AC Micro ATX LGA1700",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 9200.0,
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel B760",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: false,
    stockCount: 10
  },
  {
    id: "mb-58",
    name: "Gigabyte B760M GAMING PLUS WiFi DDR4 Micro ATX LGA1700",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 10500.0,
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel B760",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Gigabyte",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 0
  },
  {
    id: "mb-59",
    name: "MSI B760M GAMING PLUS WiFi Micro ATX LGA1700",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 9800.0,
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel B760",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "MSI",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
  {
    id: "mb-60",
    name: "Asus TUF GAMING B760M-PLUS WiFi II Micro ATX LGA1700",
    type: "motherboard",
    image: "/src/assets/Laptop1.png",
    price: 11500.0,
    specs: {
      Socket: "LGA1700",
      Chipset: "Intel B760",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      Manufacturer: "Asus",
      Color: "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0,
    },
    has3D: true,
    stockCount: 10
  },
];

