//client/src/components/PCBuilder/Modal/MockData/Webcam/Webcam.js
export const webcamData = [
  {
    id: 'webcam-1',
    name: 'Logitech Brio 4K Ultra HD Webcam',
    image: "/src/assets/Laptop1.png",
    price: 11433.43,
    specs: {
      "Brand": "Logitech",
      "Resolution": "4K Ultra HD (3840x2160)",
      "Field of View": "90° to 65° (adjustable)",
      "Features": "HDR, RightLight 3, Auto Focus",
      "Sensor": "4K Ultra HD sensor",
      "Frame Rate": "30fps at 4K, 60fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "RightLight 3 with HDR",
      "Microphone": "Dual omnidirectional mics with noise reduction",
      "Privacy Cover": "No",
      "Mounting": "Universal clip, tripod ready",
      "Connectivity": "USB-C to USB-A",
      "Compatibility": "Windows, macOS, Chrome OS",
      "Dimensions": "1.6 x 2.7 x 1.6 inches",
      "Weight": "0.33 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-2',
    name: 'Razer Kiyo Pro Ultra 4K Webcam',
    image: "/src/assets/Laptop1.png",
    price: 17152.13,
    specs: {
      "Brand": "Razer",
      "Resolution": "4K Ultra HD (3840x2160)",
      "Field of View": "90° to 103° (adjustable)",
      "Features": "Adaptive HDR, Adaptive Light Sensor",
      "Sensor": "Sony STARVIS 1/1.2-inch sensor",
      "Frame Rate": "30fps at 4K, 60fps at 1080p",
      "Autofocus": "Hybrid autofocus",
      "Auto Light Correction": "Adaptive Light Sensor",
      "Microphone": "Directional mic with noise reduction",
      "Privacy Cover": "Yes",
      "Mounting": "Universal clip, tripod ready",
      "Connectivity": "USB-C to USB-A",
      "Compatibility": "Windows, macOS",
      "Dimensions": "2.4 x 2.4 x 4.3 inches",
      "Weight": "0.5 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-3',
    name: 'Logitech C920x HD Pro Webcam',
    image: "/src/assets/Laptop1.png",
    price: 5717.17,
    specs: {
      "Brand": "Logitech",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "78°",
      "Features": "Autofocus, Light Correction",
      "Sensor": "Full HD glass lens",
      "Frame Rate": "30fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "Automatic light correction",
      "Microphone": "Dual stereo mics with noise reduction",
      "Privacy Cover": "No",
      "Mounting": "Universal clip",
      "Connectivity": "USB-A",
      "Compatibility": "Windows, macOS, Chrome OS",
      "Dimensions": "1.5 x 3.7 x 2.8 inches",
      "Weight": "0.31 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-4',
    name: 'Elgato Facecam Professional 1080p Webcam',
    image: "/src/assets/Laptop1.png",
    price: 10287.03,
    specs: {
      "Brand": "Elgato",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "82°",
      "Features": "Uncompressed video, fixed focus",
      "Sensor": "Sony STARVIS 8.5MP CMOS",
      "Frame Rate": "60fps at 1080p",
      "Autofocus": "No (fixed focus)",
      "Auto Light Correction": "No",
      "Microphone": "No",
      "Privacy Cover": "No",
      "Mounting": "Universal clip, tripod ready",
      "Connectivity": "USB-C to USB-A",
      "Compatibility": "Windows, macOS",
      "Dimensions": "1.6 x 2.5 x 2.5 inches",
      "Weight": "0.35 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-5',
    name: 'Microsoft LifeCam Studio 1080p HD Webcam',
    image: "/src/assets/Laptop1.png",
    price: 5141.47,
    specs: {
      "Brand": "Microsoft",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "75°",
      "Features": "TrueColor Technology, High-fidelity mic",
      "Sensor": "HD sensor",
      "Frame Rate": "30fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "TrueColor Technology",
      "Microphone": "High-fidelity mic",
      "Privacy Cover": "No",
      "Mounting": "Universal clip",
      "Connectivity": "USB-A",
      "Compatibility": "Windows",
      "Dimensions": "1.8 x 2.5 x 2.5 inches",
      "Weight": "0.28 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-6',
    name: 'Anker PowerConf C200 2K Webcam',
    image: "/src/assets/Laptop1.png",
    price: 4573.43,
    specs: {
      "Brand": "Anker",
      "Resolution": "2K QHD (2560x1440)",
      "Field of View": "95°",
      "Features": "Low-light correction, noise reduction",
      "Sensor": "2K CMOS sensor",
      "Frame Rate": "30fps at 2K, 60fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "Low-light correction",
      "Microphone": "Dual stereo mics with noise reduction",
      "Privacy Cover": "Built-in",
      "Mounting": "Universal clip, tripod ready",
      "Connectivity": "USB-C to USB-A",
      "Compatibility": "Windows, macOS",
      "Dimensions": "2.0 x 2.0 x 4.5 inches",
      "Weight": "0.4 lbs"
    },
    has3D: false,
    stockCount: 0
    },
  {
    id: 'webcam-7',
    name: 'NexiGo N60 1080p Webcam with Ring Light',
    image: "/src/assets/Laptop1.png",
    price: 2859.73,
    specs: {
      "Brand": "NexiGo",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "110°",
      "Features": "Built-in ring light, privacy cover",
      "Sensor": "1080p CMOS sensor",
      "Frame Rate": "30fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "Built-in ring light",
      "Microphone": "Built-in noise-canceling mic",
      "Privacy Cover": "Yes",
      "Mounting": "Universal clip",
      "Connectivity": "USB-A",
      "Compatibility": "Windows, macOS, Chrome OS",
      "Dimensions": "3.9 x 2.4 x 2.4 inches",
      "Weight": "0.45 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-8',
    name: 'Creative Live! Cam Sync 1080p V2 Webcam',
    image: "/src/assets/Laptop1.png",
    price: 2284.03,
    specs: {
      "Brand": "Creative",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "78°",
      "Features": "Autofocus, noise reduction",
      "Sensor": "1080p sensor",
      "Frame Rate": "30fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "Automatic light correction",
      "Microphone": "Built-in mic with noise reduction",
      "Privacy Cover": "No",
      "Mounting": "Universal clip",
      "Connectivity": "USB-A",
      "Compatibility": "Windows, macOS",
      "Dimensions": "1.4 x 2.6 x 2.6 inches",
      "Weight": "0.22 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-9',
    name: 'ASUS Webcam C3 1080p HD Webcam',
    image: "/src/assets/Laptop1.png",
    price: 3994.63,
    specs: {
      "Brand": "ASUS",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "78°",
      "Features": "Autofocus, HDR, AI noise cancellation",
      "Sensor": "Sony sensor",
      "Frame Rate": "30fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "HDR",
      "Microphone": "Dual mics with AI noise cancellation",
      "Privacy Cover": "Built-in",
      "Mounting": "Universal clip",
      "Connectivity": "USB-C to USB-A",
      "Compatibility": "Windows, macOS",
      "Dimensions": "1.6 x 2.4 x 2.4 inches",
      "Weight": "0.3 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-10',
    name: 'OBSBOT Tiny 2 4K AI Webcam',
    image: "/src/assets/Laptop1.png",
    price: 17152.13,
    specs: {
      "Brand": "OBSBOT",
      "Resolution": "4K Ultra HD (3840x2160)",
      "Field of View": "80° to 120° (adjustable)",
      "Features": "AI tracking, auto framing, gesture control",
      "Sensor": "1/1.5-inch Sony sensor",
      "Frame Rate": "30fps at 4K, 60fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "HDR",
      "Microphone": "Beamforming mics with noise reduction",
      "Privacy Cover": "No",
      "Mounting": "Universal clip, tripod ready",
      "Connectivity": "USB-C to USB-A",
      "Compatibility": "Windows, macOS",
      "Dimensions": "2.0 x 2.0 x 3.5 inches",
      "Weight": "0.38 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-11',
    name: 'Logitech StreamCam Premium 1080p Webcam',
    image: "/src/assets/Laptop1.png",
    price: 9712.87,
    specs: {
      "Brand": "Logitech",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "78°",
      "Features": "Vertical recording, smart auto focus",
      "Sensor": "1080p sensor",
      "Frame Rate": "60fps at 1080p",
      "Autofocus": "Smart auto focus",
      "Auto Light Correction": "Automatic",
      "Microphone": "Dual omnidirectional mics",
      "Privacy Cover": "No",
      "Mounting": "Universal clip (vertical/horizontal)",
      "Connectivity": "USB-C",
      "Compatibility": "Windows, macOS",
      "Dimensions": "1.7 x 2.4 x 2.4 inches",
      "Weight": "0.33 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-12',
    name: 'Razer Kiyo X 1080p Webcam',
    image: "/src/assets/Laptop1.png",
    price: 3430.13,
    specs: {
      "Brand": "Razer",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "90°",
      "Features": "Fixed focus, adjustable brightness",
      "Sensor": "1080p sensor",
      "Frame Rate": "30fps at 1080p",
      "Autofocus": "No (fixed focus)",
      "Auto Light Correction": "Adjustable brightness",
      "Microphone": "Directional mic",
      "Privacy Cover": "No",
      "Mounting": "Universal clip",
      "Connectivity": "USB-A",
      "Compatibility": "Windows, macOS",
      "Dimensions": "2.4 x 2.4 x 4.3 inches",
      "Weight": "0.4 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-13',
    name: 'AUKEY PC-LM1 1080p Webcam',
    image: "/src/assets/Laptop1.png",
    price: 1998.77,
    specs: {
      "Brand": "AUKEY",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "110°",
      "Features": "Plug and play, privacy cover",
      "Sensor": "1080p sensor",
      "Frame Rate": "30fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "Automatic",
      "Microphone": "Built-in noise reduction mic",
      "Privacy Cover": "Yes",
      "Mounting": "Universal clip",
      "Connectivity": "USB-A",
      "Compatibility": "Windows, macOS, Chrome OS",
      "Dimensions": "3.5 x 2.2 x 2.2 inches",
      "Weight": "0.3 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-14',
    name: 'Insta360 Link AI-Powered 4K Webcam',
    image: "/src/assets/Laptop1.png",
    price: 17152.13,
    specs: {
      "Brand": "Insta360",
      "Resolution": "4K Ultra HD (3840x2160)",
      "Field of View": "78° to 113° (adjustable)",
      "Features": "AI tracking, gesture control, zoom tracking",
      "Sensor": "1/2-inch 4K sensor",
      "Frame Rate": "30fps at 4K, 60fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "HDR",
      "Microphone": "Dual mics with noise reduction",
      "Privacy Cover": "No",
      "Mounting": "Magnetic base, tripod ready",
      "Connectivity": "USB-C to USB-A",
      "Compatibility": "Windows, macOS",
      "Dimensions": "2.0 x 2.0 x 3.9 inches",
      "Weight": "0.42 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-15',
    name: 'Wansview 1080p Webcam with Microphone',
    image: "/src/assets/Laptop1.png",
    price: 1714.97,
    specs: {
      "Brand": "Wansview",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "110°",
      "Features": "Plug and play, privacy cover",
      "Sensor": "1080p sensor",
      "Frame Rate": "30fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "Automatic",
      "Microphone": "Built-in noise reduction mic",
      "Privacy Cover": "Yes",
      "Mounting": "Universal clip",
      "Connectivity": "USB-A",
      "Compatibility": "Windows, macOS, Chrome OS",
      "Dimensions": "3.9 x 2.4 x 2.4 inches",
      "Weight": "0.35 lbs"
    },
    has3D: false,
    stockCount: 0
    },
  {
    id: 'webcam-16',
    name: 'Logitech for Creators Mevo Start Wireless Webcam',
    image: "/src/assets/Laptop1.png",
    price: 11433.43,
    specs: {
      "Brand": "Logitech for Creators",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "84°",
      "Features": "Wireless streaming, multi-camera support",
      "Sensor": "1080p sensor",
      "Frame Rate": "30fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "Automatic",
      "Microphone": "Built-in stereo mics",
      "Privacy Cover": "No",
      "Mounting": "Tripod mount",
      "Connectivity": "Wireless (WiFi), USB-C",
      "Compatibility": "iOS, Android, Windows, macOS",
      "Dimensions": "2.4 x 2.4 x 4.7 inches",
      "Weight": "0.5 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-17',
    name: 'AVerMedia PW513 1080p Webcam',
    image: "/src/assets/Laptop1.png",
    price: 5141.47,
    specs: {
      "Brand": "AVerMedia",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "90°",
      "Features": "Autofocus, low-light enhancement",
      "Sensor": "Sony STARVIS sensor",
      "Frame Rate": "30fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "Low-light enhancement",
      "Microphone": "Dual mics with noise reduction",
      "Privacy Cover": "No",
      "Mounting": "Universal clip",
      "Connectivity": "USB-A",
      "Compatibility": "Windows, macOS",
      "Dimensions": "2.0 x 2.0 x 4.3 inches",
      "Weight": "0.38 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-18',
    name: 'Green Extreme 4K Webcam with Ring Light',
    image: "/src/assets/Laptop1.png",
    price: 7420.93,
    specs: {
      "Brand": "Green Extreme",
      "Resolution": "4K Ultra HD (3840x2160)",
      "Field of View": "90°",
      "Features": "Built-in ring light, privacy cover",
      "Sensor": "4K sensor",
      "Frame Rate": "30fps at 4K",
      "Autofocus": "Yes",
      "Auto Light Correction": "Built-in ring light",
      "Microphone": "Dual noise-canceling mics",
      "Privacy Cover": "Yes",
      "Mounting": "Universal clip, tripod ready",
      "Connectivity": "USB-A",
      "Compatibility": "Windows, macOS, Chrome OS",
      "Dimensions": "4.7 x 4.7 x 4.7 inches",
      "Weight": "0.65 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-19',
    name: 'Adesso Cybertrack H4 1080p Webcam',
    image: "/src/assets/Laptop1.png",
    price: 2859.73,
    specs: {
      "Brand": "Adesso",
      "Resolution": "Full HD 1080p (1920x1080)",
      "Field of View": "120°",
      "Features": "Wide angle, plug and play",
      "Sensor": "1080p sensor",
      "Frame Rate": "30fps at 1080p",
      "Autofocus": "Yes",
      "Auto Light Correction": "Automatic",
      "Microphone": "Built-in mic",
      "Privacy Cover": "No",
      "Mounting": "Universal clip",
      "Connectivity": "USB-A",
      "Compatibility": "Windows, macOS, Chrome OS",
      "Dimensions": "3.1 x 2.4 x 2.4 inches",
      "Weight": "0.32 lbs"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'webcam-20',
    name: 'VDO360 4K Conference Webcam',
    image: "/src/assets/Laptop1.png",
    price: 14291.33,
    specs: {
      "Brand": "VDO360",
      "Resolution": "4K Ultra HD (3840x2160)",
      "Field of View": "120°",
      "Features": "Conference optimized, PTZ controls",
      "Sensor": "4K sensor",
      "Frame Rate": "30fps at 4K",
      "Autofocus": "Yes",
      "Auto Light Correction": "Automatic",
      "Microphone": "Beamforming array with noise cancellation",
      "Privacy Cover": "No",
      "Mounting": "Tripod mount, wall mount",
      "Connectivity": "USB-A, Ethernet optional",
      "Compatibility": "Windows, macOS",
      "Dimensions": "4.7 x 4.7 x 4.7 inches",
      "Weight": "1.1 lbs"
    },
    has3D: false,
    stockCount: 10
    }
];