//client/src/components/PCBuilder/Modal/MockData/GPU/GPU.js
export const gpuData = [
  {
    id: 'gpu-1',
    name: 'NVIDIA GeForce RTX 4090 24GB',
    image: "/src/assets/Laptop1.png",
    price: 1599.99,
    specs: {
      "Chipset": "GeForce RTX 4090",
      "Memory Type": "GDDR6X",
      "Memory Size": "24 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "NVIDIA",
      "Color": "BLACK",
      "TDP": "450 W",
      "Card Length": "304 mm",
      "Boost Clock": "2520 MHz",
      "Base Clock": "2235 MHz",
      "Memory Interface": "384-bit",
      "DisplayPort Outputs": 3,
      "HDMI Outputs": 1,
      "Power Connectors": "16-pin"
    },
    has3D: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'gpu-2',
    name: 'AMD Radeon RX 7900 XTX 24GB',
    image: "/src/assets/Laptop1.png",
    price: 999.99,
    specs: {
      "Chipset": "Radeon RX 7900 XTX",
      "Memory Type": "GDDR6",
      "Memory Size": "24 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "AMD",
      "Color": "BLACK",
      "TDP": "355 W",
      "Card Length": "287 mm",
      "Boost Clock": "2500 MHz",
      "Base Clock": "1900 MHz",
      "Memory Interface": "384-bit",
      "DisplayPort Outputs": 2,
      "HDMI Outputs": 2,
      "Power Connectors": "2 x 8-pin"
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'gpu-3',
    name: 'NVIDIA GeForce RTX 4080 SUPER 16GB',
    image: "/src/assets/Laptop1.png",
    price: 1199.99,
    specs: {
      "Chipset": "GeForce RTX 4080 SUPER",
      "Memory Type": "GDDR6X",
      "Memory Size": "16 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "NVIDIA",
      "Color": "BLACK",
      "TDP": "320 W",
      "Card Length": "310 mm",
      "Boost Clock": "2550 MHz",
      "Base Clock": "2295 MHz",
      "Memory Interface": "256-bit",
      "DisplayPort Outputs": 3,
      "HDMI Outputs": 1,
      "Power Connectors": "16-pin"
    },
    has3D: true,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'gpu-4',
    name: 'AMD Radeon RX 7800 XT 16GB',
    image: "/src/assets/Laptop1.png",
    price: 499.99,
    specs: {
      "Chipset": "Radeon RX 7800 XT",
      "Memory Type": "GDDR6",
      "Memory Size": "16 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "AMD",
      "Color": "BLACK",
      "TDP": "263 W",
      "Card Length": "267 mm",
      "Boost Clock": "2430 MHz",
      "Base Clock": "1800 MHz",
      "Memory Interface": "256-bit",
      "DisplayPort Outputs": 2,
      "HDMI Outputs": 2,
      "Power Connectors": "2 x 8-pin"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'gpu-5',
    name: 'NVIDIA GeForce RTX 4070 Ti SUPER 16GB',
    image: "/src/assets/Laptop1.png",
    price: 799.99,
    specs: {
      "Chipset": "GeForce RTX 4070 Ti SUPER",
      "Memory Type": "GDDR6X",
      "Memory Size": "16 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "NVIDIA",
      "Color": "WHITE",
      "TDP": "285 W",
      "Card Length": "305 mm",
      "Boost Clock": "2610 MHz",
      "Base Clock": "2340 MHz",
      "Memory Interface": "256-bit",
      "DisplayPort Outputs": 3,
      "HDMI Outputs": 1,
      "Power Connectors": "16-pin"
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'gpu-6',
    name: 'Intel Arc A770 16GB',
    image: "/src/assets/Laptop1.png",
    price: 329.99,
    specs: {
      "Chipset": "Arc A770",
      "Memory Type": "GDDR6",
      "Memory Size": "16 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "Intel",
      "Color": "BLUE",
      "TDP": "225 W",
      "Card Length": "270 mm",
      "Boost Clock": "2400 MHz",
      "Base Clock": "2100 MHz",
      "Memory Interface": "256-bit",
      "DisplayPort Outputs": 3,
      "HDMI Outputs": 1,
      "Power Connectors": "2 x 8-pin"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'gpu-7',
    name: 'NVIDIA GeForce RTX 4060 Ti 8GB',
    image: "/src/assets/Laptop1.png",
    price: 399.99,
    specs: {
      "Chipset": "GeForce RTX 4060 Ti",
      "Memory Type": "GDDR6",
      "Memory Size": "8 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "NVIDIA",
      "Color": "BLACK",
      "TDP": "160 W",
      "Card Length": "245 mm",
      "Boost Clock": "2535 MHz",
      "Base Clock": "2310 MHz",
      "Memory Interface": "128-bit",
      "DisplayPort Outputs": 3,
      "HDMI Outputs": 1,
      "Power Connectors": "1 x 8-pin"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'gpu-8',
    name: 'AMD Radeon RX 7600 8GB',
    image: "/src/assets/Laptop1.png",
    price: 269.99,
    specs: {
      "Chipset": "Radeon RX 7600",
      "Memory Type": "GDDR6",
      "Memory Size": "8 GB",
      "Interface": "PCIe 4.0 x8",
      "Manufacturer": "AMD",
      "Color": "BLACK",
      "TDP": "165 W",
      "Card Length": "204 mm",
      "Boost Clock": "2655 MHz",
      "Base Clock": "2250 MHz",
      "Memory Interface": "128-bit",
      "DisplayPort Outputs": 2,
      "HDMI Outputs": 2,
      "Power Connectors": "1 x 8-pin"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'gpu-9',
    name: 'NVIDIA GeForce RTX 3060 12GB',
    image: "/src/assets/Laptop1.png",
    price: 299.99,
    specs: {
      "Chipset": "GeForce RTX 3060",
      "Memory Type": "GDDR6",
      "Memory Size": "12 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "NVIDIA",
      "Color": "BLACK",
      "TDP": "170 W",
      "Card Length": "242 mm",
      "Boost Clock": "1777 MHz",
      "Base Clock": "1320 MHz",
      "Memory Interface": "192-bit",
      "DisplayPort Outputs": 3,
      "HDMI Outputs": 1,
      "Power Connectors": "1 x 8-pin"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'gpu-10',
    name: 'AMD Radeon RX 6700 XT 12GB',
    image: "/src/assets/Laptop1.png",
    price: 349.99,
    specs: {
      "Chipset": "Radeon RX 6700 XT",
      "Memory Type": "GDDR6",
      "Memory Size": "12 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "AMD",
      "Color": "RED",
      "TDP": "230 W",
      "Card Length": "267 mm",
      "Boost Clock": "2581 MHz",
      "Base Clock": "2321 MHz",
      "Memory Interface": "192-bit",
      "DisplayPort Outputs": 2,
      "HDMI Outputs": 2,
      "Power Connectors": "1 x 6-pin + 1 x 8-pin"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'gpu-11',
    name: 'NVIDIA GeForce RTX 3080 10GB',
    image: "/src/assets/Laptop1.png",
    price: 699.99,
    specs: {
      "Chipset": "GeForce RTX 3080",
      "Memory Type": "GDDR6X",
      "Memory Size": "10 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "NVIDIA",
      "Color": "BLACK",
      "TDP": "320 W",
      "Card Length": "285 mm",
      "Boost Clock": "1710 MHz",
      "Base Clock": "1440 MHz",
      "Memory Interface": "320-bit",
      "DisplayPort Outputs": 3,
      "HDMI Outputs": 1,
      "Power Connectors": "2 x 8-pin"
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'gpu-12',
    name: 'AMD Radeon RX 6600 XT 8GB',
    image: "/src/assets/Laptop1.png",
    price: 249.99,
    specs: {
      "Chipset": "Radeon RX 6600 XT",
      "Memory Type": "GDDR6",
      "Memory Size": "8 GB",
      "Interface": "PCIe 4.0 x8",
      "Manufacturer": "AMD",
      "Color": "BLACK",
      "TDP": "160 W",
      "Card Length": "200 mm",
      "Boost Clock": "2589 MHz",
      "Base Clock": "1968 MHz",
      "Memory Interface": "128-bit",
      "DisplayPort Outputs": 2,
      "HDMI Outputs": 2,
      "Power Connectors": "1 x 8-pin"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'gpu-13',
    name: 'NVIDIA GeForce GTX 1660 SUPER 6GB',
    image: "/src/assets/Laptop1.png",
    price: 199.99,
    specs: {
      "Chipset": "GeForce GTX 1660 SUPER",
      "Memory Type": "GDDR6",
      "Memory Size": "6 GB",
      "Interface": "PCIe 3.0 x16",
      "Manufacturer": "NVIDIA",
      "Color": "BLACK",
      "TDP": "125 W",
      "Card Length": "229 mm",
      "Boost Clock": "1785 MHz",
      "Base Clock": "1530 MHz",
      "Memory Interface": "192-bit",
      "DisplayPort Outputs": 3,
      "HDMI Outputs": 1,
      "Power Connectors": "1 x 8-pin"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'gpu-14',
    name: 'AMD Radeon RX 5700 XT 8GB',
    image: "/src/assets/Laptop1.png",
    price: 279.99,
    specs: {
      "Chipset": "Radeon RX 5700 XT",
      "Memory Type": "GDDR6",
      "Memory Size": "8 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "AMD",
      "Color": "BLACK",
      "TDP": "225 W",
      "Card Length": "272 mm",
      "Boost Clock": "1905 MHz",
      "Base Clock": "1605 MHz",
      "Memory Interface": "256-bit",
      "DisplayPort Outputs": 2,
      "HDMI Outputs": 2,
      "Power Connectors": "1 x 6-pin + 1 x 8-pin"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'gpu-15',
    name: 'NVIDIA GeForce RTX 3050 8GB',
    image: "/src/assets/Laptop1.png",
    price: 249.99,
    specs: {
      "Chipset": "GeForce RTX 3050",
      "Memory Type": "GDDR6",
      "Memory Size": "8 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "NVIDIA",
      "Color": "WHITE",
      "TDP": "130 W",
      "Card Length": "200 mm",
      "Boost Clock": "1777 MHz",
      "Base Clock": "1552 MHz",
      "Memory Interface": "128-bit",
      "DisplayPort Outputs": 3,
      "HDMI Outputs": 1,
      "Power Connectors": "1 x 8-pin"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'gpu-16',
    name: 'Intel Arc A750 8GB',
    image: "/src/assets/Laptop1.png",
    price: 229.99,
    specs: {
      "Chipset": "Arc A750",
      "Memory Type": "GDDR6",
      "Memory Size": "8 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "Intel",
      "Color": "BLACK",
      "TDP": "225 W",
      "Card Length": "268 mm",
      "Boost Clock": "2050 MHz",
      "Base Clock": "2050 MHz",
      "Memory Interface": "256-bit",
      "DisplayPort Outputs": 3,
      "HDMI Outputs": 1,
      "Power Connectors": "2 x 8-pin"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'gpu-17',
    name: 'NVIDIA GeForce RTX 3090 Ti 24GB',
    image: "/src/assets/Laptop1.png",
    price: 1299.99,
    specs: {
      "Chipset": "GeForce RTX 3090 Ti",
      "Memory Type": "GDDR6X",
      "Memory Size": "24 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "NVIDIA",
      "Color": "BLACK",
      "TDP": "450 W",
      "Card Length": "313 mm",
      "Boost Clock": "1860 MHz",
      "Base Clock": "1560 MHz",
      "Memory Interface": "384-bit",
      "DisplayPort Outputs": 3,
      "HDMI Outputs": 1,
      "Power Connectors": "16-pin"
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'gpu-18',
    name: 'AMD Radeon RX 6950 XT 16GB',
    image: "/src/assets/Laptop1.png",
    price: 649.99,
    specs: {
      "Chipset": "Radeon RX 6950 XT",
      "Memory Type": "GDDR6",
      "Memory Size": "16 GB",
      "Interface": "PCIe 4.0 x16",
      "Manufacturer": "AMD",
      "Color": "BLACK",
      "TDP": "335 W",
      "Card Length": "287 mm",
      "Boost Clock": "2310 MHz",
      "Base Clock": "1925 MHz",
      "Memory Interface": "256-bit",
      "DisplayPort Outputs": 2,
      "HDMI Outputs": 2,
      "Power Connectors": "2 x 8-pin + 1 x 6-pin"
    },
    has3D: true,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'gpu-19',
    name: 'NVIDIA GeForce GTX 1650 4GB',
    image: "/src/assets/Laptop1.png",
    price: 149.99,
    specs: {
      "Chipset": "GeForce GTX 1650",
      "Memory Type": "GDDR5",
      "Memory Size": "4 GB",
      "Interface": "PCIe 3.0 x16",
      "Manufacturer": "NVIDIA",
      "Color": "BLACK",
      "TDP": "75 W",
      "Card Length": "145 mm",
      "Boost Clock": "1665 MHz",
      "Base Clock": "1485 MHz",
      "Memory Interface": "128-bit",
      "DisplayPort Outputs": 1,
      "HDMI Outputs": 1,
      "Power Connectors": "None"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'gpu-20',
    name: 'AMD Radeon RX 6400 4GB',
    image: "/src/assets/Laptop1.png",
    price: 129.99,
    specs: {
      "Chipset": "Radeon RX 6400",
      "Memory Type": "GDDR6",
      "Memory Size": "4 GB",
      "Interface": "PCIe 4.0 x4",
      "Manufacturer": "AMD",
      "Color": "BLACK",
      "TDP": "53 W",
      "Card Length": "155 mm",
      "Boost Clock": "2321 MHz",
      "Base Clock": "1923 MHz",
      "Memory Interface": "64-bit",
      "DisplayPort Outputs": 1,
      "HDMI Outputs": 1,
      "Power Connectors": "None"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  }
];