//client/src/components/PCBuilder/Modal/MockData/Speaker/Speaker.js
export const speakerData = [
  {
    id: 'speaker-1',
    name: 'Logitech G560 LIGHTSYNC PC Gaming Speakers',
    image: "/src/assets/Laptop1.png",
    price: 11499.95, // 199.99 USD * 57.5 PHP
    specs: {
      "Brand": "Logitech",
      "Configuration": "2.1",
      "Power": "240W",
      "Connectivity": "USB, Bluetooth, 3.5mm",
      "Total RMS Power": "240W",
      "Satellite Power": "35W per satellite",
      "Subwoofer Power": "170W",
      "Frequency Response": "40Hz - 20kHz",
      "Drivers": "2.5\" woofers, 1\" tweeters",
      "RGB Lighting": "LIGHTSYNC RGB",
      "Inputs": "USB, 3.5mm, Bluetooth",
      "Controls": "Volume control, power button",
      "Dimensions (Satellites)": "7.5 x 4.8 x 4.7 inches",
      "Dimensions (Subwoofer)": "11.5 x 11.1 x 10.2 inches",
      "Weight": "12.1 lbs total",
      "Special Features": "Game-driven lighting, DTS:X Ultra surround"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'speaker-2',
    name: 'Audioengine A2+ Wireless Speakers',
    image: "/src/assets/Laptop1.png",
    price: 15467.50, // 269.00 USD * 57.5 PHP
    specs: {
      "Brand": "Audioengine",
      "Configuration": "2.0",
      "Power": "60W",
      "Connectivity": "USB, Bluetooth, 3.5mm, RCA",
      "Total RMS Power": "60W",
      "Satellite Power": "30W per speaker",
      "Subwoofer Power": "N/A",
      "Frequency Response": "65Hz - 22kHz",
      "Drivers": "2.75\" aramid fiber woofers, 0.75\" silk dome tweeters",
      "RGB Lighting": "No",
      "Inputs": "USB, 3.5mm, RCA, Bluetooth",
      "Controls": "Volume knob, power switch",
      "Dimensions (Per Speaker)": "6 x 4 x 5.25 inches",
      "Weight": "8 lbs total",
      "Special Features": "Built-in DAC, premium construction"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'speaker-3',
    name: 'Klipsch ProMedia 2.1 THX Certified Computer Speakers',
    image: "/src/assets/Laptop1.png",
    price: 8624.93, // 149.99 USD * 57.5 PHP
    specs: {
      "Brand": "Klipsch",
      "Configuration": "2.1",
      "Power": "200W",
      "Connectivity": "3.5mm",
      "Total RMS Power": "200W",
      "Satellite Power": "35W per satellite",
      "Subwoofer Power": "130W",
      "Frequency Response": "31Hz - 20kHz",
      "Drivers": "3\" micro-tractrix horn tweeters, 6.5\" subwoofer",
      "RGB Lighting": "No",
      "Inputs": "3.5mm, headphone jack",
      "Controls": "Volume control, headphone jack",
      "Dimensions (Satellites)": "7 x 4.2 x 4 inches",
      "Dimensions (Subwoofer)": "11.3 x 9.8 x 10 inches",
      "Weight": "15.4 lbs total",
      "Special Features": "THX certification, legendary sound quality"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'speaker-4',
    name: 'Razer Nommo Pro THX 2.1 Gaming Speakers',
    image: "/src/assets/Laptop1.png",
    price: 28749.43, // 499.99 USD * 57.5 PHP
    specs: {
      "Brand": "Razer",
      "Configuration": "2.1",
      "Power": "300W",
      "Connectivity": "USB, Bluetooth, 3.5mm, Optical",
      "Total RMS Power": "300W",
      "Satellite Power": "60W per satellite",
      "Subwoofer Power": "180W",
      "Frequency Response": "35Hz - 20kHz",
      "Drivers": "3\" custom woven glass fiber drivers, 5.25\" down-firing sub",
      "RGB Lighting": "Chroma RGB",
      "Inputs": "USB, 3.5mm, Optical, Bluetooth",
      "Controls": "Volume dial, bass control",
      "Dimensions (Satellites)": "7.8 x 5.9 x 7.1 inches",
      "Dimensions (Subwoofer)": "12.6 x 12.6 x 12.6 inches",
      "Weight": "22 lbs total",
      "Special Features": "THX certification, Dolby Virtual Surround"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'speaker-5',
    name: 'Edifier R1280T Powered Bookshelf Speakers',
    image: "/src/assets/Laptop1.png",
    price: 5749.43, // 99.99 USD * 57.5 PHP
    specs: {
      "Brand": "Edifier",
      "Configuration": "2.0",
      "Power": "42W",
      "Connectivity": "RCA, 3.5mm",
      "Total RMS Power": "42W",
      "Satellite Power": "21W per speaker",
      "Subwoofer Power": "N/A",
      "Frequency Response": "75Hz - 18kHz",
      "Drivers": "4\" bass drivers, 13mm silk dome tweeters",
      "RGB Lighting": "No",
      "Inputs": "RCA, 3.5mm",
      "Controls": "Volume, bass, treble controls",
      "Dimensions (Per Speaker)": "6.9 x 9.5 x 5.8 inches",
      "Weight": "10.8 lbs total",
      "Special Features": "Wooden enclosure, classic design"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'speaker-6',
    name: 'Bose Companion 2 Series III Multimedia Speakers',
    image: "/src/assets/Laptop1.png",
    price: 5692.50, // 99.00 USD * 57.5 PHP
    specs: {
      "Brand": "Bose",
      "Configuration": "2.0",
      "Power": "N/A",
      "Connectivity": "3.5mm",
      "Total RMS Power": "Not specified",
      "Satellite Power": "Not specified",
      "Subwoofer Power": "N/A",
      "Frequency Response": "Not specified",
      "Drivers": "Custom-designed drivers",
      "RGB Lighting": "No",
      "Inputs": "3.5mm, headphone jack",
      "Controls": "Volume control, headphone jack",
      "Dimensions (Per Speaker)": "7.5 x 3.1 x 5.9 inches",
      "Weight": "3.1 lbs total",
      "Special Features": "TrueSpace stereo digital processing"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'speaker-7',
    name: 'Creative Pebble Pro 2.0 USB-C Desktop Speakers',
    image: "/src/assets/Laptop1.png",
    price: 2874.43, // 49.99 USD * 57.5 PHP
    specs: {
      "Brand": "Creative",
      "Configuration": "2.0",
      "Power": "10W",
      "Connectivity": "USB-C, Bluetooth",
      "Total RMS Power": "10W",
      "Satellite Power": "5W per speaker",
      "Subwoofer Power": "N/A",
      "Frequency Response": "50Hz - 20kHz",
      "Drivers": "2.25\" full-range drivers",
      "RGB Lighting": "No",
      "Inputs": "USB-C, Bluetooth",
      "Controls": "Volume knob, Bluetooth button",
      "Dimensions (Per Speaker)": "4.7 x 4.8 x 4.7 inches",
      "Weight": "2.2 lbs total",
      "Special Features": "45° elevated drivers, Clear Dialog audio enhancement"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'speaker-8',
    name: 'Presonus Eris E3.5 BT Studio Monitors',
    image: "/src/assets/Laptop1.png",
    price: 8624.43, // 149.99 USD * 57.5 PHP
    specs: {
      "Brand": "Presonus",
      "Configuration": "2.0",
      "Power": "50W",
      "Connectivity": "RCA, TRS, Bluetooth",
      "Total RMS Power": "50W",
      "Satellite Power": "25W per monitor",
      "Subwoofer Power": "N/A",
      "Frequency Response": "80Hz - 20kHz",
      "Drivers": "3.5\" woven composite drivers, 1\" silk dome tweeters",
      "RGB Lighting": "No",
      "Inputs": "RCA, TRS, Bluetooth",
      "Controls": "Volume, low/high frequency tuning",
      "Dimensions (Per Monitor)": "7.3 x 6.3 x 9.1 inches",
      "Weight": "9.7 lbs total",
      "Special Features": "Acoustic tuning, professional studio monitors"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'speaker-9',
    name: 'JBL Professional 305P MkII Studio Monitors',
    image: "/src/assets/Laptop1.png",
    price: 17249.43, // 299.99 USD * 57.5 PHP
    specs: {
      "Brand": "JBL",
      "Configuration": "2.0",
      "Power": "164W",
      "Connectivity": "XLR, TRS",
      "Total RMS Power": "164W",
      "Satellite Power": "82W per monitor",
      "Subwoofer Power": "N/A",
      "Frequency Response": "49Hz - 20kHz",
      "Drivers": "5\" low-frequency transducer, 1\" soft dome tweeter",
      "RGB Lighting": "No",
      "Inputs": "XLR, TRS",
      "Controls": "Volume, high frequency trim",
      "Dimensions (Per Monitor)": "11.8 x 7.3 x 9.9 inches",
      "Weight": "20.5 lbs total",
      "Special Features": "Image Control Waveguide, professional studio reference"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'speaker-10',
    name: 'Corsair SP2500 2.1 High-Powered PC Speakers',
    image: "/src/assets/Laptop1.png",
    price: 14374.43, // 249.99 USD * 57.5 PHP
    specs: {
      "Brand": "Corsair",
      "Configuration": "2.1",
      "Power": "232W",
      "Connectivity": "3.5mm, RCA",
      "Total RMS Power": "232W",
      "Satellite Power": "36W per satellite",
      "Subwoofer Power": "160W",
      "Frequency Response": "30Hz - 20kHz",
      "Drivers": "2.5\" satellite drivers, 8\" subwoofer",
      "RGB Lighting": "No",
      "Inputs": "3.5mm, RCA",
      "Controls": "Wired control pod with volume/bass controls",
      "Dimensions (Satellites)": "6.7 x 4.1 x 4.7 inches",
      "Dimensions (Subwoofer)": "13.4 x 10.2 x 13.4 inches",
      "Weight": "24.7 lbs total",
      "Special Features": "High-power performance, dedicated control pod"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'speaker-11',
    name: 'Yamaha HS5 Powered Studio Monitor',
    image: "/src/assets/Laptop1.png",
    price: 11499.43, // 199.99 USD * 57.5 PHP
    specs: {
      "Brand": "Yamaha",
      "Configuration": "2.0",
      "Power": "70W",
      "Connectivity": "XLR, TRS",
      "Total RMS Power": "70W",
      "Satellite Power": "35W per monitor",
      "Subwoofer Power": "N/A",
      "Frequency Response": "54Hz - 30kHz",
      "Drivers": "5\" cone woofer, 1\" dome tweeter",
      "RGB Lighting": "No",
      "Inputs": "XLR, TRS",
      "Controls": "Level control, room control, high trim response",
      "Dimensions (Per Monitor)": "8.3 x 6.7 x 11.2 inches",
      "Weight": "19.8 lbs total",
      "Special Features": "Professional studio reference, white cone woofer"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'speaker-12',
    name: 'Kanto YU2 Powered Desktop Speakers',
    image: "/src/assets/Laptop1.png",
    price: 10349.43, // 179.99 USD * 57.5 PHP
    specs: {
      "Brand": "Kanto",
      "Configuration": "2.0",
      "Power": "50W",
      "Connectivity": "RCA, 3.5mm, Bluetooth",
      "Total RMS Power": "50W",
      "Satellite Power": "25W per speaker",
      "Subwoofer Power": "N/A",
      "Frequency Response": "80Hz - 20kHz",
      "Drivers": "3\" Kevlar drivers, 0.75\" silk dome tweeters",
      "RGB Lighting": "No",
      "Inputs": "RCA, 3.5mm, Bluetooth",
      "Controls": "Volume knob, input selection",
      "Dimensions (Per Speaker)": "5.9 x 4.1 x 5.7 inches",
      "Weight": "6.6 lbs total",
      "Special Features": "Multiple color options, built-in DAC"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'speaker-13',
    name: 'Harman Kardon SoundSticks 4 Wireless Speaker System',
    image: "/src/assets/Laptop1.png",
    price: 11497.13, // 199.95 USD * 57.5 PHP
    specs: {
      "Brand": "Harman Kardon",
      "Configuration": "2.1",
      "Power": "80W",
      "Connectivity": "Bluetooth, 3.5mm",
      "Total RMS Power": "80W",
      "Satellite Power": "20W per satellite",
      "Subwoofer Power": "40W",
      "Frequency Response": "40Hz - 20kHz",
      "Drivers": "1\" dome tweeters, 4.5\" subwoofer",
      "RGB Lighting": "No",
      "Inputs": "Bluetooth, 3.5mm",
      "Controls": "Touch-sensitive volume control",
      "Dimensions (Satellites)": "6.7 x 4.7 x 4.7 inches",
      "Dimensions (Subwoofer)": "9.1 x 6.7 x 6.7 inches",
      "Weight": "8.8 lbs total",
      "Special Features": "Iconic transparent design, touch controls"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'speaker-14',
    name: 'Sony SRS-RA5000 Wireless Speaker',
    image: "/src/assets/Laptop1.png",
    price: 40249.43, // 699.99 USD * 57.5 PHP
    specs: {
      "Brand": "Sony",
      "Configuration": "Single unit",
      "Power": "N/A",
      "Connectivity": "Bluetooth, Wi-Fi, Chromecast",
      "Total RMS Power": "Not specified",
      "Satellite Power": "N/A",
      "Subwoofer Power": "N/A",
      "Frequency Response": "Not specified",
      "Drivers": "Multiple speakers including up-firing drivers",
      "RGB Lighting": "No",
      "Inputs": "Bluetooth, Wi-Fi, Chromecast",
      "Controls": "Touch controls, app control",
      "Dimensions": "14.1 x 8.7 x 8.7 inches",
      "Weight": "13.9 lbs",
      "Special Features": "360 Reality Audio, immersive sound field"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'speaker-15',
    name: 'KRK Rokit 5 G4 Studio Monitor',
    image: "/src/assets/Laptop1.png",
    price: 10349.43, // 179.99 USD * 57.5 PHP
    specs: {
      "Brand": "KRK",
      "Configuration": "2.0",
      "Power": "105W",
      "Connectivity": "XLR, TRS, RCA",
      "Total RMS Power": "105W",
      "Satellite Power": "55W per monitor",
      "Subwoofer Power": "N/A",
      "Frequency Response": "43Hz - 40kHz",
      "Drivers": "5\" glass-aramid woofer, 1\" soft dome tweeter",
      "RGB Lighting": "No",
      "Inputs": "XLR, TRS, RCA",
      "Controls": "Volume, EQ adjustments",
      "Dimensions (Per Monitor)": "11.3 x 7.7 x 9.8 inches",
      "Weight": "18.7 lbs total",
      "Special Features": "DSP tuning, professional studio reference"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'speaker-16',
    name: 'Cyber Acoustics CA-3090 2.1 Speaker System',
    image: "/src/assets/Laptop1.png",
    price: 1724.43, // 29.99 USD * 57.5 PHP
    specs: {
      "Brand": "Cyber Acoustics",
      "Configuration": "2.1",
      "Power": "20W",
      "Connectivity": "3.5mm",
      "Total RMS Power": "20W",
      "Satellite Power": "5W per satellite",
      "Subwoofer Power": "10W",
      "Frequency Response": "40Hz - 20kHz",
      "Drivers": "2\" satellite drivers, 4\" subwoofer",
      "RGB Lighting": "No",
      "Inputs": "3.5mm",
      "Controls": "Volume control, power switch",
      "Dimensions (Satellites)": "4.5 x 3.5 x 4 inches",
      "Dimensions (Subwoofer)": "8.7 x 5.9 x 6.7 inches",
      "Weight": "4.4 lbs total",
      "Special Features": "Budget-friendly, easy setup"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'speaker-17',
    name: 'Mackie CR-X Series CR3-X 3" Creative Reference Multimedia Monitors',
    image: "/src/assets/Laptop1.png",
    price: 5749.43, // 99.99 USD * 57.5 PHP
    specs: {
      "Brand": "Mackie",
      "Configuration": "2.0",
      "Power": "50W",
      "Connectivity": "RCA, 3.5mm",
      "Total RMS Power": "50W",
      "Satellite Power": "25W per monitor",
      "Subwoofer Power": "N/A",
      "Frequency Response": "80Hz - 20kHz",
      "Drivers": "3\" polypropylene coated woofers, 0.75\" silk dome tweeters",
      "RGB Lighting": "No",
      "Inputs": "RCA, 3.5mm",
      "Controls": "Volume control, headphone output",
      "Dimensions (Per Monitor)": "6.3 x 5.7 x 8.5 inches",
      "Weight": "8.4 lbs total",
      "Special Features": "Multiple color options, front-facing volume control"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'speaker-18',
    name: 'Vanatoo Transparent Zero Powered Speakers',
    image: "/src/assets/Laptop1.png",
    price: 20642.50, // 359.00 USD * 57.5 PHP
    specs: {
      "Brand": "Vanatoo",
      "Configuration": "2.0",
      "Power": "112W",
      "Connectivity": "USB, Optical, 3.5mm, Bluetooth",
      "Total RMS Power": "112W",
      "Satellite Power": "56W per speaker",
      "Subwoofer Power": "N/A",
      "Frequency Response": "56Hz - 20kHz",
      "Drivers": "4.5 aluminum woofers, 1 silk dome tweeters",
      "RGB Lighting": "No",
      "Inputs": "USB, Optical, 3.5mm, Bluetooth",
      "Controls": "Remote control, auto-on/off",
      "Dimensions (Per Speaker)": "9.1 x 5.7 x 7.1 inches",
      "Weight": "16.5 lbs total",
      "Special Features": "Built-in DAC, multiple digital inputs"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'speaker-19',
    name: 'Genius SW-G2.1 1250 2.1 Gaming Speakers',
    image: "/src/assets/Laptop1.png",
    price: 2299.43, // 39.99 USD * 57.5 PHP
    specs: {
      "Brand": "Genius",
      "Configuration": "2.1",
      "Power": "16W",
      "Connectivity": "3.5mm",
      "Total RMS Power": "16W",
      "Satellite Power": "4W per satellite",
      "Subwoofer Power": "8W",
      "Frequency Response": "50Hz - 20kHz",
      "Drivers": "2 satellite drivers, 4 subwoofer",
      "RGB Lighting": "Blue LED",
      "Inputs": "3.5mm",
      "Controls": "Volume control, bass control",
      "Dimensions (Satellites)": "4.3 x 3.5 x 4.7 inches",
      "Dimensions (Subwoofer)": "8.7 x 6.3 x 7.1 inches",
      "Weight": "4.2 lbs total",
      "Special Features": "Gaming-oriented design, affordable price"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'speaker-20',
    name: 'Fluance Ai41 Powered Bookshelf Speakers',
    image: "/src/assets/Laptop1.png",
    price: 14374.43, // 249.99 USD * 57.5 PHP
    specs: {
      "Brand": "Fluance",
      "Configuration": "2.0",
      "Power": "140W",
      "Connectivity": "RCA, Optical, Bluetooth",
      "Total RMS Power": "140W",
      "Satellite Power": "70W per speaker",
      "Subwoofer Power": "N/A",
      "Frequency Response": "50Hz - 20kHz",
      "Drivers": "5 woven glass fiber drivers, 1 silk dome tweeters",
      "RGB Lighting": "No",
      "Inputs": "RCA, Optical, Bluetooth",
      "Controls": "Remote control, input selection",
      "Dimensions (Per Speaker)": "10.2 x 7.1 x 8.7 inches",
      "Weight": "22 lbs total",
      "Special Features": "Wooden cabinet, premium audio quality"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  }
];