//client/src/components/PCBuilder/Modal/MockData/Headphones/Headphones.js
export const headphonesData = [
  {
    id: 'headphones-1',
    name: 'SteelSeries Arctis Pro Wireless Gaming Headset',
    image: "/src/assets/Laptop1.png",
    price: 329.99,
    specs: {
      "Brand": "SteelSeries",
      "Type": "Over-ear",
      "Connectivity": "Wireless",
      "Features": "DTS Headphone:X v2.0",
      "Driver Size": "40mm",
      "Frequency Response": "10-40,000 Hz",
      "Impedance": "32 ohms",
      "Sensitivity": "102 dB",
      "Battery Life": "20 hours",
      "Microphone": "Retractable ClearCast",
      "Microphone Frequency Response": "100-10,000 Hz",
      "Noise Cancellation": "None",
      "Weight": "374g",
      "Cable Length": "N/A",
      "Charging": "Dual-battery system",
      "Compatibility": "PC, PS4, PS5, Mobile"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'headphones-2',
    name: 'Sennheiser HD 660S2 Open-Back Headphones',
    image: "/src/assets/Laptop1.png",
    price: 599.95,
    specs: {
      "Brand": "Sennheiser",
      "Type": "Over-ear",
      "Connectivity": "Wired",
      "Features": "Audiophile-grade",
      "Driver Size": "42mm",
      "Frequency Response": "8-41,500 Hz",
      "Impedance": "300 ohms",
      "Sensitivity": "104 dB",
      "Battery Life": "N/A",
      "Microphone": "None",
      "Microphone Frequency Response": "N/A",
      "Noise Cancellation": "None",
      "Weight": "260g",
      "Cable Length": "3m",
      "Charging": "N/A",
      "Compatibility": "PC, Hi-Fi systems"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'headphones-3',
    name: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
    image: "/src/assets/Laptop1.png",
    price: 399.99,
    specs: {
      "Brand": "Sony",
      "Type": "Over-ear",
      "Connectivity": "Wireless",
      "Features": "Industry-leading noise cancellation",
      "Driver Size": "30mm",
      "Frequency Response": "4-40,000 Hz",
      "Impedance": "48 ohms",
      "Sensitivity": "104.5 dB",
      "Battery Life": "30 hours",
      "Microphone": "Built-in beamforming mics",
      "Microphone Frequency Response": "50-8,000 Hz",
      "Noise Cancellation": "Active Noise Cancellation",
      "Weight": "250g",
      "Cable Length": "1.2m",
      "Charging": "USB-C, Quick Charge",
      "Compatibility": "PC, Mobile, Bluetooth devices"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'headphones-4',
    name: 'Bose QuietComfort Ultra Wireless Headphones',
    image: "/src/assets/Laptop1.png",
    price: 429.99,
    specs: {
      "Brand": "Bose",
      "Type": "Over-ear",
      "Connectivity": "Wireless",
      "Features": "Immersive Audio",
      "Driver Size": "Custom",
      "Frequency Response": "Not specified",
      "Impedance": "Not specified",
      "Sensitivity": "Not specified",
      "Battery Life": "24 hours",
      "Microphone": "Beamforming array",
      "Microphone Frequency Response": "Not specified",
      "Noise Cancellation": "Active Noise Cancellation",
      "Weight": "253g",
      "Cable Length": "1.2m",
      "Charging": "USB-C",
      "Compatibility": "PC, Mobile, Bluetooth devices"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'headphones-5',
    name: 'Audio-Technica ATH-M50x Professional Monitor Headphones',
    image: "/src/assets/Laptop1.png",
    price: 169.00,
    specs: {
      "Brand": "Audio-Technica",
      "Type": "Over-ear",
      "Connectivity": "Wired",
      "Features": "Studio monitoring",
      "Driver Size": "45mm",
      "Frequency Response": "15-28,000 Hz",
      "Impedance": "38 ohms",
      "Sensitivity": "99 dB",
      "Battery Life": "N/A",
      "Microphone": "None",
      "Microphone Frequency Response": "N/A",
      "Noise Cancellation": "Passive isolation",
      "Weight": "285g",
      "Cable Length": "3 cables included (1.2-3m)",
      "Charging": "N/A",
      "Compatibility": "PC, Studio equipment"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'headphones-6',
    name: 'Razer BlackShark V2 Pro Wireless Gaming Headset',
    image: "/src/assets/Laptop1.png",
    price: 179.99,
    specs: {
      "Brand": "Razer",
      "Type": "Over-ear",
      "Connectivity": "Wireless",
      "Features": "THX Spatial Audio",
      "Driver Size": "50mm",
      "Frequency Response": "12-28,000 Hz",
      "Impedance": "32 ohms",
      "Sensitivity": "107 dB",
      "Battery Life": "24 hours",
      "Microphone": "HyperClear Supercardioid",
      "Microphone Frequency Response": "100-10,000 Hz",
      "Noise Cancellation": "Passive isolation",
      "Weight": "320g",
      "Cable Length": "1.8m",
      "Charging": "USB-C",
      "Compatibility": "PC, PS4, PS5, Mobile"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'headphones-7',
    name: 'Beyerdynamic DT 990 PRO Studio Headphones',
    image: "/src/assets/Laptop1.png",
    price: 179.00,
    specs: {
      "Brand": "Beyerdynamic",
      "Type": "Over-ear",
      "Connectivity": "Wired",
      "Features": "Open-back studio reference",
      "Driver Size": "45mm",
      "Frequency Response": "5-35,000 Hz",
      "Impedance": "250 ohms",
      "Sensitivity": "96 dB",
      "Battery Life": "N/A",
      "Microphone": "None",
      "Microphone Frequency Response": "N/A",
      "Noise Cancellation": "None",
      "Weight": "340g",
      "Cable Length": "3m",
      "Charging": "N/A",
      "Compatibility": "PC, Studio equipment"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'headphones-8',
    name: 'Apple AirPods Max Wireless Headphones',
    image: "/src/assets/Laptop1.png",
    price: 549.00,
    specs: {
      "Brand": "Apple",
      "Type": "Over-ear",
      "Connectivity": "Wireless",
      "Features": "Spatial Audio with Dynamic Tracking",
      "Driver Size": "Custom",
      "Frequency Response": "Not specified",
      "Impedance": "Not specified",
      "Sensitivity": "Not specified",
      "Battery Life": "20 hours",
      "Microphone": "Beamforming array",
      "Microphone Frequency Response": "Not specified",
      "Noise Cancellation": "Active Noise Cancellation",
      "Weight": "384g",
      "Cable Length": "1.2m",
      "Charging": "Lightning",
      "Compatibility": "Apple devices, Bluetooth"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'headphones-9',
    name: 'HyperX Cloud Alpha Wireless Gaming Headset',
    image: "/src/assets/Laptop1.png",
    price: 199.99,
    specs: {
      "Brand": "HyperX",
      "Type": "Over-ear",
      "Connectivity": "Wireless",
      "Features": "300-hour battery life",
      "Driver Size": "50mm",
      "Frequency Response": "13-27,000 Hz",
      "Impedance": "65 ohms",
      "Sensitivity": "98 dB",
      "Battery Life": "300 hours",
      "Microphone": "Detachable noise-canceling",
      "Microphone Frequency Response": "50-7,300 Hz",
      "Noise Cancellation": "Passive isolation",
      "Weight": "335g",
      "Cable Length": "N/A",
      "Charging": "USB-C",
      "Compatibility": "PC, PS4, PS5"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'headphones-10',
    name: 'Audeze LCD-2 Classic Planar Magnetic Headphones',
    image: "/src/assets/Laptop1.png",
    price: 799.00,
    specs: {
      "Brand": "Audeze",
      "Type": "Over-ear",
      "Connectivity": "Wired",
      "Features": "Planar magnetic drivers",
      "Driver Size": "106mm",
      "Frequency Response": "10-50,000 Hz",
      "Impedance": "70 ohms",
      "Sensitivity": "101 dB",
      "Battery Life": "N/A",
      "Microphone": "None",
      "Microphone Frequency Response": "N/A",
      "Noise Cancellation": "None",
      "Weight": "595g",
      "Cable Length": "2.4m",
      "Charging": "N/A",
      "Compatibility": "PC, Hi-Fi systems"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'headphones-11',
    name: 'Logitech G Pro X 2 Lightspeed Wireless Gaming Headset',
    image: "/src/assets/Laptop1.png",
    price: 249.99,
    specs: {
      "Brand": "Logitech",
      "Type": "Over-ear",
      "Connectivity": "Wireless",
      "Features": "DTS Headphone:X 2.0",
      "Driver Size": "50mm",
      "Frequency Response": "20-20,000 Hz",
      "Impedance": "35 ohms",
      "Sensitivity": "91 dB",
      "Battery Life": "50 hours",
      "Microphone": "Blue VO!CE compatible",
      "Microphone Frequency Response": "100-10,000 Hz",
      "Noise Cancellation": "Passive isolation",
      "Weight": "350g",
      "Cable Length": "1.8m",
      "Charging": "USB-C",
      "Compatibility": "PC, PS4, PS5, Mobile"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'headphones-12',
    name: 'Focal Utopia 2022 Open-Back Headphones',
    image: "/src/assets/Laptop1.png",
    price: 4999.00,
    specs: {
      "Brand": "Focal",
      "Type": "Over-ear",
      "Connectivity": "Wired",
      "Features": "Flagship audiophile",
      "Driver Size": "40mm",
      "Frequency Response": "5-50,000 Hz",
      "Impedance": "80 ohms",
      "Sensitivity": "104 dB",
      "Battery Life": "N/A",
      "Microphone": "None",
      "Microphone Frequency Response": "N/A",
      "Noise Cancellation": "None",
      "Weight": "490g",
      "Cable Length": "4m",
      "Charging": "N/A",
      "Compatibility": "Hi-Fi systems"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'headphones-13',
    name: 'Corsair HS80 MAX Wireless Gaming Headset',
    image: "/src/assets/Laptop1.png",
    price: 179.99,
    specs: {
      "Brand": "Corsair",
      "Type": "Over-ear",
      "Connectivity": "Wireless",
      "Features": "Dolby Audio",
      "Driver Size": "50mm",
      "Frequency Response": "20-40,000 Hz",
      "Impedance": "32 ohms",
      "Sensitivity": "116 dB",
      "Battery Life": "65 hours",
      "Microphone": "Broadcast-quality omnidirectional",
      "Microphone Frequency Response": "100-10,000 Hz",
      "Noise Cancellation": "None",
      "Weight": "372g",
      "Cable Length": "N/A",
      "Charging": "USB-C",
      "Compatibility": "PC, PS4, PS5, Mobile"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'headphones-14',
    name: 'Shure SRH1540 Professional Closed-Back Headphones',
    image: "/src/assets/Laptop1.png",
    price: 499.00,
    specs: {
      "Brand": "Shure",
      "Type": "Over-ear",
      "Connectivity": "Wired",
      "Features": "Professional monitoring",
      "Driver Size": "40mm",
      "Frequency Response": "5-25,000 Hz",
      "Impedance": "46 ohms",
      "Sensitivity": "99 dB",
      "Battery Life": "N/A",
      "Microphone": "None",
      "Microphone Frequency Response": "N/A",
      "Noise Cancellation": "Passive isolation",
      "Weight": "286g",
      "Cable Length": "3m",
      "Charging": "N/A",
      "Compatibility": "PC, Studio equipment"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'headphones-15',
    name: 'Turtle Beach Stealth Pro Wireless Gaming Headset',
    image: "/src/assets/Laptop1.png",
    price: 329.99,
    specs: {
      "Brand": "Turtle Beach",
      "Type": "Over-ear",
      "Connectivity": "Wireless",
      "Features": "Active Noise Cancellation",
      "Driver Size": "50mm",
      "Frequency Response": "20-20,000 Hz",
      "Impedance": "32 ohms",
      "Sensitivity": "108 dB",
      "Battery Life": "40 hours",
      "Microphone": "Flip-to-mute",
      "Microphone Frequency Response": "100-10,000 Hz",
      "Noise Cancellation": "Active Noise Cancellation",
      "Weight": "380g",
      "Cable Length": "1.8m",
      "Charging": "USB-C",
      "Compatibility": "PC, PS4, PS5, Xbox, Mobile"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'headphones-16',
    name: 'AKG K371 Closed-Back Studio Headphones',
    image: "/src/assets/Laptop1.png",
    price: 149.00,
    specs: {
      "Brand": "AKG",
      "Type": "Over-ear",
      "Connectivity": "Wired",
      "Features": "Studio reference",
      "Driver Size": "50mm",
      "Frequency Response": "5-40,000 Hz",
      "Impedance": "32 ohms",
      "Sensitivity": "114 dB",
      "Battery Life": "N/A",
      "Microphone": "None",
      "Microphone Frequency Response": "N/A",
      "Noise Cancellation": "Passive isolation",
      "Weight": "255g",
      "Cable Length": "3m",
      "Charging": "N/A",
      "Compatibility": "PC, Studio equipment"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'headphones-17',
    name: 'EPOS H6PRO Open Acoustic Gaming Headset',
    image: "/src/assets/Laptop1.png",
    price: 179.99,
    specs: {
      "Brand": "EPOS",
      "Type": "Over-ear",
      "Connectivity": "Wired",
      "Features": "Open-back design",
      "Driver Size": "42mm",
      "Frequency Response": "10-30,000 Hz",
      "Impedance": "20 ohms",
      "Sensitivity": "112 dB",
      "Battery Life": "N/A",
      "Microphone": "Noise-canceling flip-to-mute",
      "Microphone Frequency Response": "50-16,000 Hz",
      "Noise Cancellation": "Passive isolation",
      "Weight": "310g",
      "Cable Length": "2.4m",
      "Charging": "N/A",
      "Compatibility": "PC, PS4, PS5, Xbox"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'headphones-18',
    name: 'Philips Fidelio X3 Open-Back Headphones',
    image: "/src/assets/Laptop1.png",
    price: 299.99,
    specs: {
      "Brand": "Philips",
      "Type": "Over-ear",
      "Connectivity": "Wired",
      "Features": "Hi-Res Audio certified",
      "Driver Size": "50mm",
      "Frequency Response": "5-40,000 Hz",
      "Impedance": "30 ohms",
      "Sensitivity": "100 dB",
      "Battery Life": "N/A",
      "Microphone": "None",
      "Microphone Frequency Response": "N/A",
      "Noise Cancellation": "None",
      "Weight": "380g",
      "Cable Length": "3m",
      "Charging": "N/A",
      "Compatibility": "PC, Hi-Fi systems"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'headphones-19',
    name: 'JBL Quantum 910 Wireless Gaming Headset',
    image: "/src/assets/Laptop1.png",
    price: 229.99,
    specs: {
      "Brand": "JBL",
      "Type": "Over-ear",
      "Connectivity": "Wireless",
      "Features": "QuantumSPHERE 360",
      "Driver Size": "50mm",
      "Frequency Response": "20-40,000 Hz",
      "Impedance": "32 ohms",
      "Sensitivity": "103 dB",
      "Battery Life": "39 hours",
      "Microphone": "Detachable noise-canceling",
      "Microphone Frequency Response": "100-10,000 Hz",
      "Noise Cancellation": "Active Noise Cancellation",
      "Weight": "350g",
      "Cable Length": "1.5m",
      "Charging": "USB-C",
      "Compatibility": "PC, PS4, PS5, Xbox, Mobile"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'headphones-20',
    name: 'Drop + Sennheiser HD 8XX Headphones',
    image: "/src/assets/Laptop1.png",
    price: 1099.00,
    specs: {
      "Brand": "Sennheiser",
      "Type": "Over-ear",
      "Connectivity": "Wired",
      "Features": "Collaboration with Drop",
      "Driver Size": "56mm",
      "Frequency Response": "4-51,000 Hz",
      "Impedance": "300 ohms",
      "Sensitivity": "102 dB",
      "Battery Life": "N/A",
      "Microphone": "None",
      "Microphone Frequency Response": "N/A",
      "Noise Cancellation": "None",
      "Weight": "360g",
      "Cable Length": "3m",
      "Charging": "N/A",
      "Compatibility": "PC, Hi-Fi systems"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  }
];