//client/src/components/PCBuilder/Modal/MockData/Motherboard/Motherboard.js
export const motherboardData = [
  {
    id: 'mb-1',
    name: 'ASUS ROG Strix X670E-E Gaming WiFi',
    image: "/src/assets/Laptop1.png",
    price: 449.99,
    specs: {
      "Socket": "AM5",
      "Chipset": "AMD X670E",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "ASUS",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-2',
    name: 'Gigabyte B650 AORUS Elite AX',
    image: "/src/assets/Laptop1.png",
    price: 289.99,
    specs: {
      "Socket": "AM5",
      "Chipset": "AMD B650",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "Gigabyte",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mb-3',
    name: 'MSI MAG B550 TOMAHAWK',
    image: "/src/assets/Laptop1.png",
    price: 189.99,
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD B550",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "MSI",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mb-4',
    name: 'ASRock B660M Pro RS',
    image: "/src/assets/Laptop1.png",
    price: 149.99,
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel B660",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "ASRock",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-5',
    name: 'ASUS ROG Maximus Z790 Hero',
    image: "/src/assets/Laptop1.png",
    price: 629.99,
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel Z790",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "ASUS",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "192 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 2,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 1
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mb-6',
    name: 'Gigabyte Z690 AORUS Ultra',
    image: "/src/assets/Laptop1.png",
    price: 299.99,
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel Z690",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "Gigabyte",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mb-7',
    name: 'ASRock X570 Taichi',
    image: "/src/assets/Laptop1.png",
    price: 349.99,
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD X570",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "ASRock",
      "Color": "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 8,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-8',
    name: 'MSI MPG Z590 Gaming Carbon WiFi',
    image: "/src/assets/Laptop1.png",
    price: 279.99,
    specs: {
      "Socket": "LGA1200",
      "Chipset": "Intel Z590",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "MSI",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mb-9',
    name: 'ASUS ROG Strix B450-F Gaming II',
    image: "/src/assets/Laptop1.png",
    price: 129.99,
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD B450",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "ASUS",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mb-10',
    name: 'Gigabyte B760M DS3H AX',
    image: "/src/assets/Laptop1.png",
    price: 159.99,
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel B760",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "Gigabyte",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "96 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-11',
    name: 'ASRock Z790 PG Lightning',
    image: "/src/assets/Laptop1.png",
    price: 229.99,
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel Z790",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "ASRock",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "192 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mb-12',
    name: 'MSI B550M PRO-VDH WiFi',
    image: "/src/assets/Laptop1.png",
    price: 119.99,
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD B550",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "MSI",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mb-13',
    name: 'ASUS Prime H610M-A D4',
    image: "/src/assets/Laptop1.png",
    price: 109.99,
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel H610",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "ASUS",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "No",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-14',
    name: 'Gigabyte X570S AORUS Master',
    image: "/src/assets/Laptop1.png",
    price: 399.99,
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD X570",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "Gigabyte",
      "Color": "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 8,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 2,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mb-15',
    name: 'ASRock B450M-HDV R4.0',
    image: "/src/assets/Laptop1.png",
    price: 79.99,
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD B450",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "ASRock",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "No",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "32 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mb-16',
    name: 'MSI MEG Z690 ACE',
    image: "/src/assets/Laptop1.png",
    price: 549.99,
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel Z690",
      "Form Factor": "EATX",
      "RAM Type": "DDR5",
      "Manufacturer": "MSI",
      "Color": "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 8,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 3,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 1
    },
    has3D: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-17',
    name: 'ASUS TUF Gaming B550-PLUS WiFi II',
    image: "/src/assets/Laptop1.png",
    price: 179.99,
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD B550",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "ASUS",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mb-18',
    name: 'Gigabyte Z490 AORUS XTREME',
    image: "/src/assets/Laptop1.png",
    price: 699.99,
    specs: {
      "Socket": "LGA1200",
      "Chipset": "Intel Z490",
      "Form Factor": "EATX",
      "RAM Type": "DDR4",
      "Manufacturer": "Gigabyte",
      "Color": "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 3,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mb-19',
    name: 'ASRock X670E Steel Legend',
    image: "/src/assets/Laptop1.png",
    price: 329.99,
    specs: {
      "Socket": "AM5",
      "Chipset": "AMD X670E",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "ASRock",
      "Color": "WHITE",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 8,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-20',
    name: 'MSI MPG B760I Edge WiFi',
    image: "/src/assets/Laptop1.png",
    price: 219.99,
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel B760",
      "Form Factor": "Mini-ITX",
      "RAM Type": "DDR5",
      "Manufacturer": "MSI",
      "Color": "WHITE",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  }
];