//client/src/components/PCBuilder/Modal/MockData/Motherboard/Motherboard.js
export const motherboardData = [
  {
    id: 'mb-1',
    name: 'ASUS ROG Strix X670E-E Gaming WiFi',
    image: "/src/assets/Laptop1.png",
    price: 25650.00, // Converted from 449.99 USD to PHP
    specs: {
      "Socket": "AM5",
      "Chipset": "AMD X670E",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "ASUS",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3极: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-2',
    name: 'Gigabyte B650 AORUS Elite AX',
    image: "/src/assets/Laptop1.png",
    price: 16530.00, // Converted from 289.99 USD to PHP
    specs: {
      "Socket": "AM5",
      "Chipset": "AMD B650",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "Gigabyte",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "极",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mb-3',
    name: 'MSI MAG B550 TOMAHAWK',
    image: "/src/assets/Laptop1.png",
    price: 10830.00, // Converted from 189.99 USD to PHP
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD B550",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "MSI",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 极 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mb-4',
    name: 'ASRock B660M Pro RS',
    image: "/src/assets/Laptop1.png",
    price: 8550.00, // Converted from 149.99 USD to PHP
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel B660",
      "Form Factor": "Micro ATX",
      "RAM Type": "D极4",
      "Manufacturer": "ASRock",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-5',
    name: 'ASUS ROG Maximus Z790 Hero',
    image: "/src/assets/Laptop1.png",
    price: 35910.00, // Converted from 629.99 USD to PHP
    specs: {
      "Socket": "LGA1700",
      "C极set": "Intel Z790",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "ASUS",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "192 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 2,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 1
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mb-6',
    name: 'Gigabyte Z690 AORUS Ultra',
    image: "/src/assets/Laptop1.png",
    price: 17100.00, // Converted from 299.99 USD to PHP
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel Z690",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "Gigabyte",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Port极": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mb-7',
    name: 'ASRock X570 Taichi',
    image: "/src/assets/Laptop1.png",
    price: 19950.00, // Converted from 349.99 USD to PHP
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD X570",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "ASRock",
      "Color": "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 8,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-8',
    name: 'MSI MPG Z590 Gaming Carbon WiFi',
    image: "/src/assets/Laptop1.png",
    price: 15960.00, // Converted from 279.99 USD to PHP
    specs: {
      "Socket": "LGA1200",
      "Chipset": "Intel Z590",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "MSI",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory极ots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mb-9',
    name: 'ASUS ROG Strix B450-F Gaming II',
    image: "/src/assets/Laptop1.png",
    price: 7410.00, // Converted from 129.99 USD to PHP
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD B450",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "ASUS",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mb-10',
    name: 'Gigabyte B760M DS3H AX',
    image: "/src/assets/Laptop1.png",
    price: 9120.00, // Converted from 159.99 USD to PHP
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel B极0",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "Gigabyte",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "96 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-11',
    name: 'ASRock Z790 PG Lightning',
    image: "/src/assets/Laptop1.png",
    price: 13110.00, // Converted from 229.99 USD to PHP
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel Z790",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "ASRock",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "192 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mb-12',
    name: 'MSI B550M PRO-VDH WiFi',
    image: "/src/assets/Laptop1.png",
    price: 6840.00, // Converted from 119.99 USD to PHP
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD B550",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "MSI",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 极.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mb-13',
    name: 'ASUS Prime H610M-A D4',
    image: "/src/assets/Laptop1.png",
    price: 6270.00, // Converted from 109.99 USD to PHP
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel H610",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "ASUS",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "No",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "No",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-14',
    name: 'Gigabyte X570S AORUS Master',
    image: "/src/assets/Laptop1.png",
    price: 22800.00, // Converted from 399.99 USD to PHP
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD X570",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "Gigabyte",
      "Color": "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 8,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 2,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mb-15',
    name: 'ASRock B450M-HDV R4.0',
    image: "/src/assets/Laptop1.png",
    price: 4560.00, // Converted from 79.99 USD to PHP
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD B450",
      "Form Factor": "Micro ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "ASRock",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "No",
      "BIOS Flashback": "No",
      "Clear CMOS Button": "极",
      "Maximum Memory": "32 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 0,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mb-16',
    name: 'MSI MEG Z690 ACE',
    image: "/src/assets/Laptop1.png",
    price: 31350.00, // Converted from 549.99 USD to PHP
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel Z690",
      "Form Factor": "EATX",
      "RAM Type": "DDR5",
      "Manufacturer": "MSI",
      "Color": "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 8,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 3,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 1
    },
    has3D: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-17',
    name: 'ASUS TUF Gaming B550-PLUS WiFi II',
    image: "/极/assets/Laptop1.png",
    price: 10260.00, // Converted from 179.99 USD to PHP
    specs: {
      "Socket": "AM4",
      "Chipset": "AMD B550",
      "Form Factor": "ATX",
      "RAM Type": "DDR4",
      "Manufacturer": "ASUS",
      "Color": "BLACK",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mb-18',
    name: 'Gigabyte Z490 AORUS XTREME',
    image: "/src/assets/Laptop1.png",
    price: 39900.00, // Converted from 699.99 USD to PHP
    specs: {
      "Socket": "LGA1200",
      "Chipset": "Intel Z490",
      "Form Factor": "EATX",
      "RAM Type": "DDR4",
      "Manufacturer": "Gigabyte",
      "Color": "BLACK",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 6,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 3,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 极x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mb-19',
    name: 'ASRock X670E Steel Legend',
    image: "/src/assets/Laptop1.png",
    price: 18810.00, // Converted from 329.极9 USD to PHP
    specs: {
      "Socket": "AM5",
      "Chipset": "AMD X670E",
      "Form Factor": "ATX",
      "RAM Type": "DDR5",
      "Manufacturer": "ASRock",
      "Color": "WHITE",
      "ECC Support": "Yes",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "128 GB",
      "Memory Slots": 4,
      "SATA 6 Gb/s Ports": 8,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 1,
      "USB 2.0 Headers": 2,
      "USB 3.2 Gen 1 Headers": 2,
      "USB 3.2 Gen 2 Headers": 2,
      "USB 3.2 Gen 2x2 Headers": 1,
      "USB 4 Headers": 0
    },
    has3D: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mb-20',
    name: 'MSI MPG B760I Edge WiFi',
    image: "/src/assets/Laptop1.png",
    price: 12540.00, // Converted from 219.99 USD to PHP
    specs: {
      "Socket": "LGA1700",
      "Chipset": "Intel B760",
      "Form Factor": "Mini-ITX",
      "RAM Type": "DDR5",
      "Manufacturer": "MSI",
      "Color": "WHITE",
      "ECC Support": "No",
      "RAID Support": "Yes",
      "BIOS Flashback": "Yes",
      "Clear CMOS Button": "Yes",
      "Maximum Memory": "64 GB",
      "Memory Slots": 2,
      "SATA 6 Gb/s Ports": 4,
      "SATA 3 Gb/s Ports": 0,
      "U.2 Ports": 0,
      "USB 2.0 Headers": 1,
      "USB 3.2 Gen 1 Headers": 1,
      "USB 3.2 Gen 2 Headers": 1,
      "USB 3.2 Gen 2x2 Headers": 0,
      "USB 4 Headers": 0
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  }
];