// client/src/components/MockData/accessoriesProducts.js
import SampleImg from "../../assets/Laptop1.png";

export const accessoriesProducts = [
  {
    id: 25,
    name: "USB-C Cable",
    brand: "Anker",
    description: "High-speed USB-C charging cable",
    img: SampleImg,
    price: 1999,
    oldPrice: 2499,
    rating: 4.4,
    reviews: 89,
    category: "Accessories",
    series: "essential-series",
    subcategory: "cables",
  },
  {
    id: 26,
    name: "Wireless Earphones",
    brand: "Sony",
    description: "Noise cancelling wireless earphones",
    img: SampleImg,
    price: 8999,
    oldPrice: 9999,
    rating: 4.7,
    reviews: 156,
    category: "Accessories",
    series: "premium-series",
    subcategory: "earphones",
  },
  {
    id: 27,
    name: "Power Bank 20000mAh",
    brand: "Xiaomi",
    description: "High capacity portable power bank",
    img: SampleImg,
    price: 2999,
    oldPrice: 3499,
    rating: 4.5,
    reviews: 203,
    category: "Accessories",
    series: "travel-series",
    subcategory: "power-bank",
  },
  {
    id: 28,
    name: "HDMI to DisplayPort Adapter",
    brand: "Cable Matters",
    description: "High-quality video adapter",
    img: SampleImg,
    price: 1499,
    oldPrice: 1999,
    rating: 4.3,
    reviews: 78,
    category: "Accessories",
    series: "essential-series",
    subcategory: "adapters",
  },
  {
    id: 29,
    name: "Laptop Stand",
    brand: "Rain Design",
    description: "Aluminum laptop stand for better ergonomics",
    img: SampleImg,
    price: 3999,
    oldPrice: 4499,
    rating: 4.6,
    reviews: 112,
    category: "Accessories",
    series: "office-series",
    subcategory: "mounts-stands",
  },
  {
    id: 30,
    name: "Electronics Cleaning Kit",
    brand: "iKlear",
    description: "Professional cleaning kit for electronics",
    img: SampleImg,
    price: 2499,
    oldPrice: 2999,
    rating: 4.4,
    reviews: 67,
    category: "Accessories",
    series: "protection-series",
    subcategory: "cleaning-kits",
  },
];