// client/src/components/MockData/banners.js
export const banners = [
  {
    id: "dream-build",
    imageKey: "banner1",
    eyebrow: "Custom Builds",
    title: "Build Your Dream PC",
    description: "Custom computers built for gaming, creativity, and productivity",
    overlayOpacity: 0.45,
    contentAlign: "left",
    backgroundPosition: "center 35%",
  },
  {
    id: "gaming",
    imageKey: "banner2",
    eyebrow: "Gaming",
    title: "Ultimate Gaming Experience",
    description: "High-performance components for the serious gamer",
    overlayOpacity: 0.5,
    contentAlign: "center",
    backgroundPosition: "center center",
  },
  {
    id: "workstations",
    imageKey: "banner3",
    eyebrow: "Workstations",
    title: "Professional Workstations",
    description: "Powerful systems for content creation and professional work",
    overlayOpacity: 0.4,
    contentAlign: "right",
    backgroundPosition: "center 30%",
  },
  {
    id: "innovation",
    imageKey: "banner4",
    eyebrow: "Innovation",
    title: "Cutting-Edge Technology",
    description: "Stay ahead with the latest innovations in PC hardware",
    overlayOpacity: 0.5,
    contentAlign: "left",
    backgroundPosition: "center center",
  },
];
