// client/src/components/MockData/laptopProducts.js
import SampleImg from "../../assets/Laptop1.png";

export const laptopProducts = [
  // Gaming Laptops
  {
    id: 1,
    name: "Gaming Laptop Pro",
    brand: "ASUS ROG",
    description: "17-inch gaming laptop with RTX 4070",
    img: SampleImg,
    price: 95999,
    oldPrice: 99999,
    rating: 4.8,
    reviews: 156,
    category: "Gaming Laptops",
    series: "titan-series",
    subcategory: "high-refresh-displays",
    specs: {
      gpu: "rtx4070",
      processor: "intel-i9",
      screenSize: "17",
      ram: "32gb",
      storage: "1tb",
    },
  },
  {
    id: 2,
    name: "Budget Gaming Laptop",
    brand: "Acer",
    description: "Affordable gaming performance",
    img: SampleImg,
    price: 49999,
    oldPrice: 54999,
    rating: 4.3,
    reviews: 187,
    category: "Gaming Laptops",
    series: "katana-series",
    subcategory: "nvidia-rtx-gpus",
    specs: {
      gpu: "rtx4050",
      processor: "intel-i5",
      screenSize: "15",
      ram: "16gb",
      storage: "512gb",
    },
  },
  {
    id: 3,
    name: "RGB Gaming Laptop",
    brand: "Razer",
    description: "Sleek design with customizable lighting",
    img: SampleImg,
    price: 102999,
    oldPrice: 109999,
    rating: 4.7,
    reviews: 98,
    category: "Gaming Laptops",
    series: "raider-series",
    subcategory: "rgb-keyboard",
    specs: {
      gpu: "rtx4080",
      processor: "intel-i9",
      screenSize: "17",
      ram: "32gb",
      storage: "2tb",
    },
  },

  // Content Creation Laptops
  {
    id: 4,
    name: "Content Creator Laptop",
    brand: "MSI",
    description: "Color-accurate display for creative work",
    img: SampleImg,
    price: 85999,
    oldPrice: 89999,
    rating: 4.7,
    reviews: 64,
    category: "Content Creation Laptops",
    series: "creator-z-series",
    subcategory: "color-accurate-displays",
    specs: {
      gpu: "rtx4060",
      processor: "amd-ryzen9",
      screenSize: "16",
      ram: "32gb",
      storage: "1tb",
    },
  },
  {
    id: 5,
    name: "Creative Workstation",
    brand: "Dell",
    description: "Professional-grade creative workstation",
    img: SampleImg,
    price: 119999,
    oldPrice: 124999,
    rating: 4.9,
    reviews: 56,
    category: "Content Creation Laptops",
    series: "creatorpro-series",
    subcategory: "professional-gpus",
    specs: {
      gpu: "rtx5000",
      processor: "intel-xeon",
      screenSize: "17",
      ram: "64gb",
      storage: "2tb",
    },
  },
  {
    id: 6,
    name: "MacBook Pro",
    brand: "Apple",
    description: "Professional laptop for creatives",
    img: SampleImg,
    price: 112999,
    oldPrice: 119999,
    rating: 4.9,
    reviews: 245,
    category: "Content Creation Laptops",
    series: "prestige-series",
    subcategory: "color-calibration",
    specs: {
      gpu: "apple-silicon",
      processor: "apple-m2",
      screenSize: "16",
      ram: "32gb",
      storage: "1tb",
    },
  },

  // Business Laptops
  {
    id: 7,
    name: "Business Laptop",
    brand: "HP",
    description: "Security-focused for enterprise use",
    img: SampleImg,
    price: 58999,
    oldPrice: 62999,
    rating: 4.4,
    reviews: 76,
    category: "Business Laptops",
    series: "pro-series",
    subcategory: "security-features",
    specs: {
      gpu: "integrated",
      processor: "intel-i5",
      screenSize: "15",
      ram: "16gb",
      storage: "512gb",
    },
  },
  {
    id: 8,
    name: "Ultrabook Elite",
    brand: "Dell",
    description: "Thin and light for professionals on the go",
    img: SampleImg,
    price: 72999,
    oldPrice: 76999,
    rating: 4.5,
    reviews: 89,
    category: "Business Laptops",
    series: "modern-business-series",
    subcategory: "long-battery",
    specs: {
      gpu: "integrated",
      processor: "intel-i7",
      screenSize: "14",
      ram: "16gb",
      storage: "512gb",
    },
  },
  {
    id: 9,
    name: "Executive Laptop",
    brand: "Lenovo",
    description: "Premium business solution",
    img: SampleImg,
    price: 89999,
    oldPrice: 94999,
    rating: 4.6,
    reviews: 112,
    category: "Business Laptops",
    series: "prestige-business-line",
    subcategory: "vpro-technology",
    specs: {
      gpu: "integrated",
      processor: "intel-i7",
      screenSize: "14",
      ram: "16gb",
      storage: "1tb",
    },
  },

  // Thin & Light Laptops
  {
    id: 10,
    name: "Thin & Light Ultrabook",
    brand: "MSI",
    description: "Ultra-portable for professionals",
    img: SampleImg,
    price: 78999,
    oldPrice: 82999,
    rating: 4.6,
    reviews: 134,
    category: "Thin & Light Laptops",
    series: "prestige-slim-series",
    subcategory: "ultra-thin-design",
    specs: {
      gpu: "integrated",
      processor: "intel-i7",
      screenSize: "14",
      ram: "16gb",
      storage: "1tb",
    },
  },
  {
    id: 11,
    name: "Zen Ultrabook",
    brand: "ASUS",
    description: "Ultra-portable zen series",
    img: SampleImg,
    price: 69999,
    oldPrice: 74999,
    rating: 4.5,
    reviews: 98,
    category: "Thin & Light Laptops",
    series: "zen-series",
    subcategory: "lightweight-construction",
    specs: {
      gpu: "integrated",
      processor: "intel-i5",
      screenSize: "13",
      ram: "16gb",
      storage: "512gb",
    },
  },
  {
    id: 12,
    name: "Modern Thin Laptop",
    brand: "HP",
    description: "Modern thin design",
    img: SampleImg,
    price: 65999,
    oldPrice: 69999,
    rating: 4.4,
    reviews: 87,
    category: "Thin & Light Laptops",
    series: "modern-thin-series",
    subcategory: "all-day-battery",
    specs: {
      gpu: "integrated",
      processor: "intel-i5",
      screenSize: "14",
      ram: "8gb",
      storage: "512gb",
    },
  },

  // 2-in-1 Convertibles
  {
    id: 13,
    name: "2-in-1 Convertible",
    brand: "Lenovo",
    description: "Versatile laptop and tablet combination",
    img: SampleImg,
    price: 65999,
    oldPrice: 69999,
    rating: 4.6,
    reviews: 112,
    category: "2-in-1 Convertibles",
    series: "summit-e-series",
    subcategory: "touchscreen-display",
    specs: {
      gpu: "integrated",
      processor: "intel-i7",
      screenSize: "13",
      ram: "16gb",
      storage: "512gb",
    },
  },
  {
    id: 14,
    name: "Convertible Business",
    brand: "Dell",
    description: "Business convertible with pen support",
    img: SampleImg,
    price: 79999,
    oldPrice: 84999,
    rating: 4.5,
    reviews: 76,
    category: "2-in-1 Convertibles",
    series: "prestige-flip-series",
    subcategory: "pen-support",
    specs: {
      gpu: "integrated",
      processor: "intel-i5",
      screenSize: "13",
      ram: "16gb",
      storage: "512gb",
    },
  },
  {
    id: 15,
    name: "Modern Convertible",
    brand: "HP",
    description: "Modern convertible series",
    img: SampleImg,
    price: 72999,
    oldPrice: 77999,
    rating: 4.4,
    reviews: 93,
    category: "2-in-1 Convertibles",
    series: "modern-convertible-series",
    subcategory: "hinge-design",
    specs: {
      gpu: "integrated",
      processor: "intel-i5",
      screenSize: "14",
      ram: "8gb",
      storage: "512gb",
    },
  },
];