// client/src/components/MockData/otherProducts.js
import SampleImg from "../../assets/Laptop1.png";

export const otherProducts = [
  {
    id: 9,
    name: "MSI MAG Series Fan",
    brand: "MSI",
    description: "High-performance chassis fan with RGB lighting",
    price: 29.99,
    oldPrice: 39.99,
    rating: 4.5,
    reviews: 128,
    img: SampleImg,
    category: "Components",
    series: "cooling-series",
    subcategory: "chassis-fan",
  },
  {
    id: 10,
    name: "MSI Silent Fan",
    brand: "MSI",
    description: "Quiet operation chassis fan",
    price: 24.99,
    oldPrice: 0,
    rating: 4.3,
    reviews: 87,
    img: SampleImg,
    category: "Components",
    series: "cooling-series",
    subcategory: "chassis-fan",
  },
  {
    id: 11,
    name: "Mechanical Keyboard",
    brand: "Corsair",
    description: "RGB mechanical keyboard with Cherry MX switches",
    img: SampleImg,
    price: 6999,
    oldPrice: 7999,
    rating: 4.8,
    reviews: 342,
    category: "Peripherals",
    series: "peripherals-series",
    subcategory: "keyboard",
  },
  {
    id: 12,
    name: "Gaming Mouse",
    brand: "Logitech",
    description: "Wireless gaming mouse with Hero sensor",
    img: SampleImg,
    price: 5499,
    oldPrice: 5999,
    rating: 4.7,
    reviews: 287,
    category: "Peripherals",
    series: "peripherals-series",
    subcategory: "mouse",
  },
  {
    id: 13,
    name: "4K Monitor",
    brand: "Samsung",
    description: "32-inch 4K display with HDR support",
    img: SampleImg,
    price: 23999,
    oldPrice: 25999,
    rating: 4.6,
    reviews: 154,
    category: "Peripherals",
    series: "display-series",
    subcategory: "monitor",
  },
  {
    id: 14,
    name: "Gaming Headset",
    brand: "SteelSeries",
    description: "7.1 surround sound with noise cancellation",
    img: SampleImg,
    price: 6999,
    oldPrice: 7999,
    rating: 4.5,
    reviews: 213,
    category: "Peripherals",
    series: "peripherals-series",
    subcategory: "headset",
  },
  {
    id: 15,
    name: "Webcam",
    brand: "Logitech",
    description: "4K webcam with background replacement",
    img: SampleImg,
    price: 8999,
    oldPrice: 9999,
    rating: 4.4,
    reviews: 178,
    category: "Peripherals",
    series: "peripherals-series",
    subcategory: "web-digital-camera",
  },
  {
    id: 16,
    name: "SSD 1TB",
    brand: "Samsung",
    description: "NVMe SSD with read speeds up to 7000MB/s",
    img: SampleImg,
    price: 7999,
    oldPrice: 8999,
    rating: 4.9,
    reviews: 432,
    category: "Components",
    series: "storage-series",
    subcategory: "storage",
  },
  {
    id: 17,
    name: "Router",
    brand: "TP-Link",
    description: "Wi-Fi 6 gaming router with prioritization",
    img: SampleImg,
    price: 5999,
    oldPrice: 6999,
    rating: 4.3,
    reviews: 167,
    category: "Peripherals",
    series: "network-series",
    subcategory: "router",
  },
  {
    id: 18,
    name: "Mouse Pad",
    brand: "Razer",
    description: "Extended RGB gaming mouse pad",
    img: SampleImg,
    price: 2999,
    oldPrice: 3499,
    rating: 4.6,
    reviews: 198,
    category: "Peripherals",
    series: "peripherals-series",
    subcategory: "mouse-pad",
  },
  {
    id: 19,
    name: "Motherboard Z790",
    brand: "ASUS",
    description: "High-performance motherboard for gaming",
    img: SampleImg,
    price: 18999,
    oldPrice: 20999,
    rating: 4.7,
    reviews: 156,
    category: "Components",
    series: "motherboard-series",
    subcategory: "motherboard",
  },
  {
    id: 20,
    name: "Graphics Card RTX 4080",
    brand: "NVIDIA",
    description: "High-end graphics card for gaming",
    img: SampleImg,
    price: 65999,
    oldPrice: 72999,
    rating: 4.9,
    reviews: 287,
    category: "Components",
    series: "gpu-series",
    subcategory: "gpu",
  },
  {
    id: 21,
    name: "Processor i9-13900K",
    brand: "Intel",
    description: "High-performance processor for gaming",
    img: SampleImg,
    price: 32999,
    oldPrice: 35999,
    rating: 4.8,
    reviews: 198,
    category: "Components",
    series: "cpu-series",
    subcategory: "cpu-intel",
  },
  {
    id: 22,
    name: "RAM 32GB DDR5",
    brand: "Corsair",
    description: "High-speed DDR5 memory",
    img: SampleImg,
    price: 8999,
    oldPrice: 9999,
    rating: 4.6,
    reviews: 134,
    category: "Components",
    series: "memory-series",
    subcategory: "memory",
  },
  {
    id: 23,
    name: "Power Supply 1000W",
    brand: "Seasonic",
    description: "80+ Gold certified power supply",
    img: SampleImg,
    price: 12999,
    oldPrice: 14999,
    rating: 4.7,
    reviews: 112,
    category: "Components",
    series: "psu-series",
    subcategory: "psu",
  },
  {
    id: 24,
    name: "CPU Cooler AIO",
    brand: "NZXT",
    description: "All-in-one liquid CPU cooler",
    img: SampleImg,
    price: 7999,
    oldPrice: 8999,
    rating: 4.5,
    reviews: 167,
    category: "Components",
    series: "cooling-series",
    subcategory: "cooler",
  },
];