//client/src/components/PCBuilder/Modal/MockData/Monitor/Monitor.js
export const monitorData = [
  {
    id: 'monitor-1',
    name: 'Samsung Odyssey G7 32" QHD 240Hz Curved Gaming Monitor',
    image: "/src/assets/Laptop1.png",
    price: 34200.00, // Converted from 599.99 USD to PHP
    specs: {
      "Brand": "Samsung",
      "Refresh Rate": "240Hz",
      "Screen Size": "32",
      "Vertical Resolution": "1440",
      "Horizontal Resolution": "2560",
      "Panel Type": "VA",
      "Curvature": "1000R",
      "Response Time": "1ms",
      "Brightness": "600 nits",
      "Contrast Ratio": "2500:1",
      "HDR": "HDR600",
      "Adaptive Sync": "G-Sync Compatible, FreeSync Premium Pro",
      "Ports": "DisplayPort 1.4, HDMI 2.1, USB Hub",
      "Stand Adjustments": "Height, Tilt, Swivel",
      "VESA Mount": "100x100mm",
      "Weight": "7.7 kg"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'monitor-2',
    name: 'LG 27GP850极 27" Nano IPS QHD 180Hz Gaming Monitor',
    image: "/src/assets/Laptop1.png",
    price: 22800.00, // Converted from 399.99 USD to PHP
    specs: {
      "Brand": "LG",
      "Refresh Rate": "180Hz",
      "Screen Size": "27",
      "Vertical Resolution": "1440",
      "Horizontal Resolution": "2560",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "1ms",
      "Brightness": "350 nits",
      "Contrast Ratio": "1000:1",
      "HDR": "HDR10",
      "Adaptive Sync": "G-Sync Compatible, FreeSync Premium",
      "Ports": "DisplayPort 1.4, HDMI 2.0, USB Hub",
      "Stand Adjustments": "Height, Tilt, Pivot",
      "VESA Mount": "100x100mm",
      "Weight": "5.9 kg"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'monitor-3',
    name: 'Dell S2721DGF 27" QHD 165Hz IPS Gaming Monitor',
    image: "/src/assets/Laptop1.png",
    price: 19950.00, // Converted from 349.99 USD to PHP
    specs: {
      "Brand": "Dell",
      "Refresh Rate": "165Hz",
      "Screen Size": "27",
      "Vertical Resolution": "1440",
      "Horizontal Resolution": "2560",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "1ms",
      "Brightness": "400 nits",
      "Contrast Ratio": "1000:1",
      "HDR": "HDR400",
      "Adaptive Sync": "G-Sync Compatible, FreeSync Premium",
      "Ports": "DisplayPort 1.4, HDMI 2.0极 USB Hub",
      "Stand Adjustments": "Height, Tilt, Swivel, Pivot",
      "VESA Mount": "100x100mm",
      "Weight": "6.1 kg"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'monitor-4',
    name: 'ASUS ROG Swift PG32UQX 32" 4K 144Hz Mini-LED',
    image: "/src/assets/Laptop1.png",
    price: 171000.00, // Converted from 2999.99 USD to PHP
    specs: {
      "Brand": "ASUS",
      "Refresh Rate": "144Hz",
      "Screen Size": "32",
      "Vertical Resolution": "2160",
      "Horizontal Resolution": "3840",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "1ms",
      "Brightness": "1400 nits",
      "Contrast Ratio": "1000000:1",
      "HDR": "HDR1400",
      "Adaptive Sync": "G-Sync Ultimate",
      "Ports": "DisplayPort 1.4, HDMI 2.1, USB-C",
      "Stand Adjustments": "Height, Tilt, Swivel, Pivot",
      "VESA Mount": "100x100mm",
      "Weight": "11.2 kg"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'monitor-5',
    name: 'Acer Nitro XV272U 27" WQHD 170Hz IPS Monitor',
    image: "/src/assets/Laptop1.png",
    price: 17100.00, // Converted from 299.99 USD to PHP
    specs: {
      "Brand": "Acer",
      "Refresh Rate": "170Hz",
      "Screen Size": "27",
      "Vertical Resolution": "1440",
      "Horizontal Resolution": "2560",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "0.5ms",
      "Brightness": "400 nits",
      "Contrast Ratio": "1000:1",
      "HDR": "HDR10",
      "Adaptive Sync": "FreeSync Premium",
      "Port极": "DisplayPort 1.2, HDMI 2.0",
      "Stand Adjustments": "Height, Tilt",
      "VESA Mount": "100x100mm",
      "Weight": "5.5 kg"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'monitor-6',
    name: 'MSI Optix MAG274QRF-QD 27" QHD 165Hz Quantum Dot',
    image: "/src/assets/Laptop1.png",
    price: 25650.00, // Converted from 449.99 USD to PHP
    specs: {
      "Brand": "MSI",
      "Refresh Rate": "165Hz",
      "Screen Size": "27",
      "Vertical Resolution": "1440",
      "Horizontal Resolution": "2560",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "1ms",
      "Brightness": "400 nits",
      "Contrast Ratio": "极:1",
      "HDR": "HDR400",
      "Adaptive Sync": "G-Sync Compatible, FreeSync Premium",
      "Ports": "DisplayPort 1.4, HDMI 2.0, USB-C",
      "Stand Adjustments": "Height, T极, Swivel",
      "VESA Mount": "100x100mm",
      "Weight": "6.3 kg"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'monitor-7',
    name: 'Gigabyte M28U 28" 4K 144Hz SS IPS Gaming Monitor',
    image: "/src/assets/Laptop1.png",
    price: 34200.00, // Converted from 599.99 USD to PHP
    specs: {
      "Brand": "Gigabyte",
      "Refresh Rate": "144Hz",
      "Screen Size": "28",
      "Vertical Resolution": "2160",
      "Horizontal Resolution": "3840",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "1ms",
      "Brightness": "300 nits",
      "Contrast Ratio": "1000:1",
      "HDR": "HDR400",
      "Adaptive Sync": "G-Sync Compatible, FreeSync Premium",
      "Ports": "DisplayPort 1.4, HDMI 2.1, USB-C 90W",
      "Stand Adjustments": "Height, Tilt",
      "VESA Mount": "100x极mm",
      "Weight": "6.极 kg"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'monitor-8',
    name: 'Alienware AW3423DW 34" QD-OLED 175Hz Curved',
    image: "/src/assets/Laptop1.png",
    price: 74100.00, // Converted from 1299.99 USD to PHP
    specs: {
      "Brand": "Alienware",
      "Refresh Rate": "175Hz",
      "Screen Size": "34",
      "Vertical Resolution": "1440",
      "Horizontal Resolution": "3440",
      "Panel Type": "OLED",
      "Curvature": "1800R",
      "Response Time": "0.1ms",
      "Brightness": "1000 nits",
      "Contrast Ratio": "1000000:1",
      "HDR": "HDR400 True Black",
      "Adaptive Sync": "G-Sync Ultimate",
      "Ports": "DisplayPort 1.4, HDMI 2.0, USB Hub",
      "Stand Adjustments": "Height, Tilt, Swivel",
      "VESA Mount": "100x100mm",
      "Weight": "9.3 kg"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'monitor-9',
    name: 'ViewSonic XG270QG 27" QHD 165Hz Nano IPS G-Sync',
    image: "/src/assets/Laptop1.png",
    price: 28500.00, // Converted from 499.99 USD to PHP
    specs: {
      "Brand": "ViewSonic",
      "Refresh Rate": "165Hz",
      "Screen Size": "27",
      "Vertical Resolution": "1440",
      "Horizontal Resolution": "2560",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "1ms",
      "Brightness": "350 nits",
      "Contrast Ratio": "1000:1",
      "HDR": "HDR10",
      "Adaptive Sync": "G极Sync",
      "Ports": "DisplayPort 1.4, HDMI 2.0, USB Hub",
      "Stand Adjustments": "Height, Tilt, Swivel, Pivot",
      "VESA Mount": "100x100mm",
      "Weight": "6.7 kg"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'monitor-10',
    name: 'HP X27q 27" QHD 165Hz IPS Gaming Monitor',
    image: "/src/assets/Laptop1.png",
    price: 15960.00, // Converted from 279.99 USD to PHP
    specs: {
      "Brand": "HP",
      "Refresh Rate": "165Hz",
      "Screen Size": "27",
      "Vertical Resolution": "1440",
      "Horizontal Resolution": "2560",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "1ms",
      "Brightness": "400 nits",
      "Contrast Ratio": "1000:1",
      "HDR": "HDR400",
      "Adaptive Sync": "FreeSync",
      "Ports": "DisplayPort 1.4, HDMI 2.0",
      "Stand Adjustments": "Tilt",
      "VESA Mount": "100x100mm",
      "Weight": "5.2 kg"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'monitor-11',
    name: 'Samsung Odyssey Neo G9 49" DQHD 240Hz Mini-LED',
    image: "/src/assets/Laptop1.png",
    price: 91200.00, // Converted from 1599.99 USD to PHP
    specs: {
      "Brand": "Samsung",
      "Refresh Rate": "240Hz",
      "Screen Size": "49",
      "Vertical Resolution": "1440",
      "Horizontal Resolution": "5120",
      "Panel Type": "VA",
      "Curvature": "1000R",
      "Response Time": "1ms",
      "Brightness": "2000 nits",
      "Contrast Ratio": "1000000:1",
      "HDR": "HDR2000",
      "Adaptive Sync": "G-Sync Compatible, FreeSync Premium Pro",
      "Ports": "DisplayPort 1.4, HDMI 2.1, USB Hub",
      "Stand Adjustments": "Height, Tilt, Swivel",
      "VESA Mount": "100x100mm",
      "Weight": "16.7 kg"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'monitor-12',
    name: 'LG 27GN950-B 27" 4K Nano IPS 极Hz Gaming Monitor',
    image: "/src/assets/Laptop1.png",
    price: 45600.00, // Converted from 799.99 USD to PHP
    specs: {
      "Brand": "LG",
      "Refresh Rate": "144Hz",
      "Screen Size": "27",
      "Vertical Resolution": "2160",
      "Horizontal Resolution": "3840",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "1ms",
      "Brightness": "400 nits",
      "Contrast Ratio": "1000:1",
      "HDR": "HDR600",
      "Adaptive Sync": "G-Sync Compatible, FreeSync Premium Pro",
      "Ports": "DisplayPort 1.4, HDMI 2.1, USB Hub",
      "Stand Adjustments": "Height, Tilt, Pivot",
      "VESA Mount": "100x100mm",
      "Weight": "6.8 kg"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'monitor-13',
    name: 'AOC 24G2 24" Full HD 144Hz IPS Gaming Monitor',
    image: "/src/assets/Laptop1.png",
    price: 10260.00, // Converted from 179.99 USD to PHP
    specs: {
      "Brand": "AOC",
      "Refresh Rate": "144Hz",
      "Screen Size": "24",
      "Vertical Resolution": "1080",
      "Horizontal Resolution": "1920",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "1ms",
      "Brightness": "250 nits",
      "Contrast Ratio": "1000:1",
      "HDR": "No",
      "Adaptive Sync": "FreeSync",
      "Ports": "DisplayPort 1.2, HDMI 1.4, VGA",
      "Stand Adjustments": "Height, Tilt, Swivel, Pivot",
      "VESA Mount": "100x100mm",
      "Weight": "4.2 kg"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'monitor-14',
    name: 'Dell U2720Q 27" 4K USB-C IPS Ultrasharp Monitor',
    image: "/src/assets/Laptop1.png",
    price: 28500.00, // Converted from 499.99 USD to PHP
    specs: {
      "Brand": "Dell",
      "Refresh Rate": "60Hz",
      "Screen Size": "27",
      "Vertical Resolution": "2160",
      "Horizontal Resolution": "3840",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "5ms",
      "Brightness": "350 nits",
      "Contrast Ratio": "1300:1",
      "HDR": "HDR400",
      "Adaptive Sync": "No",
      "Ports": "DisplayPort, HDMI, USB-C 90W",
      "Stand Adjustments": "Height, Tilt, Swivel, Pivot",
      "VESA Mount": "100x100mm",
      "Weight": "极 kg"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'monitor-15',
    name: 'ASUS TUF Gaming VG279QM 27" Full HD 280Hz IPS',
    image: "/src/assets/Laptop1.png",
    price: 19950.00, // Converted from 349.99 USD to PHP
    specs: {
      "Brand": "ASUS",
      "Refresh Rate": "280Hz",
      "Screen Size": "27",
      "Vertical Resolution": "1080",
      "Horizontal Resolution": "1920",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "1ms",
      "Brightness": "400 nits",
      "Contrast Ratio": "1000:1",
      "HDR": "HDR400",
      "Adaptive Sync": "G-Sync Compatible, FreeSync",
      "Ports": "DisplayPort 1.2, HDMI 2.0",
      "Stand Adjustments": "Height, Tilt, Swivel",
      "VESA Mount": "100x100mm",
      "Weight": "5.8 kg"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mon极r-16',
    name: 'Philips 346B1C 34" UWQHD 100Hz Curved Business Monitor',
    image: "/src/assets/Laptop1.png",
    price: 25650.00, // Converted from 449.99 USD to PHP
    specs: {
      "Brand": "Philips",
      "Refresh Rate": "极Hz",
      "Screen Size": "34",
      "Vertical Resolution": "1440",
      "Horizontal Resolution": "3440",
      "Panel Type": "VA",
      "Curvature": "1500R",
      "Response Time": "4ms",
      "Brightness": "300 nits",
      "Contrast Ratio": "3000:1",
      "HDR": "HDR10",
      "Adaptive Sync": "FreeSync",
      "Ports": "DisplayPort, HDMI, USB-C 90W, Ethernet",
      "Stand Adjustments": "Height, Tilt, Swivel",
      "VESA Mount": "100x100mm",
      "Weight": "9.1 kg"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'monitor-17',
    name: 'MSI MPG ARTYMIS 343CQR 34" WQHD 165Hz Curved',
    image: "/src/assets/Laptop1.png",
    price: 39900.00, // Converted from 699.99 USD to PHP
    specs: {
      "Brand": "MSI",
      "Refresh Rate": "165Hz",
      "Screen Size": "34",
      "Vertical Resolution": "1440",
      "Horizontal Resolution": "3440",
      "Panel Type": "VA",
      "Curvature": "1000R",
      "Response Time": "1ms",
      "Brightness": "400 nits",
      "Contrast Ratio": "3000:1",
      "HDR": "HDR400",
      "Adaptive Sync": "FreeSync Premium",
      "Ports": "DisplayPort 1.4, HDMI 2.0, USB Hub",
      "Stand Adjustments": "Height, Tilt, Swivel",
      "VESA Mount": "100x100mm",
      "Weight": "8.9 kg"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'monitor-18',
    name: 'Gigabyte G27Q 27" QHD 144Hz IPS Gaming Monitor',
    image: "/src/assets/Laptop1.png",
    price: 17100.00, // Converted from 299.99 USD to PHP
    specs: {
      "Brand": "Gigabyte",
      "Refresh Rate": "144Hz",
      "Screen Size": "27",
      "Vertical Resolution": "1440",
      "Horizontal Resolution": "2560",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "1ms",
      "Brightness": "350 nits",
      "Contrast Ratio": "1000:1",
      "HDR": "HDR400",
      "Adaptive Sync": "FreeSync Premium",
      "Ports": "DisplayPort 1.2, HDMI 2.0",
      "Stand Adjustments": "Height, Tilt",
      "VESA Mount": "100x100mm",
      "Weight": "5.6 kg"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'monitor-19',
    name: 'Samsung UR55 28" 4K 60Hz IPS HDR Monitor',
    image: "/src/assets/Laptop1.png",
    price: 17100.00, // Converted from 299.99 USD to PHP
    specs: {
      "Brand": "Samsung",
      "Refresh Rate": "60Hz",
      "Screen Size": "28",
      "Vertical Resolution": "2160",
      "Horizontal Resolution": "3840",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "4ms",
      "Brightness": "300 nits",
      "Contrast Ratio": "1000:1",
      "HDR": "HDR10",
      "Adaptive Sync": "FreeSync",
      "Ports": "DisplayPort 1.2, HDMI 2.0",
      "Stand Adjustments": "Tilt",
      "VESA Mount": "75x75mm",
      "Weight": "4.8 kg"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'monitor-20',
    name: 'ViewSonic ELITE XG270 27" Full HD 240Hz IPS',
    image: "/src/assets/Laptop1.png",
    price: 21660.00, // Converted from 379.99 USD to PHP
    specs: {
      "Brand": "ViewSonic",
      "Refresh Rate": "240Hz",
      "Screen Size": "27",
      "Vertical Resolution": "1080",
      "Horizontal Resolution": "1920",
      "Panel Type": "IPS",
      "Curvature": "Flat",
      "Response Time": "0.5ms",
      "Brightness": "350 nits",
      "Contrast Ratio": "1000:1",
      "HDR": "HDR10",
      "Adaptive Sync": "G-Sync Compatible, FreeSync Premium",
      "Ports": "DisplayPort 1.4, HDMI 2.0, USB Hub",
      "Stand Adjustments": "Height, Tilt, Swivel, Pivot",
      "VESA Mount": "100x100mm",
      "Weight": "6.2 kg"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  }
];