//client/src/components/PCBuilder/Modal/MockData/Keyboard/Keyboard.js
export const keyboardData = [
  {
    id: 'keyboard-1',
    name: 'Corsair K100 RGB Mechanical Gaming Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 11400.00, // Converted from 199.99 USD to PHP
    specs: {
      "Keyboard Brand": "Corsair",
      "Switch Type": "Cherry MX Speed Silver",
      "Backlight": "RGB",
      "Connectivity": "Wired",
      "Layout": "Full-size (100%)",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "45g",
      "Actuation Point": "1.2mm",
      "Polling Rate": "4000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "Yes",
      "Wrist Rest": "Detachable",
      "Construction": "Aluminum frame",
      "Dimensions": "465 x 166 x 36 mm",
      "Weight": "1.2 kg",
      "Software": "iCUE",
      "USB Passthrough": "Yes"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'keyboard-2',
    name: 'Razer BlackWidow V4 Pro Mechanical Gaming Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 13110.00, // Converted from 229.99 USD to PHP
    specs: {
      "Keyboard Brand": "Razer",
      "Switch Type": "Razer Green Mechanical",
      "Backlight": "RGB",
      "Connectivity": "Wired",
      "Layout": "Full-size (100%)",
      "Keycaps": "Double-shot ABS",
      "Actuation Force": "50g",
      "Actuation Point": "1.9mm",
      "Polling Rate": "8000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "Yes",
      "Wrist Rest": "Magnetic plush leatherette",
      "Construction": "Aluminum top plate",
      "Dimensions": "470 x 165 x 40 mm",
      "Weight": "1.4 kg",
      "Software": "Razer Synapse",
      "USB Passthrough": "Yes"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'keyboard-3',
    name: 'Logitech G915 TKL Lightspeed Wireless Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 13110.00, // Converted from 229.99 USD to PHP
    specs: {
      "Keyboard Brand": "Logitech",
      "Switch Type": "GL Tactile",
      "Backlight": "RGB",
      "Connectivity": "Wireless",
      "Layout": "Tenkeyless (80%)",
      "Keycaps": "ABS",
      "Actuation Force": "50g",
      "Actuation Point": "1.5mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "Yes",
      "Wrist Rest": "No",
      "Construction": "Aluminum alloy",
      "Dimensions": "368 x 150 x 22 mm",
      "Weight": "0.8 kg",
      "Software": "Logitech G Hub",
      "Battery Life": "40 hours"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'keyboard-4',
    name: 'Keychron K8 Pro Wireless Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 5130.00, // Converted from 89.99 USD to PHP
    specs: {
      "Keyboard Brand": "Keychron",
      "Switch Type": "Gateron G Pro Brown",
      "Backlight": "RGB",
      "Connectivity": "Wireless",
      "Layout": "Tenkeyless (80%)",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "55g",
      "Actuation Point": "2.0mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "Yes",
      "Wrist Rest": "No",
      "Construction": "Plastic case",
      "Dimensions": "357 x 131 x 41 mm",
      "Weight": "0.9 kg",
      "Software": "VIA/QMK",
      "Battery Life": "80 hours"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'keyboard-5',
    name: 'SteelSeries Apex Pro TKL Wireless Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 11400.00, // Converted from 199.99 USD to PHP
    specs: {
      "Keyboard Brand": "SteelSeries",
      "Switch Type": "OmniPoint 2.0 Adjustable",
      "Backlight": "RGB",
      "Connectivity": "Wireless",
      "Layout": "Tenkeyless (80%)",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "Adjustable 0.4-3.6mm",
      "Actuation Point": "Adjustable",
      "Polling Rate": "2000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "Yes",
      "Wrist Rest": "Magnetic",
      "Construction": "Aluminum alloy",
      "Dimensions": "360 x 128 x 40 mm",
      "Weight": "0.9 kg",
      "Software": "SteelSeries GG",
      "Battery Life": "60 hours"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'keyboard-6',
    name: 'Ducky One 2 SF Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 7410.00, // Converted from 129.99 USD to PHP
    specs: {
      "Keyboard Brand": "Ducky",
      "Switch Type": "Cherry MX Red",
      "Backlight": "RGB",
      "Connectivity": "Wired",
      "Layout": "65%",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "45g",
      "Actuation Point": "2.0mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "No",
      "Wrist Rest": "No",
      "Construction": "Plastic case",
      "Dimensions": "310 x 110 x 40 mm",
      "Weight": "0.7 kg",
      "Software": "None",
      "Hot-swappable": "Yes"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'keyboard-7',
    name: 'HyperX Alloy Origins 65 Mechanical Gaming Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 5700.00, // Converted from 99.99 USD to PHP
    specs: {
      "Keyboard Brand": "HyperX",
      "Switch Type": "HyperX Red Linear",
      "Backlight": "RGB",
      "Connectivity": "Wired",
      "Layout": "65%",
      "Keycaps": "Double-shot ABS",
      "Actuation Force": "45g",
      "Actuation Point": "1.8mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "No",
      "Wrist Rest": "No",
      "Construction": "Aluminum frame",
      "Dimensions": "310 x 110 x 36 mm",
      "Weight": "0.6 kg",
      "Software": "HyperX NGENUITY"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'keyboard-8',
    name: 'Glorious GMMK 2 96% Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 7980.00, // Converted from 139.99 USD to PHP
    specs: {
      "Keyboard Brand": "Glorious",
      "Switch Type": "Glorious Fox Linear",
      "Backlight": "RGB",
      "Connectivity": "Wired",
      "Layout": "96%",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "50g",
      "Actuation Point": "2.0mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "Yes",
      "Wrist Rest": "No",
      "Construction": "Aluminum frame",
      "Dimensions": "387 x 124 x 40 mm",
      "Weight": "0.9 kg",
      "Software": "Glorious Core",
      "Hot-swappable": "Yes"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'keyboard-9',
    name: 'ASUS ROG Strix Scope II 96 Wireless Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 10260.00, // Converted from 179.99 USD to PHP
    specs: {
      "Keyboard Brand": "ASUS",
      "Switch Type": "ROG NX Snow Linear",
      "Backlight": "RGB",
      "Connectivity": "Wireless",
      "Layout": "96%",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "40g",
      "Actuation Point": "1.8mm",
      "Polling Rate": "2000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "Yes",
      "Wrist Rest": "Magnetic",
      "Construction": "Aluminum top plate",
      "Dimensions": "390 x 130 x 45 mm",
      "Weight": "1.2 kg",
      "Software": "Armoury Crate",
      "Battery Life": "150 hours"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'keyboard-10',
    name: 'NuPhy Halo75 Wireless Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 6840.00, // Converted from 119.99 USD to PHP
    specs: {
      "Keyboard Brand": "NuPhy",
      "Switch Type": "Gateron Baby Kangaroo Tactile",
      "Backlight": "RGB",
      "Connectivity": "Wireless",
      "Layout": "75%",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "55g",
      "Actuation Point": "2.0mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "Yes",
      "Wrist Rest": "Included",
      "Construction": "Plastic case with silicone dampening",
      "Dimensions": "325 x 142 x 40 mm",
      "Weight": "1.1 kg",
      "Software": "None",
      "Battery Life": "100 hours"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'keyboard-11',
    name: 'Royal Kludge RK84 Wireless Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 3990.00, // Converted from 69.99 USD to PHP
    specs: {
      "Keyboard Brand": "Royal Kludge",
      "Switch Type": "RK Red Linear",
      "Backlight": "RGB",
      "Connectivity": "Wireless",
      "Layout": "75%",
      "Keycaps": "ABS",
      "Actuation Force": "50g",
      "Actuation Point": "2.0mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "Yes",
      "Wrist Rest": "No",
      "Construction": "Plastic case",
      "Dimensions": "320 x 120 x 38 mm",
      "Weight": "0.7 kg",
      "Software": "None",
      "Battery Life": "200 hours"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'keyboard-12',
    name: 'Leopold FC750R PD Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 8550.00, // Converted from 149.99 USD to PHP
    specs: {
      "Keyboard Brand": "Leopold",
      "Switch Type": "Cherry MX Brown",
      "Backlight": "None",
      "Connectivity": "Wired",
      "Layout": "Tenkeyless (80%)",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "55g",
      "Actuation Point": "2.0mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "No",
      "Wrist Rest": "No",
      "Construction": "Plastic case",
      "Dimensions": "360 x 135 x 40 mm",
      "Weight": "1.0 kg",
      "Software": "None"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'keyboard-13',
    name: 'Wooting 60HE Analog Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 9975.00, // Converted from 174.99 USD to PHP
    specs: {
      "Keyboard Brand": "Wooting",
      "Switch Type": "Lekker Switch 60 Analog",
      "Backlight": "RGB",
      "Connectivity": "Wired",
      "Layout": "60%",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "Adjustable 0.1-4.0mm",
      "Actuation Point": "Adjustable",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "No",
      "Wrist Rest": "No",
      "Construction": "Aluminum case",
      "Dimensions": "295 x 102 x 38 mm",
      "Weight": "0.8 kg",
      "Software": "Wootility"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'keyboard-14',
    name: 'Epomaker TH80 Pro Wireless Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 5130.00, // Converted from 89.99 USD to PHP
    specs: {
      "Keyboard Brand": "Epomaker",
      "Switch Type": "Gateron Yellow Pro",
      "Backlight": "RGB",
      "Connectivity": "Wireless",
      "Layout": "75%",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "50g",
      "Actuation Point": "2.0mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "Yes",
      "Wrist Rest": "No",
      "Construction": "Plastic case",
      "Dimensions": "325 x 142 x 38 mm",
      "Weight": "0.9 kg",
      "Software": "None",
      "Battery Life": "150 hours"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'keyboard-15',
    name: 'Cooler Master SK622 Wireless Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 5700.00, // Converted from 99.99 USD PHP
    specs: {
      "Keyboard Brand": "Cooler Master",
      "Switch Type": "Cherry MX Low Profile Red",
      "Backlight": "RGB",
      "Connectivity": "Wireless",
      "Layout": "60%",
      "Keycaps": "ABS",
      "Actuation Force": "45g",
      "Actuation Point": "1.2mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "No",
      "Wrist Rest": "No",
      "Construction": "Aluminum frame",
      "Dimensions": "293 x 102 x 30 mm",
      "Weight": "0.5 kg",
      "Software": "MasterPlus",
      "Battery Life": "45 hours"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'keyboard-16',
    name: 'Drop ALT Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 11400.00, // Converted from 199.99 USD to PHP
    specs: {
      "Keyboard Brand": "Drop",
      "Switch Type": "Halo True Tactile",
      "Backlight": "RGB",
      "Connectivity": "Wired",
      "Layout": "65%",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "54g",
      "Actuation Point": "1.9mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "No",
      "Wrist Rest": "No",
      "Construction": "Aluminum case",
      "Dimensions": "325 x 110 x 35 mm",
      "Weight": "1.1 kg",
      "Software": "None",
      "Hot-swappable": "Yes"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'keyboard-17',
    name: 'Microsoft Surface Ergonomic Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 7410.00, // Converted from 129.99 USD to PHP
    specs: {
      "Keyboard Brand": "Microsoft",
      "Switch Type": "Membrane",
      "Backlight": "No",
      "Connectivity": "Wireless",
      "Layout": "Full-size (100%)",
      "Keycaps": "ABS",
      "Actuation Force": "55g",
      "Actuation Point": "2.0mm",
      "Polling Rate": "125Hz",
      "Anti-Ghosting": "6-key rollover",
      "Media Controls": "Yes",
      "Wrist Rest": "Integrated",
      "Construction": "Plastic",
      "Dimensions": "430 x 200 x 35 mm",
      "Weight": "0.8 kg",
      "Software": "None",
      "Battery Life": "12 months"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'keyboard-18',
    name: 'Redragon K552 Kumara Mechanical Gaming Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 2280.00, // Converted from 39.99 USD to PHP
    specs: {
      "Keyboard Brand": "Redragon",
      "Switch Type": "Outemu Blue Clicky",
      "Backlight": "RGB",
      "Connectivity": "Wired",
      "Layout": "Tenkeyless (80%)",
      "Keycaps": "ABS",
      "Actuation Force": "50g",
      "Actuation Point": "2.2mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "No",
      "Wrist Rest": "No",
      "Construction": "Plastic case",
      "Dimensions": "360 x 130 x 35 mm",
      "Weight": "0.7 kg",
      "Software": "None"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'keyboard-19',
    name: 'Varmilo VA88M Moonlight Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 9690.00, // Converted from 169.99 USD to PHP
    specs: {
      "Keyboard Brand": "Varmilo",
      "Switch Type": "Cherry MX Silent Red",
      "Backlight": "White LED",
      "Connectivity": "Wired",
      "Layout": "Tenkeyless (80%)",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "45g",
      "Actuation Point": "1.9mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "No",
      "Wrist Rest": "No",
      "Construction": "Plastic case",
      "Dimensions": "355 x 135 x 40 mm",
      "Weight": "1.0 kg",
      "Software": "None"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'keyboard-20',
    name: 'Akko 3068B Plus Wireless Mechanical Keyboard',
    image: "/src/assets/Laptop1.png",
    price: 4560.00, // Converted from 79.99 USD to PHP
    specs: {
      "Keyboard Brand": "Akko",
      "Switch Type": "Akko CS Jelly Pink",
      "Backlight": "RGB",
      "Connectivity": "Wireless",
      "Layout": "65%",
      "Keycaps": "Double-shot PBT",
      "Actuation Force": "43g",
      "Actuation Point": "1.9mm",
      "Polling Rate": "1000Hz",
      "Anti-Ghosting": "Full N-key rollover",
      "Media Controls": "No",
      "Wrist Rest": "No",
      "Construction": "Plastic case",
      "Dimensions": "310 x 110 x 38 mm",
      "Weight": "0.7 kg",
      "Software": "None",
      "Battery Life": "120 hours"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  }
];