//client/src/components/PCBuilder/Modal/MockData/Storage/Storage.js
export const storageData = [
  {
    id: 'storage-1',
    name: 'Samsung 980 Pro 2TB PCIe 4.0 NVMe SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 9143.43,
    specs: {
      "Type": "SSD",
      "Form Factor": "M.2 2280",
      "Manufacturer": "Samsung",
      "NVMe": "Yes",
      "Capacity": "2000 GB",
      "Interface": "PCIe 4.0 x4",
      "Sequential Read": "7000 MB/s",
      "Sequential Write": "5000 MB/s",
      "TBW": "1200 TB",
      "DRAM Cache": "Yes",
      "NAND Type": "TLC",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-2',
    name: 'Western Digital WD Blue 4TB 3.5" HDD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 4573.43,
    specs: {
      "Type": "HDD",
      "Form Factor": "3.5-inch",
      "Manufacturer": "Western Digital",
      "NVMe": "No",
      "Capacity": "4000 GB",
      "Interface": "SATA 6.0 Gb/s",
      "RPM": "5400 RPM",
      "Cache": "256 MB",
      "Sequential Read": "180 MB/s",
      "Sequential Write": "180 MB/s",
      "MTBF": "1,000,000 hours",
      "Warranty": "2 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-3',
    name: 'Crucial P5 Plus 1TB PCIe 4.0 NVMe SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 5141.47,
    specs: {
      "Type": "SSD",
      "Form Factor": "M.2 2280",
      "Manufacturer": "Crucial",
      "NVMe": "Yes",
      "Capacity": "1000 GB",
      "Interface": "PCIe 4.0 x4",
      "Sequential Read": "6600 MB/s",
      "Sequential Write": "5000 MB/s",
      "TBW": "600 TB",
      "DRAM Cache": "Yes",
      "NAND Type": "TLC",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-4',
    name: 'Seagate IronWolf Pro 12TB 3.5" NAS HDD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 17152.13,
    specs: {
      "Type": "HDD",
      "Form Factor": "3.5-inch",
      "Manufacturer": "Seagate",
      "NVMe": "No",
      "Capacity": "12000 GB",
      "Interface": "SATA 6.0 Gb/s",
      "RPM": "7200 RPM",
      "Cache": "256 MB",
      "Sequential Read": "250 MB/s",
      "Sequential Write": "250 MB/s",
      "MTBF": "1,200,000 hours",
      "Workload Rate": "300 TB/year",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-5',
    name: 'SK Hynix Platinum P41 2TB PCIe 4.0 NVMe SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 9712.87,
    specs: {
      "Type": "SSD",
      "Form Factor": "M.2 2280",
      "Manufacturer": "SK Hynix",
      "NVMe": "Yes",
      "Capacity": "2000 GB",
      "Interface": "PCIe 4.0 x4",
      "Sequential Read": "7000 MB/s",
      "Sequential Write": "6500 MB/s",
      "TBW": "1200 TB",
      "DRAM Cache": "Yes",
      "NAND Type": "TLC",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-6',
    name: 'Samsung 870 EVO 1TB 2.5" SATA SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 5717.17,
    specs: {
      "Type": "SSD",
      "Form Factor": "2.5-inch",
      "Manufacturer": "Samsung",
      "NVMe": "No",
      "Capacity": "1000 GB",
      "Interface": "SATA 6.0 Gb/s",
      "Sequential Read": "560 MB/s",
      "Sequential Write": "530 MB/s",
      "TBW": "600 TB",
      "DRAM Cache": "Yes",
      "NAND Type": "TLC",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-7',
    name: 'Sabrent Rocket 4 Plus 4TB PCIe 4.0 NVMe SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 19998.77,
    specs: {
      "Type": "SSD",
      "Form Factor": "M.2 2280",
      "Manufacturer": "Sabrent",
      "NVMe": "Yes",
      "Capacity": "4000 GB",
      "Interface": "PCIe 4.0 x4",
      "Sequential Read": "7100 MB/s",
      "Sequential Write": "6600 MB/s",
      "TBW": "3000 TB",
      "DRAM Cache": "Yes",
      "NAND Type": "TLC",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-8',
    name: 'Toshiba X300 8TB 3.5" Performance HDD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 10287.03,
    specs: {
      "Type": "HDD",
      "Form Factor": "3.5-inch",
      "Manufacturer": "Toshiba",
      "NVMe": "No",
      "Capacity": "8000 GB",
      "Interface": "SATA 6.0 Gb/s",
      "RPM": "7200 RPM",
      "Cache": "256 MB",
      "Sequential Read": "235 MB/s",
      "Sequential Write": "235 MB/s",
      "MTBF": "600,000 hours",
      "Warranty": "2 years"
    },
    has3D: false,
    stockCount: 0
    },
  {
    id: 'storage-9',
    name: 'WD Black SN850X 1TB PCIe 4.0 NVMe SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 6285.20,
    specs: {
      "Type": "SSD",
      "Form Factor": "M.2 2280",
      "Manufacturer": "Western Digital",
      "NVMe": "Yes",
      "Capacity": "1000 GB",
      "Interface": "PCIe 4.0 x4",
      "Sequential Read": "7300 MB/s",
      "Sequential Write": "6300 MB/s",
      "TBW": "600 TB",
      "DRAM Cache": "Yes",
      "NAND Type": "TLC",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-10',
    name: 'Kingston NV2 2TB PCIe 4.0 NVMe SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 6853.23,
    specs: {
      "Type": "SSD",
      "Form Factor": "M.2 2280",
      "Manufacturer": "Kingston",
      "NVMe": "Yes",
      "Capacity": "2000 GB",
      "Interface": "PCIe 4.0 x4",
      "Sequential Read": "3500 MB/s",
      "Sequential Write": "2800 MB/s",
      "TBW": "500 TB",
      "DRAM Cache": "No",
      "NAND Type": "QLC",
      "Encryption": "AES 256-bit",
      "Warranty": "3 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-11',
    name: 'Seagate FireCuda 530 2TB PCIe 4.0 NVMe SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 10855.43,
    specs: {
      "Type": "SSD",
      "Form Factor": "M.2 2280",
      "Manufacturer": "Seagate",
      "NVMe": "Yes",
      "Capacity": "2000 GB",
      "Interface": "PCIe 4.0 x4",
      "Sequential Read": "7300 MB/s",
      "Sequential Write": "6900 MB/s",
      "TBW": "1275 TB",
      "DRAM Cache": "Yes",
      "NAND Type": "TLC",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-12',
    name: 'Crucial MX500 2TB 2.5" SATA SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 7432.97,
    specs: {
      "Type": "SSD",
      "Form Factor": "2.5-inch",
      "Manufacturer": "Crucial",
      "NVMe": "No",
      "Capacity": "2000 GB",
      "Interface": "SATA 6.0 Gb/s",
      "Sequential Read": "560 MB/s",
      "Sequential Write": "510 MB/s",
      "TBW": "700 TB",
      "DRAM Cache": "Yes",
      "NAND Type": "TLC",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-13',
    name: 'Western Digital Red Pro 10TB 3.5" NAS HDD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 14292.97,
    specs: {
      "Type": "HDD",
      "Form Factor": "3.5-inch",
      "Manufacturer": "Western Digital",
      "NVMe": "No",
      "Capacity": "10000 GB",
      "Interface": "SATA 6.0 Gb/s",
      "RPM": "7200 RPM",
      "Cache": "256 MB",
      "Sequential Read": "240 MB/s",
      "Sequential Write": "240 MB/s",
      "MTBF": "1,000,000 hours",
      "Workload Rate": "300 TB/year",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-14',
    name: 'G.Skill Trident Z44Q 4TB PCIe 4.0 NVMe SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 18864.97,
    specs: {
      "Type": "SSD",
      "Form Factor": "M.2 2280",
      "Manufacturer": "G.Skill",
      "NVMe": "Yes",
      "Capacity": "4000 GB",
      "Interface": "PCIe 4.0 x4",
      "Sequential Read": "7000 MB/s",
      "Sequential Write": "6500 MB/s",
      "TBW": "3000 TB",
      "DRAM Cache": "Yes",
      "NAND Type": "TLC",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-15',
    name: 'Seagate BarraCuda 2TB 3.5" HDD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 3429.97,
    specs: {
      "Type": "HDD",
      "Form Factor": "3.5-inch",
      "Manufacturer": "Seagate",
      "NVMe": "No",
      "Capacity": "2000 GB",
      "Interface": "SATA 6.0 Gb/s",
      "RPM": "7200 RPM",
      "Cache": "256 MB",
      "Sequential Read": "220 MB/s",
      "Sequential Write": "220 MB/s",
      "MTBF": "600,000 hours",
      "Warranty": "2 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-16',
    name: 'ADATA XPG GAMMIX S70 Blade 2TB PCIe 4.0 NVMe SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 7993.97,
    specs: {
      "Type": "SSD",
      "Form Factor": "M.2 2280",
      "Manufacturer": "ADATA",
      "NVMe": "Yes",
      "Capacity": "2000 GB",
      "Interface": "PCIe 4.0 x4",
      "Sequential Read": "7400 MB/s",
      "Sequential Write": "6800 MB/s",
      "TBW": "1480 TB",
      "DRAM Cache": "Yes",
      "NAND Type": "TLC",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-17',
    name: 'Intel 670p 2TB PCIe 3.0 NVMe SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 5717.17,
    specs: {
      "Type": "SSD",
      "Form Factor": "M.2 2280",
      "Manufacturer": "Intel",
      "NVMe": "Yes",
      "Capacity": "2000 GB",
      "Interface": "PCIe 3.0 x4",
      "Sequential Read": "3500 MB/s",
      "Sequential Write": "2700 MB/s",
      "TBW": "740 TB",
      "DRAM Cache": "No",
      "NAND Type": "QLC",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 0
    },
  {
    id: 'storage-18',
    name: 'SanDisk Extreme Pro 1TB Portable SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 7432.97,
    specs: {
      "Type": "SSD",
      "Form Factor": "2.5-inch",
      "Manufacturer": "SanDisk",
      "NVMe": "No",
      "Capacity": "1000 GB",
      "Interface": "USB 3.2 Gen 2",
      "Sequential Read": "1050 MB/s",
      "Sequential Write": "1000 MB/s",
      "Shock Resistance": "2-meter drop",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-19',
    name: 'Samsung 990 Pro 4TB PCIe 4.0 NVMe SSD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 19999.97,
    specs: {
      "Type": "SSD",
      "Form Factor": "M.2 2280",
      "Manufacturer": "Samsung",
      "NVMe": "Yes",
      "Capacity": "4000 GB",
      "Interface": "PCIe 4.0 x4",
      "Sequential Read": "7450 MB/s",
      "Sequential Write": "6900 MB/s",
      "TBW": "2400 TB",
      "DRAM Cache": "Yes",
      "NAND Type": "TLC",
      "Encryption": "AES 256-bit",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    },
  {
    id: 'storage-20',
    name: 'Seagate Exos X20 20TB 3.5" Enterprise HDD',
    image: "https://dfestore.com/wp-content/uploads/2025/12/Untitled-1-24.jpg",
    price: 22868.97,
    specs: {
      "Type": "HDD",
      "Form Factor": "3.5-inch",
      "Manufacturer": "Seagate",
      "NVMe": "No",
      "Capacity": "20000 GB",
      "Interface": "SATA 6.0 Gb/s",
      "RPM": "7200 RPM",
      "Cache": "256 MB",
      "Sequential Read": "285 MB/s",
      "Sequential Write": "285 MB/s",
      "MTBF": "2,500,000 hours",
      "Workload Rate": "550 TB/year",
      "Warranty": "5 years"
    },
    has3D: false,
    stockCount: 10
    }
];
