//client/src/components/PCBuilder/Modal/MockData/Case/Case.js
export const caseData = [
  {
    id: 'case-1',
    name: 'HYTE Y60 ATX Mid Tower White Tempered Glass Side Panel',
    image: "/src/assets/Laptop1.png",
    price: 179.97,
    specs: {
      "Form Factor": "ATX Mid Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "HYTE",
      "Color": "WHITE",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "440 mm",
      "Max CPU Cooler Height": "180 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 4,
      "Expansion Slots": 7,
      "Volume": "58 L",
      "Weight": "13.2 lbs"
    },
    has3D: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'case-2',
    name: 'NZXT H510 Elite ATX Mid Tower Black',
    image: "/src/assets/Laptop1.png",
    price: 149.99,
    specs: {
      "Form Factor": "ATX Mid Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "NZXT",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "381 mm",
      "Max CPU Cooler Height": "165 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 3,
      "Expansion Slots": 7,
      "Volume": "46 L",
      "Weight": "18.3 lbs"
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'case-3',
    name: 'Corsair 4000D Airflow ATX Mid Tower',
    image: "/src/assets/Laptop1.png",
    price: 94.99,
    specs: {
      "Form Factor": "ATX Mid Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "Corsair",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "360 mm",
      "Max CPU Cooler Height": "170 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 4,
      "Expansion Slots": 7,
      "Volume": "45 L",
      "Weight": "17.6 lbs"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'case-4',
    name: 'Fractal Design Meshify C Mini MicroATX Mini Tower',
    image: "/src/assets/Laptop1.png",
    price: 99.99,
    specs: {
      "Form Factor": "Micro ATX Mini Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "Fractal Design",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "315 mm",
      "Max CPU Cooler Height": "172 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 3,
      "Expansion Slots": 4,
      "Volume": "39 L",
      "Weight": "16.3 lbs"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'case-5',
    name: 'Lian Li O11 Dynamic Mini Snow White',
    image: "/src/assets/Laptop1.png",
    price: 129.99,
    specs: {
      "Form Factor": "ATX Mid Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "Lian Li",
      "Color": "WHITE",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "395 mm",
      "Max CPU Cooler Height": "170 mm",
      "3.5\" Drive Bays": 1,
      "2.5\" Drive Bays": 5,
      "Expansion Slots": 7,
      "Volume": "49 L",
      "Weight": "15.4 lbs"
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'case-6',
    name: 'Cooler Master MasterBox Q300L MicroATX Mini Tower',
    image: "/src/assets/Laptop1.png",
    price: 49.99,
    specs: {
      "Form Factor": "Micro ATX Mini Tower",
      "Side Panel": "Acrylic",
      "Manufacturer": "Cooler Master",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "360 mm",
      "Max CPU Cooler Height": "159 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 3,
      "Expansion Slots": 4,
      "Volume": "33 L",
      "Weight": "9.9 lbs"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'case-7',
    name: 'Phanteks Enthoo Pro Full Tower Chassis',
    image: "/src/assets/Laptop1.png",
    price: 129.99,
    specs: {
      "Form Factor": "ATX Full Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "Phanteks",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "490 mm",
      "Max CPU Cooler Height": "193 mm",
      "3.5\" Drive Bays": 6,
      "2.5\" Drive Bays": 6,
      "Expansion Slots": 8,
      "Volume": "76 L",
      "Weight": "29.8 lbs"
    },
    has3D: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'case-8',
    name: 'NZXT H1 Mini ITX Tower',
    image: "/src/assets/Laptop1.png",
    price: 199.99,
    specs: {
      "Form Factor": "Mini-ITX Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "NZXT",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "305 mm",
      "Max CPU Cooler Height": "140 mm",
      "3.5\" Drive Bays": 0,
      "2.5\" Drive Bays": 2,
      "Expansion Slots": 2,
      "Volume": "27 L",
      "Weight": "13.2 lbs"
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'case-9',
    name: 'be quiet! Pure Base 500DX ATX Mid Tower',
    image: "/src/assets/Laptop1.png",
    price: 109.99,
    specs: {
      "Form Factor": "ATX Mid Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "be quiet!",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "369 mm",
      "Max CPU Cooler Height": "190 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 4,
      "Expansion Slots": 7,
      "Volume": "49 L",
      "Weight": "19.6 lbs"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'case-10',
    name: 'Thermaltake Core P3 ATX Mid Tower Open Frame',
    image: "/src/assets/Laptop1.png",
    price: 139.99,
    specs: {
      "Form Factor": "ATX Mid Tower",
      "Side Panel": "None",
      "Manufacturer": "Thermaltake",
      "Color": "BLACK",
      "Transparent Side Panel": "No",
      "Max GPU Length": "420 mm",
      "Max CPU Cooler Height": "180 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 4,
      "Expansion Slots": 7,
      "Volume": "N/A",
      "Weight": "20.1 lbs"
    },
    has3D: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'case-11',
    name: 'ASUS TUF Gaming GT301 ATX Mid Tower',
    image: "/src/assets/Laptop1.png",
    price: 89.99,
    specs: {
      "Form Factor": "ATX Mid Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "ASUS",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "330 mm",
      "Max CPU Cooler Height": "160 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 4,
      "Expansion Slots": 7,
      "Volume": "47 L",
      "Weight": "15.4 lbs"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'case-12',
    name: 'SilverStone Sugo SG13 Mini-ITX Desktop',
    image: "/src/assets/Laptop1.png",
    price: 59.99,
    specs: {
      "Form Factor": "Mini-ITX Desktop",
      "Side Panel": "Steel",
      "Manufacturer": "SilverStone",
      "Color": "WHITE",
      "Transparent Side Panel": "No",
      "Max GPU Length": "266 mm",
      "Max CPU Cooler Height": "61 mm",
      "3.5\" Drive Bays": 1,
      "2.5\" Drive Bays": 2,
      "Expansion Slots": 2,
      "Volume": "11.5 L",
      "Weight": "7.1 lbs"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'case-13',
    name: 'Corsair Obsidian 1000D Super Tower',
    image: "/src/assets/Laptop1.png",
    price: 499.99,
    specs: {
      "Form Factor": "EATX Full Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "Corsair",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "500 mm",
      "Max CPU Cooler Height": "190 mm",
      "3.5\" Drive Bays": 4,
      "2.5\" Drive Bays": 6,
      "Expansion Slots": 10,
      "Volume": "121 L",
      "Weight": "35.3 lbs"
    },
    has3D: true,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'case-14',
    name: 'MSI MPG GUNGNIR 110R ATX Mid Tower',
    image: "/src/assets/Laptop1.png",
    price: 119.99,
    specs: {
      "Form Factor": "ATX Mid Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "MSI",
      "Color": "WHITE",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "340 mm",
      "Max CPU Cooler Height": "170 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 4,
      "Expansion Slots": 7,
      "Volume": "48 L",
      "Weight": "17.6 lbs"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'case-15',
    name: 'In Win 101 MicroATX Mid Tower',
    image: "/src/assets/Laptop1.png",
    price: 79.99,
    specs: {
      "Form Factor": "Micro ATX Mid Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "In Win",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "320 mm",
      "Max CPU Cooler Height": "160 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 3,
      "Expansion Slots": 5,
      "Volume": "42 L",
      "Weight": "14.3 lbs"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'case-16',
    name: 'DeepCool MATREXX 55 MESH ATX Mid Tower',
    image: "/src/assets/Laptop1.png",
    price: 69.99,
    specs: {
      "Form Factor": "ATX Mid Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "DeepCool",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "370 mm",
      "Max CPU Cooler Height": "165 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 3,
      "Expansion Slots": 7,
      "Volume": "46 L",
      "Weight": "14.6 lbs"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'case-17',
    name: 'Cougar MX330-G Air ATX Mid Tower',
    image: "/src/assets/Laptop1.png",
    price: 49.99,
    specs: {
      "Form Factor": "ATX Mid Tower",
      "Side Panel": "Acrylic",
      "Manufacturer": "Cougar",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "350 mm",
      "Max CPU Cooler Height": "155 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 3,
      "Expansion Slots": 7,
      "Volume": "44 L",
      "Weight": "11.9 lbs"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'case-18',
    name: 'GAMDIAS TALOS E1 MESH MicroATX Mini Tower',
    image: "/src/assets/Laptop1.png",
    price: 59.99,
    specs: {
      "Form Factor": "Micro ATX Mini Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "GAMDIAS",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "320 mm",
      "Max CPU Cooler Height": "160 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 2,
      "Expansion Slots": 4,
      "Volume": "36 L",
      "Weight": "12.3 lbs"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'case-19',
    name: 'AeroCool Cylon RGB ATX Mid Tower',
    image: "/src/assets/Laptop1.png",
    price: 54.99,
    specs: {
      "Form Factor": "ATX Mid Tower",
      "Side Panel": "Acrylic",
      "Manufacturer": "AeroCool",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "330 mm",
      "Max CPU Cooler Height": "155 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 3,
      "Expansion Slots": 7,
      "Volume": "42 L",
      "Weight": "11.2 lbs"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'case-20',
    name: 'EVGA DG-75 ATX Mid Tower',
    image: "/src/assets/Laptop1.png",
    price: 129.99,
    specs: {
      "Form Factor": "ATX Mid Tower",
      "Side Panel": "Tempered Glass",
      "Manufacturer": "EVGA",
      "Color": "BLACK",
      "Transparent Side Panel": "Yes",
      "Max GPU Length": "350 mm",
      "Max CPU Cooler Height": "165 mm",
      "3.5\" Drive Bays": 2,
      "2.5\" Drive Bays": 4,
      "Expansion Slots": 7,
      "Volume": "47 L",
      "Weight": "18.7 lbs"
    },
    has3D: true,
    store: "Amazon",
    stock: "In stock"
  }
];