//client/src/components/PCBuilder/Modal/MockData/Mouse/Mouse.js
export const mouseData = [
  {
    id: 'mouse-1',
    name: 'Logitech G Pro X Superlight Wireless Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 149.99,
    specs: {
      "Mouse Brand": "Logitech",
      "Sensor": "HERO 25K",
      "Weight": "63g",
      "Connectivity": "Wireless",
      "DPI": "25600",
      "Polling Rate": "1000Hz",
      "Buttons": "5",
      "Switch Type": "Optical",
      "Battery Life": "70 hours",
      "Charging": "USB-C",
      "RGB Lighting": "No",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Ambidextrous",
      "Dimensions": "125 x 63.5 x 40 mm",
      "Material": "Plastic",
      "Skates": "PTFE",
      "Software": "Logitech G Hub"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mouse-2',
    name: 'Razer DeathAdder V3 Pro Wireless Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 159.99,
    specs: {
      "Mouse Brand": "Razer",
      "Sensor": "Focus Pro 30K",
      "Weight": "64g",
      "Connectivity": "Wireless",
      "DPI": "30000",
      "Polling Rate": "4000Hz",
      "Buttons": "5",
      "Switch Type": "Optical",
      "Battery Life": "90 hours",
      "Charging": "USB-C",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Ergonomic",
      "Dimensions": "128 x 68 x 44 mm",
      "Material": "Matte Plastic",
      "Skates": "100% PTFE",
      "Software": "Razer Synapse"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mouse-3',
    name: 'SteelSeries Aerox 3 Wireless Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 99.99,
    specs: {
      "Mouse Brand": "SteelSeries",
      "Sensor": "TrueMove Air",
      "Weight": "66g",
      "Connectivity": "Wireless",
      "DPI": "18000",
      "Polling Rate": "1000Hz",
      "Buttons": "6",
      "Switch Type": "Mechanical",
      "Battery Life": "200 hours",
      "Charging": "USB-C",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Ambidextrous",
      "Dimensions": "120 x 64 x 38 mm",
      "Material": "Plastic",
      "Skates": "PTFE",
      "Software": "SteelSeries GG"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mouse-4',
    name: 'Glorious Model O Wireless Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 79.99,
    specs: {
      "Mouse Brand": "Glorious",
      "Sensor": "BAMF",
      "Weight": "69g",
      "Connectivity": "Wireless",
      "DPI": "19000",
      "Polling Rate": "1000Hz",
      "Buttons": "6",
      "Switch Type": "Mechanical",
      "Battery Life": "71 hours",
      "Charging": "USB-C",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Ambidextrous",
      "Dimensions": "128 x 66 x 37.5 mm",
      "Material": "Honeycomb Shell",
      "Skates": "G-Skates",
      "Software": "Glorious Core"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mouse-5',
    name: 'Corsair Sabre RGB Pro Wireless Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 89.99,
    specs: {
      "Mouse Brand": "Corsair",
      "Sensor": "MARKSMAN",
      "Weight": "79g",
      "Connectivity": "Wireless",
      "DPI": "26000",
      "Polling Rate": "2000Hz",
      "Buttons": "6",
      "Switch Type": "Optical",
      "Battery Life": "60 hours",
      "Charging": "USB-C",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Claw",
      "Dimensions": "127 x 66 x 42 mm",
      "Material": "Plastic",
      "Skates": "PTFE",
      "Software": "iCUE"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mouse-6',
    name: 'Razer Viper V2 Pro Wireless Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 149.99,
    specs: {
      "Mouse Brand": "Razer",
      "Sensor": "Focus Pro 30K",
      "Weight": "58g",
      "Connectivity": "Wireless",
      "DPI": "30000",
      "Polling Rate": "4000Hz",
      "Buttons": "5",
      "Switch Type": "Optical",
      "Battery Life": "80 hours",
      "Charging": "USB-C",
      "RGB Lighting": "No",
      "Hand Orientation": "Ambidextrous",
      "Grip Style": "Claw/Fingertip",
      "Dimensions": "126.7 x 57.6 x 37.8 mm",
      "Material": "Matte Plastic",
      "Skates": "100% PTFE",
      "Software": "Razer Synapse"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mouse-7',
    name: 'Logitech G502 X Plus Lightspeed Wireless',
    image: "/src/assets/Laptop1.png",
    price: 159.99,
    specs: {
      "Mouse Brand": "Logitech",
      "Sensor": "HERO 25K",
      "Weight": "106g",
      "Connectivity": "Wireless",
      "DPI": "25600",
      "Polling Rate": "1000Hz",
      "Buttons": "11",
      "Switch Type": "LIGHTFORCE Hybrid",
      "Battery Life": "120 hours",
      "Charging": "USB-C",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Palm",
      "Dimensions": "132 x 80 x 40 mm",
      "Material": "Plastic",
      "Skates": "PTFE",
      "Software": "Logitech G Hub"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mouse-8',
    name: 'Finalmouse Starlight-12 Pro Small Wireless',
    image: "/src/assets/Laptop1.png",
    price: 189.99,
    specs: {
      "Mouse Brand": "Finalmouse",
      "Sensor": "PMW3370",
      "Weight": "42g",
      "Connectivity": "Wireless",
      "DPI": "20000",
      "Polling Rate": "1000Hz",
      "Buttons": "5",
      "Switch Type": "Mechanical",
      "Battery Life": "200 hours",
      "Charging": "USB-C",
      "RGB Lighting": "No",
      "Hand Orientation": "Ambidextrous",
      "Grip Style": "Fingertip",
      "Dimensions": "114.5 x 56 x 35.5 mm",
      "Material": "Magnesium Alloy",
      "Skates": "PTFE",
      "Software": "None"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mouse-9',
    name: 'HyperX Pulsefire Haste Wireless Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 69.99,
    specs: {
      "Mouse Brand": "HyperX",
      "Sensor": "PAW3335",
      "Weight": "61g",
      "Connectivity": "Wireless",
      "DPI": "16000",
      "Polling Rate": "1000Hz",
      "Buttons": "6",
      "Switch Type": "Mechanical",
      "Battery Life": "100 hours",
      "Charging": "USB-C",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Ambidextrous",
      "Grip Style": "Claw/Fingertip",
      "Dimensions": "124.2 x 66.8 x 38.2 mm",
      "Material": "Honeycomb Shell",
      "Skates": "PTFE",
      "Software": "HyperX NGENUITY"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mouse-10',
    name: 'ASUS ROG Keris Wireless AimPoint Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 119.99,
    specs: {
      "Mouse Brand": "ASUS",
      "Sensor": "AimPoint 36K",
      "Weight": "75g",
      "Connectivity": "Wireless",
      "DPI": "36000",
      "Polling Rate": "1000Hz",
      "Buttons": "6",
      "Switch Type": "Optical",
      "Battery Life": "119 hours",
      "Charging": "USB-C",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Claw",
      "Dimensions": "118 x 62 x 39 mm",
      "Material": "PBT Plastic",
      "Skates": "100% PTFE",
      "Software": "Armoury Crate"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mouse-11',
    name: 'Zowie EC2-C Wired Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 69.99,
    specs: {
      "Mouse Brand": "Zowie",
      "Sensor": "3360",
      "Weight": "73g",
      "Connectivity": "Wired",
      "DPI": "3200",
      "Polling Rate": "1000Hz",
      "Buttons": "5",
      "Switch Type": "Mechanical",
      "Battery Life": "N/A",
      "Charging": "N/A",
      "RGB Lighting": "No",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Palm",
      "Dimensions": "120 x 64 x 40 mm",
      "Material": "Matte Plastic",
      "Skates": "PTFE",
      "Software": "None"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mouse-12',
    name: 'Razer Basilisk V3 Wired Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 69.99,
    specs: {
      "Mouse Brand": "Razer",
      "Sensor": "Focus+ 26K",
      "Weight": "101g",
      "Connectivity": "Wired",
      "DPI": "26000",
      "Polling Rate": "1000Hz",
      "Buttons": "11",
      "Switch Type": "Optical",
      "Battery Life": "N/A",
      "Charging": "N/A",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Palm",
      "Dimensions": "130 x 60 x 42 mm",
      "Material": "Plastic",
      "Skates": "100% PTFE",
      "Software": "Razer Synapse"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mouse-13',
    name: 'Logitech MX Master 3S Wireless Productivity Mouse',
    image: "/src/assets/Laptop1.png",
    price: 99.99,
    specs: {
      "Mouse Brand": "Logitech",
      "Sensor": "Darkfield 8000",
      "Weight": "141g",
      "Connectivity": "Wireless",
      "DPI": "8000",
      "Polling Rate": "125Hz",
      "Buttons": "7",
      "Switch Type": "Quiet Mechanical",
      "Battery Life": "70 days",
      "Charging": "USB-C",
      "RGB Lighting": "No",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Palm",
      "Dimensions": "124.9 x 84.3 x 51 mm",
      "Material": "Plastic",
      "Skates": "PTFE",
      "Software": "Logi Options+"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mouse-14',
    name: 'SteelSeries Rival 3 Wireless Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 49.99,
    specs: {
      "Mouse Brand": "SteelSeries",
      "Sensor": "TrueMove Core",
      "Weight": "106g",
      "Connectivity": "Wireless",
      "DPI": "18000",
      "Polling Rate": "1000Hz",
      "Buttons": "6",
      "Switch Type": "Mechanical",
      "Battery Life": "400+ hours",
      "Charging": "USB-C",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Ambidextrous",
      "Dimensions": "120.6 x 67 x 37.9 mm",
      "Material": "Plastic",
      "Skates": "PTFE",
      "Software": "SteelSeries GG"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mouse-15',
    name: 'Glorious Model D Wireless Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 79.99,
    specs: {
      "Mouse Brand": "Glorious",
      "Sensor": "BAMF",
      "Weight": "69g",
      "Connectivity": "Wireless",
      "DPI": "19000",
      "Polling Rate": "1000Hz",
      "Buttons": "6",
      "Switch Type": "Mechanical",
      "Battery Life": "71 hours",
      "Charging": "USB-C",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Ergonomic",
      "Dimensions": "128 x 68 x 43 mm",
      "Material": "Honeycomb Shell",
      "Skates": "G-Skates",
      "Software": "Glorious Core"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mouse-16',
    name: 'Corsair Katar Pro XT Wired Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 39.99,
    specs: {
      "Mouse Brand": "Corsair",
      "Sensor": "PMW3391",
      "Weight": "73g",
      "Connectivity": "Wired",
      "DPI": "18000",
      "Polling Rate": "1000Hz",
      "Buttons": "6",
      "Switch Type": "Mechanical",
      "Battery Life": "N/A",
      "Charging": "N/A",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Ambidextrous",
      "Grip Style": "Claw/Fingertip",
      "Dimensions": "116.6 x 64.2 x 37.8 mm",
      "Material": "Plastic",
      "Skates": "PTFE",
      "Software": "iCUE"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mouse-17',
    name: 'Razer Naga Pro Wireless MMO Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 179.99,
    specs: {
      "Mouse Brand": "Razer",
      "Sensor": "Focus+ 20K",
      "Weight": "117g",
      "Connectivity": "Wireless",
      "DPI": "20000",
      "Polling Rate": "1000Hz",
      "Buttons": "14-19",
      "Switch Type": "Optical",
      "Battery Life": "150 hours",
      "Charging": "USB-C",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Palm",
      "Dimensions": "119 x 74 x 43 mm",
      "Material": "Plastic",
      "Skates": "100% PTFE",
      "Software": "Razer Synapse"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'mouse-18',
    name: 'Logitech G305 Lightspeed Wireless Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 49.99,
    specs: {
      "Mouse Brand": "Logitech",
      "Sensor": "HERO",
      "Weight": "99g",
      "Connectivity": "Wireless",
      "DPI": "12000",
      "Polling Rate": "1000Hz",
      "Buttons": "6",
      "Switch Type": "Mechanical",
      "Battery Life": "250 hours",
      "Charging": "AA Battery",
      "RGB Lighting": "No",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Ambidextrous",
      "Dimensions": "116.6 x 62.15 x 38.2 mm",
      "Material": "Plastic",
      "Skates": "PTFE",
      "Software": "Logitech G Hub"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'mouse-19',
    name: 'Microsoft Modern Mobile Mouse Wireless',
    image: "/src/assets/Laptop1.png",
    price: 34.99,
    specs: {
      "Mouse Brand": "Microsoft",
      "Sensor": "Optical",
      "Weight": "78g",
      "Connectivity": "Wireless",
      "DPI": "1000",
      "Polling Rate": "125Hz",
      "Buttons": "3",
      "Switch Type": "Mechanical",
      "Battery Life": "12 months",
      "Charging": "AA Battery",
      "RGB Lighting": "No",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Palm",
      "Dimensions": "115 x 62.5 x 32.2 mm",
      "Material": "Plastic",
      "Skates": "Plastic",
      "Software": "None"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'mouse-20',
    name: 'Redragon M808 Storm Wired Gaming Mouse',
    image: "/src/assets/Laptop1.png",
    price: 24.99,
    specs: {
      "Mouse Brand": "Redragon",
      "Sensor": "PixArt 3327",
      "Weight": "105g",
      "Connectivity": "Wired",
      "DPI": "10000",
      "Polling Rate": "1000Hz",
      "Buttons": "7",
      "Switch Type": "Mechanical",
      "Battery Life": "N/A",
      "Charging": "N/A",
      "RGB Lighting": "Yes",
      "Hand Orientation": "Right-handed",
      "Grip Style": "Palm",
      "Dimensions": "126 x 68 x 41 mm",
      "Material": "Plastic",
      "Skates": "PTFE",
      "Software": "None"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  }
];