//client/src/components/PCBuilder/Modal/MockData/RAM/Ram.js
export const ramData = [
  {
    id: 'ram-1',
    name: 'Corsair Vengeance RGB 32GB DDR5 6000MHz',
    image: "/src/assets/Laptop1.png",
    price: 7410.00, // Converted from 129.99 USD to PHP
    specs: {
      "RAM Type": "DDR5",
      "Form Factor": "288-pin DIMM (DDR5)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "Corsair",
      "Color": "BLACK",
      "Heat Spreader": "Yes",
      "RGB": "Yes",
      "Speed": "6000 MHz",
      "Total Capacity": "32 GB",
      "Number of Modules": 2,
      "CAS Latency": 36,
      "Module Height": "44 mm",
      "Timing": "CL36",
      "Voltage": "1.35V",
      "XMP/EXPO": "XMP 3.0"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'ram-2',
    name: 'G.Skill Trident Z5 RGB 64GB DDR5 6400MHz',
    image: "/src/assets/Laptop1.png",
    price: 14250.00, // Converted from 249.99 USD to PHP
    specs: {
      "RAM Type": "DDR5",
      "Form Factor": "288-pin DIMM (DDR5)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "G.Skill",
      "Color": "BLACK",
      "Heat Spreader": "Yes",
      "RGB": "Yes",
      "Speed": "6400 MHz",
      "Total Capacity": "64 GB",
      "Number of Modules": 2,
      "CAS Latency": 32,
      "Module Height": "42 mm",
      "Timing": "CL32",
      "Voltage": "1.4V",
      "XMP/EXPO": "XMP 3.0"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'ram-3',
    name: 'Kingston FURY Beast 16GB DDR5 5200MHz',
    image: "/src/assets/Laptop1.png",
    price: 4560.00, // Converted from 79.99 USD to PHP
    specs: {
      "RAM Type": "DDR5",
      "Form Factor": "288-pin DIMM (DDR5)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "Kingston",
      "Color": "BLACK",
      "Heat Spreader": "Yes",
      "RGB": "No",
      "Speed": "5200 MHz",
      "Total Capacity": "16 GB",
      "Number of Modules": 2,
      "CAS Latency": 40,
      "Module Height": "35 mm",
      "Timing": "CL40",
      "Voltage": "1.25V",
      "XMP/EXPO": "XMP 3.0"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'ram-4',
    name: 'Crucial Pro 32GB DDR4 3200MHz',
    image: "/src/assets/Laptop1.png",
    price: 3990.00, // Converted from 69.99 USD to PHP
    specs: {
      "RAM Type": "DDR4",
      "Form Factor": "288-pin DIMM (DDR4)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "Crucial",
      "Color": "BLACK",
      "Heat Spreader": "Yes",
      "RGB": "No",
      "Speed": "3200 MHz",
      "Total Capacity": "32 GB",
      "Number of Modules": 2,
      "CAS Latency": 22,
      "Module Height": "32 mm",
      "Timing": "极L22",
      "Voltage": "1.2V",
      "XMP/EXPO": "XMP 2.0"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'ram-5',
    name: 'Corsair Vengeance LPX 64GB DDR4 3600MHz',
    image: "/src/assets/Laptop1.png",
    price: 8550.00, // Converted from 149.99 USD to PHP
    specs: {
      "RAM Type": "DDR4",
      "Form Factor": "288-pin DIMM (DDR4)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "Corsair",
      "Color": "BLACK",
      "Heat Spreader": "Yes",
      "RGB": "No",
      "Speed": "3600 MHz",
      "Total Capacity": "极4 GB",
      "Number of Modules": 2,
      "CAS Latency": 18,
      "Module Height": "31 mm",
      "Timing": "CL18",
      "Voltage": "1.35V",
      "XMP/EXPO": "XMP 2.0"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'ram-6',
    name: 'G.Skill Ripjaws V 16GB DDR4 4000MHz',
    image: "/极rc/assets/Laptop1.png",
    price: 5130.00, // Converted from 89.99 USD to PHP
    specs: {
      "RAM Type": "DDR4",
      "Form Factor": "288-pin DIMM (DDR4)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "G.Skill",
      "Color": "RED",
      "Heat Spreader": "Yes",
      "RGB": "No",
      "Speed": "4000 MHz",
      "Total Capacity": "16 GB",
      "Number of Modules": 2,
      "CAS Latency": 19,
      "Module Height": "42 mm",
      "Timing": "CL19",
      "Voltage": "1.35极",
      "XMP/EXPO": "XMP 2.0"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'ram-7',
    name: 'Teamgroup T-Force Delta RGB 32GB DDR4 3600MHz',
    image: "/src/assets/Laptop1.png",
    price: 4560.00, // Converted from 79.99 USD to PHP
    specs: {
      "RAM Type": "DDR4",
      "Form Factor": "288-pin DIMM (DDR4)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "TEAMGROUP",
      "Color": "WHITE",
      "Heat Spreader": "Yes",
      "RGB": "Yes",
      "Speed": "3600 MHz",
      "Total Capacity": "32 GB",
      "Number of Modules": 2,
      "CAS Latency": 18,
      "Module Height": "44 mm",
      "Timing": "CL18",
      "Voltage": "1.35V",
      "XMP/EXPO": "XMP 2.0"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'ram-8',
    name: 'Samsung 32GB DDR5 4800MHz ECC Registered',
    image: "/src/assets/Laptop1.png",
    price: 11400.00, // Converted from 199.99 USD to PHP
    specs: {
      "RAM Type": "DDR5",
      "Form Factor": "288-pin DIMM (DDR5)",
      "ECC": "ECC",
      "Registered": "Registered",
      "Manufacturer": "Samsung",
      "Color": "GREEN",
      "Heat Spreader": "No",
      "RGB": "No",
      "Speed": "4800 MHz",
      "Total Capacity": "32 GB",
      "Number of Modules": 1,
      "CAS Latency": 40,
      "Module Height": "31 mm",
      "Timing": "CL40",
      "Voltage": "1.1V",
      "XMP/EXPO": "No"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'ram-9',
    name: 'HyperX Fury 8GB DDR3 1866MHz',
    image: "/src/assets/Laptop1.png",
    price: 2280.00, // Converted from 39.99 USD to PHP
    specs: {
      "RAM Type": "DDR3",
      "Form Factor": "240-pin DIMM (DDR3)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "HyperX",
      "Color": "BLUE",
      "Heat Spreader": "Yes",
      "RGB": "No",
      "Speed": "1866 MHz",
      "Total Capacity": "8 GB",
      "Number of Modules": 1,
      "CAS Latency": 10,
      "Module Height": "34 mm",
      "Timing": "CL10",
      "Voltage": "1.5V",
      "XMP/EXPO": "XMP 1.3"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'ram-10',
    name: 'Patriot Viper Steel 128GB DDR4 3600MHz',
    image: "/src/assets/Laptop1.png",
    price: 17100.00, // Converted from 299.99 USD to PHP
    specs: {
      "RAM Type": "DDR4",
      "Form Factor": "288-pin DIMM (DDR4)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "Patriot",
      "Color": "BLACK",
      "Heat Spreader": "Yes",
      "RGB": "极",
      "Speed": "3600 MHz",
      "Total Capacity": "128 GB",
      "Number of Modules": 4,
      "CAS Latency": 18,
      "Module Height": "42 mm",
      "Tim极": "CL18",
      "Voltage": "1.35V",
      "XMP/EXPO": "XMP 2.0"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'ram-11',
    name: 'OLOy Blade RGB 16GB DDR5 7200MHz',
    image: "/src/assets/Laptop1.png",
    price: 6840.00, // Converted from 119.99 USD to PHP
    specs: {
      "RAM Type": "DDR5",
      "Form Factor": "288-pin DIMM (DDR5)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "OLOy",
      "Color": "BLACK",
      "Heat Spreader": "Yes",
      "RGB": "Yes",
      "Speed": "7200 MHz",
      "Total Capacity": "16 GB",
      "Number of Modules": 2,
      "CAS Latency": 34,
      "Module Height": "45 mm",
      "Timing": "CL34",
      "Voltage": "1.4V",
      "XMP/EXPO": "XMP 3.0"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'ram-12',
    name: 'Silicon Power Zenith 64GB DDR5 6000MHz',
    image: "/src/assets/Laptop1极",
    price: 11400.00, // Converted from 199.99 USD to PHP
    specs: {
      "RAM Type": "DDR5",
      "Form Factor": "288-pin DIMM (DDR5)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "Silicon Power",
      "Color": "BLACK",
      "Heat Spreader": "Yes",
      "RGB": "No",
      "Speed": "6000 MHz",
      "Total Capacity": "64 GB",
      "Number of Modules": 2,
      "CAS Latency": 36,
      "Module Height": "33 mm",
      "Timing": "CL36",
      "Voltage": "1.35V",
      "XMP/EXPO": "XMP 3.0"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'ram-13',
    name: 'ADATA XPG Lancer 32GB DDR5 8000MHz',
    image: "/src/assets/Laptop1.png",
    price: 10260.00, // Converted from 179.99 USD to PHP
    specs: {
      "RAM Type": "DDR5",
      "Form Factor": "288-pin DIMM (DDR5)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "ADATA",
      "Color": "BLACK",
      "Heat Spreader": "Yes",
      "RGB": "Yes",
      "Speed": "8000 MHz",
      "Total Capacity": "32 GB",
      "Number of Modules": 2,
      "CAS Latency": 38,
      "Module Height": "43 mm",
      "Timing": "CL38",
      "Voltage": "1.45V",
      "XMP/EXPO": "XMP 3.0"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'ram-14',
    name: 'Micron 16GB DDR4 2666MHz SODIMM',
    image: "/src/assets/Laptop1.png",
    price: 2850.00, // Converted from 49.99 USD to PHP
    specs: {
      "RAM Type": "DDR4",
      "Form Factor": "260-pin SODIMM (DDR4)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "Micron",
      "Color": "GREEN",
      "Heat Spreader": "No",
      "RGB": "No",
      "Speed": "2666 MHz",
      "Total Capacity": "16 GB",
      "Number of Modules": 极,
      "CAS Latency": 19,
      "Module Height": "30 mm",
      "Timing": "CL19",
      "Voltage": "1.2V",
      "XMP/EXPO": "No"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'ram-15',
    name: 'G.Skill Trident Z Neo 32GB DDR4 3800MHz',
    image: "/src/assets/Laptop1.png",
    price: 7410.00, // Converted from 129.99 USD to PHP
    specs: {
      "RAM Type": "DDR4",
      "Form Factor": "288-pin DIMM (DDR4)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "G.Skill",
      "Color": "BLACK",
      "Heat Spreader": "Yes",
      "RGB": "Yes",
      "Speed": "3800 MHz",
      "Total Capacity": "32 GB",
      "Number of Modules": 2,
      "CAS Latency": 14,
      "Module Height": "44 mm",
      "Timing": "CL14",
      "Voltage": "1.5V",
      "XMP/EXPO": "XMP 2.0"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'ram-16',
    name: 'Kingston ValueRAM 8GB DDR3 1600MHz',
    image: "/src/assets/Laptop1.png",
    price: 1710.00, // Converted from 29.99 USD to PHP
    specs: {
      "RAM Type": "DDR3",
      "Form Factor": "240-pin DIMM (DDR3)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "Kingston",
      "Color": "GREEN",
      "Heat Spreader": "No",
      "RGB": "No",
      "Speed": "1600 MHz",
      "Total Capacity": "8 GB",
      "Number of Modules": 1,
      "CAS Latency": 11,
      "Module Height": "30 mm",
      "Timing": "CL11",
      "Voltage": "1.5V",
      "XMP/EXPO": "No"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'ram-17',
    name: 'Corsair Dominator Platinum 64GB DDR5 6600MHz',
    image: "/src/assets/Laptop1.png",
    price: 19950.00, // Converted from 349.99 USD to PHP
    specs: {
      "RAM Type": "DDR5",
      "Form Factor": "288-pin DIMM (DDR5)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "Corsair",
      "Color": "BLACK",
      "Heat Spreader": "Yes",
      "RGB": "Yes",
      "Speed": "6600 MHz",
      "Total Capacity": "64 GB",
      "Number of Modules": 2,
      "CAS Latency": 32,
      "Module Height": "45 mm",
      "Timing": "CL32",
      "Voltage": "1.4V",
      "XMP/EXPO": "XMP 3.0"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'ram-18',
    name: 'Teamgroup Vulcan Z 16GB DDR4 3200MHz',
    image: "/src/assets/Laptop1.png",
    price: 3500.99,
    specs: {
      "RAM Type": "DDR4",
      "Form Factor": "288-pin DIMM (DDR4)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "TEAMGROUP",
      "Color": "RED",
      "Heat Spreader": "Yes",
      "RGB": "No",
      "Speed": "3200 MHz",
      "Total Capacity": "16 GB",
      "Number of Modules": 2,
      "CAS Latency": 16,
      "Module Height": "32 mm",
      "Timing": "CL16",
      "Voltage": "1.35V",
      "XMP/EXPO": "XMP 2.0"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'ram-19',
    name: 'Samsung 128GB DDR4 3200MHz ECC Registered',
    image: "/src/assets/Laptop1.png",
    price: 36999.99,
    specs: {
      "RAM Type": "DDR4",
      "Form Factor": "288-pin DIMM (DDR4)",
      "ECC": "ECC",
      "Registered": "Registered",
      "Manufacturer": "Samsung",
      "Color": "GREEN",
      "Heat Spreader": "No",
      "RGB": "No",
      "Speed": "3200 MHz",
      "Total Capacity": "128 GB",
      "Number of Modules": 4,
      "CAS Latency": 22,
      "Module Height": "31 mm",
      "Timing": "CL22",
      "Voltage": "1.2V",
      "XMP/EXPO": "No"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'ram-20',
    name: 'GeIL Orion RGB 32GB DDR5 5600MHz',
    image: "/src/assets/Laptop1.png",
    price: 5999.99,
    specs: {
      "RAM Type": "DDR5",
      "Form Factor": "288-pin DIMM (DDR5)",
      "ECC": "Non-ECC",
      "Registered": "Unbuffered",
      "Manufacturer": "GeIL",
      "Color": "WHITE",
      "Heat Spreader": "Yes",
      "RGB": "Yes",
      "Speed": "5600 MHz",
      "Total Capacity": "32 GB",
      "Number of Modules": 2,
      "CAS Latency": 36,
      "Module Height": "44 mm",
      "Timing": "CL36",
      "Voltage": "1.35V",
      "XMP/EXPO": "XMP 3.0"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  }
];