//client/src/components/PCBuilder/Modal/MockData/Case Fan/CaseFan.js
export const caseFanData = [
  {
    id: 'fan-1',
    name: 'Noctua NF-A12x25 PWM Premium Quiet Fan',
    image: "/src/assets/Laptop1.png",
    price: 29.99,
    specs: {
      "Brand": "Noctua",
      "Size": "120mm",
      "Airflow": "60.1 CFM",
      "Noise Level": "22.6 dB",
      "Static Pressure": "2.34 mmH₂O",
      "RPM": "2000 RPM",
      "Bearing Type": "SSO2",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BROWN",
      "MTBF": "150,000 hours",
      "Warranty": "6 years"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'fan-2',
    name: 'Corsair LL120 RGB 120mm Dual Light Loop RGB LED PWM Fan',
    image: "/src/assets/Laptop1.png",
    price: 39.99,
    specs: {
      "Brand": "Corsair",
      "Size": "120mm",
      "Airflow": "43.25 CFM",
      "Noise Level": "24.8 dB",
      "Static Pressure": "1.61 mmH₂O",
      "RPM": "600-1500 RPM",
      "Bearing Type": "Rifle Bearing",
      "Connector": "4-pin PWM",
      "LED": "RGB",
      "Color": "BLACK",
      "MTBF": "35,000 hours",
      "Warranty": "2 years"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'fan-3',
    name: 'ARCTIC P12 PWM PST 120mm Pressure Optimized Fan',
    image: "/src/assets/Laptop1.png",
    price: 9.99,
    specs: {
      "Brand": "ARCTIC",
      "Size": "120mm",
      "Airflow": "56.3 CFM",
      "Noise Level": "22.5 dB",
      "Static Pressure": "2.2 mmH₂O",
      "RPM": "1800 RPM",
      "Bearing Type": "Fluid Dynamic Bearing",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BLACK",
      "MTBF": "50,000 hours",
      "Warranty": "10 years"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'fan-4',
    name: 'be quiet! Silent Wings 3 140mm PWM High-Speed Fan',
    image: "/src/assets/Laptop1.png",
    price: 24.90,
    specs: {
      "Brand": "be quiet!",
      "Size": "140mm",
      "Airflow": "59.5 CFM",
      "Noise Level": "24.3 dB",
      "Static Pressure": "1.79 mmH₂O",
      "RPM": "1600 RPM",
      "Bearing Type": "Rifle Bearing",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BLACK",
      "MTBF": "80,000 hours",
      "Warranty": "3 years"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'fan-5',
    name: 'Lian Li UNI FAN SL120 120mm RGB PWM Fan',
    image: "/src/assets/Laptop1.png",
    price: 29.99,
    specs: {
      "Brand": "Lian Li",
      "Size": "120mm",
      "Airflow": "58.54 CFM",
      "Noise Level": "31.5 dB",
      "Static Pressure": "2.54 mmH₂O",
      "RPM": "800-1900 RPM",
      "Bearing Type": "Hydraulic Bearing",
      "Connector": "4-pin PWM",
      "LED": "RGB",
      "Color": "BLACK",
      "MTBF": "50,000 hours",
      "Warranty": "2 years"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'fan-6',
    name: 'Noctua NF-A14 PWM 140mm Premium Quiet Fan',
    image: "/src/assets/Laptop1.png",
    price: 23.90,
    specs: {
      "Brand": "Noctua",
      "Size": "140mm",
      "Airflow": "82.5 CFM",
      "Noise Level": "24.6 dB",
      "Static Pressure": "2.08 mmH₂O",
      "RPM": "1500 RPM",
      "Bearing Type": "SSO2",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BROWN",
      "MTBF": "150,000 hours",
      "Warranty": "6 years"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'fan-7',
    name: 'Cooler Master SickleFlow 120 120mm ARGB Fan',
    image: "/src/assets/Laptop1.png",
    price: 12.99,
    specs: {
      "Brand": "Cooler Master",
      "Size": "120mm",
      "Airflow": "62 CFM",
      "Noise Level": "27 dB",
      "Static Pressure": "2.5 mmH₂O",
      "RPM": "650-1800 RPM",
      "Bearing Type": "Rifle Bearing",
      "Connector": "4-pin PWM",
      "LED": "ARGB",
      "Color": "BLACK",
      "MTBF": "40,000 hours",
      "Warranty": "2 years"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'fan-8',
    name: 'Phanteks PH-F120T30 120mm Ultra High Performance Fan',
    image: "/src/assets/Laptop1.png",
    price: 34.99,
    specs: {
      "Brand": "Phanteks",
      "Size": "120mm",
      "Airflow": "101 CFM",
      "Noise Level": "37.7 dB",
      "Static Pressure": "5.61 mmH₂O",
      "RPM": "520-3000 RPM",
      "Bearing Type": "Dual Ball Bearing",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BLACK",
      "MTBF": "100,000 hours",
      "Warranty": "5 years"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'fan-9',
    name: 'ARCTIC F12 PWM PST 120mm Value Pack (5 Fans)',
    image: "/src/assets/Laptop1.png",
    price: 29.99,
    specs: {
      "Brand": "ARCTIC",
      "Size": "120mm",
      "Airflow": "53 CFM",
      "Noise Level": "22.5 dB",
      "Static Pressure": "1.2 mmH₂O",
      "RPM": "1350 RPM",
      "Bearing Type": "Fluid Dynamic Bearing",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BLACK",
      "MTBF": "50,000 hours",
      "Warranty": "10 years"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'fan-10',
    name: 'be quiet! Light Wings 120mm PWM High-Speed RGB Fan',
    image: "/src/assets/Laptop1.png",
    price: 26.90,
    specs: {
      "Brand": "be quiet!",
      "Size": "120mm",
      "Airflow": "53.3 CFM",
      "Noise Level": "30.2 dB",
      "Static Pressure": "2.2 mmH₂O",
      "RPM": "2500 RPM",
      "Bearing Type": "Rifle Bearing",
      "Connector": "4-pin PWM",
      "LED": "RGB",
      "Color": "WHITE",
      "MTBF": "80,000 hours",
      "Warranty": "3 years"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'fan-11',
    name: 'Noctua NF-F12 iPPC-3000 PWM 120mm Industrial Fan',
    image: "/src/assets/Laptop1.png",
    price: 29.90,
    specs: {
      "Brand": "Noctua",
      "Size": "120mm",
      "Airflow": "109.8 CFM",
      "Noise Level": "43.5 dB",
      "Static Pressure": "7.63 mmH₂O",
      "RPM": "3000 RPM",
      "Bearing Type": "SSO2",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BLACK",
      "MTBF": "150,000 hours",
      "Warranty": "3 years"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'fan-12',
    name: 'Corsair QL120 RGB 120mm PWM Fan',
    image: "/src/assets/Laptop1.png",
    price: 44.99,
    specs: {
      "Brand": "Corsair",
      "Size": "120mm",
      "Airflow": "41.8 CFM",
      "Noise Level": "26 dB",
      "Static Pressure": "1.55 mmH₂O",
      "RPM": "1500 RPM",
      "Bearing Type": "Rifle Bearing",
      "Connector": "4-pin PWM",
      "LED": "RGB",
      "Color": "BLACK",
      "MTBF": "35,000 hours",
      "Warranty": "2 years"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'fan-13',
    name: 'Thermalright TL-C12 120mm PWM Fan',
    image: "/src/assets/Laptop1.png",
    price: 8.99,
    specs: {
      "Brand": "Thermalright",
      "Size": "120mm",
      "Airflow": "66.17 CFM",
      "Noise Level": "25.6 dB",
      "Static Pressure": "1.53 mmH₂O",
      "RPM": "1550 RPM",
      "Bearing Type": "Rifle Bearing",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BLACK",
      "MTBF": "50,000 hours",
      "Warranty": "2 years"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'fan-14',
    name: 'Fractal Design Dynamic X2 GP-12 120mm PWM Fan',
    image: "/src/assets/Laptop1.png",
    price: 14.99,
    specs: {
      "Brand": "Fractal Design",
      "Size": "120mm",
      "Airflow": "52.3 CFM",
      "Noise Level": "22.4 dB",
      "Static Pressure": "0.88 mmH₂O",
      "RPM": "1000 RPM",
      "Bearing Type": "Fluid Dynamic Bearing",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BLACK",
      "MTBF": "100,000 hours",
      "Warranty": "3 years"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'fan-15',
    name: 'EK-Vardar EVO 120ER 120mm PWM D-RGB Fan',
    image: "/src/assets/Laptop1.png",
    price: 22.99,
    specs: {
      "Brand": "EK",
      "Size": "120mm",
      "Airflow": "77.4 CFM",
      "Noise Level": "38.5 dB",
      "Static Pressure": "3.16 mmH₂O",
      "RPM": "500-2200 RPM",
      "Bearing Type": "Fluid Dynamic Bearing",
      "Connector": "4-pin PWM",
      "LED": "D-RGB",
      "Color": "BLACK",
      "MTBF": "50,000 hours",
      "Warranty": "2 years"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'fan-16',
    name: 'Scythe Kaze Flex 120mm PWM Fan',
    image: "/src/assets/Laptop1.png",
    price: 13.99,
    specs: {
      "Brand": "Scythe",
      "Size": "120mm",
      "Airflow": "51.17 CFM",
      "Noise Level": "24.9 dB",
      "Static Pressure": "1.05 mmH₂O",
      "RPM": "300-1200 RPM",
      "Bearing Type": "Fluid Dynamic Bearing",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BLACK",
      "MTBF": "120,000 hours",
      "Warranty": "2 years"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'fan-17',
    name: 'upHere 120mm RGB PWM Case Fan 3-Pack',
    image: "/src/assets/Laptop1.png",
    price: 29.99,
    specs: {
      "Brand": "upHere",
      "Size": "120mm",
      "Airflow": "56.5 CFM",
      "Noise Level": "26 dB",
      "Static Pressure": "1.2 mmH₂O",
      "RPM": "800-1500 RPM",
      "Bearing Type": "Hydraulic Bearing",
      "Connector": "4-pin PWM",
      "LED": "RGB",
      "Color": "BLACK",
      "MTBF": "30,000 hours",
      "Warranty": "1 year"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  },
  {
    id: 'fan-18',
    name: 'NoiseBlocker NB-eLoop B12-PS 120mm PWM Fan',
    image: "/src/assets/Laptop1.png",
    price: 27.90,
    specs: {
      "Brand": "NoiseBlocker",
      "Size": "120mm",
      "Airflow": "64.3 CFM",
      "Noise Level": "28.9 dB",
      "Static Pressure": "1.83 mmH₂O",
      "RPM": "1900 RPM",
      "Bearing Type": "Ball Bearing",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BLACK",
      "MTBF": "100,000 hours",
      "Warranty": "3 years"
    },
    has3D: false,
    store: "Best Buy",
    stock: "In stock"
  },
  {
    id: 'fan-19',
    name: 'SilverStone Air Slimmer 120 120mm Slim PWM Fan',
    image: "/src/assets/Laptop1.png",
    price: 19.99,
    specs: {
      "Brand": "SilverStone",
      "Size": "120mm",
      "Airflow": "50.3 CFM",
      "Noise Level": "23.6 dB",
      "Static Pressure": "1.59 mmH₂O",
      "RPM": "2500 RPM",
      "Bearing Type": "Fluid Dynamic Bearing",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BLACK",
      "MTBF": "60,000 hours",
      "Warranty": "2 years"
    },
    has3D: false,
    store: "Amazon",
    stock: "In stock"
  },
  {
    id: 'fan-20',
    name: 'Gelid Solutions Silent 9 92mm PWM Fan',
    image: "/src/assets/Laptop1.png",
    price: 9.99,
    specs: {
      "Brand": "Gelid Solutions",
      "Size": "92mm",
      "Airflow": "33.6 CFM",
      "Noise Level": "19.8 dB",
      "Static Pressure": "1.08 mmH₂O",
      "RPM": "2000 RPM",
      "Bearing Type": "Nanoflux Bearing",
      "Connector": "4-pin PWM",
      "LED": "None",
      "Color": "BLACK",
      "MTBF": "100,000 hours",
      "Warranty": "3 years"
    },
    has3D: false,
    store: "Newegg",
    stock: "In stock"
  }
];